### ISSUE TITLE
ERROR: Failed to download Chromium r515411! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.

### ISSUE THREAD

**Issue by lixiaodong** [Chatie/wechaty#1001]
when i execute npm install,throws errors like this:
![image](https://user-images.githubusercontent.com/1568575/33709968-137ac0ae-db7a-11e7-9c3c-1541ea528f81.png)

**Comment by zixia** [comment]
Duplicated with #867
