### ISSUE TITLE
How to pop out the browser window after v0.9

### ISSUE THREAD

**Issue by forconz** [Chatie/wechaty#1003]
我参考 https://github.com/Chatie/wechaty/blob/master/example/gist-bot/index.ts 写的bot，扫码后，浏览器不弹出来了，为什么？
`
const Wechaty = require('wechaty').default;

import { onError }   from './listener/error'
import { onFriend }   from './listener/friend'
import { onHeartbeat }   from './listener/heartbeat'
import { onLogin }   from './listener/login'
import { onLogOut }   from './listener/logout'
import { onMessage }   from './listener/message'
import { onRoomJoin }   from './listener/room-join'
import { onRoomLeave }   from './listener/room-leave'
import { onRoomTopic }   from './listener/room-topic'

const bot = Wechaty.instance() // Wechaty.instance({ profile: config.default.DEFAULT_PROFILE })
  // .on('scan', onScan)
  .on('scan', (url, code) => {
    if (!/201|200/.test(String(code))) {
      const loginUrl = url.replace(/\/qrcode\//, '/l/')
      require('qrcode-terminal').generate(loginUrl)
    }
    console.log(`${url}\n[${code}] Scan QR Code in above url to login: `)
  })
  .on('login', onLogin)
  .on('logout', onLogOut)
  .on('error', onError)
  .on('message', onMessage)
  .on('friend', onFriend)
  .on('heartbeat', onHeartbeat)
  .on('room-join', onRoomJoin)
  .on('room-leave', onRoomLeave)
  .on('room-topic', onRoomTopic)
  .start()
  .catch(e => console.error(e));
`
main.ts 参考index.ts写了以后，编译输出main.js到out文件夹下
D:\robot\out> node main.js
15:55:12 INFO Wechaty v0.12.5 starting...
[二维码]
https://login.weixin.qq.com/qrcode/QaauJY-jDw==
[0] Scan QR Code in above url to login:
https://login.weixin.qq.com/qrcode/QaauJY-jDw==
[201] Scan QR Code in above url to login:

日志到这里就结束了，0.9的时候，我记得扫码的时候，浏览器都弹出来的，可以扫shell上的二维码，或者扫浏览器上的二维码，现在0.12怎么不弹出谷歌浏览器了？

**Comment by forconz** [comment]
https://github.com/lijiarui/wechaty-getting-started
用这个例子，wechaty使用^0.7.3，谷歌浏览器能弹出来，
package.json"wechaty":后面版本号修改为"^0.13.36"以后，谷歌浏览器弹不出来。

mybot.js的代码没变。

谷歌浏览器最好能弹出来，这样还可以通过浏览器聊天。

**Comment by forconz** [comment]
跟\node_modules\puppeteer\.local-chromium\win64-508693\chrome-win32\chrome.exe有关系

也有可能是wechat 0.12版本以后的配置有关系，默认不弹出chrome browser了
我现在把wechaty改成0.9，只能这样跑了

**Comment by forconz** [comment]
0.9.0 浏览器在scan时会弹出来，0.12和0.13.36都不弹出来了。

**Comment by zixia** [comment]
Yes, you are right. We had set the default to WECHATY_HEAD=0 after v0.9.

If you want the browser window popped out, you can set WECHATY_HEAD=1 before running Wechaty.

```
WECHATY_HEAD=1
```

**Comment by forconz** [comment]
PS D:\CarRental\source\wechat\Marketer\test> set WECHATY_HEAD=1
PS D:\CarRental\source\wechat\Marketer\test> node mybot.js
19:38:15 WARN Wechaty init() DEPRECATED and will be removed after Jun 2018. Use start() instead.
19:38:15 INFO Wechaty v0.12.5 starting...

How to set WECHATY_HEAD=1?
I set WECHATY_HEAD=1, but it do not pop out the browser window.

**Comment by forconz** [comment]
在.vscode目录下创建launch.json

"env": {
                "WECHATY_HEAD": "1"
            },

也不怎么好使

**Comment by forconz** [comment]
process.env['WECHATY_HEAD']=1;
console.log("WECHATY_HEAD：" + process.env['WECHATY_HEAD']);

Wechaty.instance()
...
.init();

windows powershell show:
PS D:\CarRental\source\wechat\Marketer\test> node mybot.js
WECHATY_HEAD：1
20:02:10 WARN Wechaty init() DEPRECATED and will be removed after Jun 2018. Use start() instead.
20:02:10 INFO Wechaty v0.12.5 starting...

 it do not pop out the browser window.

**Comment by forconz** [comment]
How to set WECHATY_HEAD=1？

**Comment by zixia** [comment]
`process.env['WECHATY_HEAD']=1` should work with the lastest master branch.

Had you tried v0.13?

**Comment by zixia** [comment]
Close this issue due to no response for a long period.

Hope the problem had been resolved.
