### ISSUE TITLE
获取所有群

### ISSUE THREAD

**Issue by sowhatwill** [Chatie/wechaty#1020]
Room.findAll()  获取所有群不稳定,有多有少.

**Comment by lijiarui** [comment]
This works as expect. Because web wechat cannot get all groups in your wechat

What I did now like this:
```ts
async function initRoom() {
  console.log('begin to initRoom!')
  const roomList = await Room.findAll()
  if (roomList.length < MAX_GROUP) {
    console.warn(`room num not ready. retry after 10 seconds. room num: ${roomList.length}`)
    setTimeout(initRoom, 10000)
    return
  }
  return roomList
}
```

**Comment by sowhatwill** [comment]
谢谢了,如果这样做的话,我就需要改一下业务流程了.

**Comment by forconz** [comment]
如何知道room的群主信息？

/**
     * @private
     * Get room's owner from the room.
     * Not recommend, because cannot always get the owner
     * @returns {(Contact | null)}
     */
    owner(): Contact | null;

**Comment by forconz** [comment]
@lijirui  MAX_GROUP是多少？

**Comment by lijiarui** [comment]
1. If you can get `room.owner()`, then console log the contact, you can get the room owner's information. 

2. MAX_GROUP depends on your situation, I don't know how rooms in your wechat bot.

**Comment by zixia** [comment]
This feature might be able to be enhanced by the New Puppets.

See: #1167

**Comment by zixia** [comment]
Close this issue due to inactivated for 60 days.
