### ISSUE TITLE
emoji can't display

### ISSUE THREAD

**Issue by threescales** [Chatie/wechaty#1038]
example：
normal：@|･ω･｀)💓 娟
wrong：@|･ω･｀)[emoji1f49e] 娟

**Comment by threescales** [comment]
I used the api of message.say("",Contact).And I view the source code。
![image](https://user-images.githubusercontent.com/15061441/34398469-0b61ed8e-ebba-11e7-88a3-be506a74c38b.png)

**Comment by suntong** [comment]
How about those emoji that are **plain unicode**, do they display as expected?

**Comment by threescales** [comment]
@suntong simple emoji is expected.

**Comment by zixia** [comment]
Move to <https://github.com/Chatie/wechaty-puppet-puppeteer/issues/30>
