### ISSUE TITLE
如果没有加该微信账号为好友，那么在微信群里能否获取到我为该微信账号设置的备注名称？

### ISSUE THREAD

**Issue by guoleisong** [Chatie/wechaty#1045]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?

### Full Output Logs

```shell
$ WECHATY_LOG=silly npm run ts-node mybot.ts

# or 

$ WECHATY_LOG=silly node dist/mybot.js
```

<details>
<summary>
Show Logs
</summary>
### Paste the full output logs here with `WECHATY_LOG=silly` set 

```shell
# PASTE FULL LOG OUTPUT AT HERE:



```
</details>

**Comment by lijiarui** [comment]
You can have a try by yourself if web wechat can do this, wechaty can have the ability do this.

**Comment by guoleisong** [comment]
好的 非常感谢！
