### ISSUE TITLE
contact.weixin showing openid; how do we get the "微信号"?

### ISSUE THREAD

**Issue by bluefurrymonster** [Chatie/wechaty#1057]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)

China

1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?

Aliyun

### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 
Starting Wechaty v0.13.41 with Node.js v9.4.0 ...

> wechaty@0.13.41 doctor /wechaty
> npm run check-node-version && ts-node bin/doctor

> wechaty@0.13.41 check-node-version /wechaty
> check-node-version --node ">= 7"

  #### Wechaty Doctor

  1. Wechaty version: #git[c8ce385]
  2. Linux x64 version 3.10.0-514.26.2.el7.x86_64 memory 272/1839 MB
  3. Docker: true
  4. Node version: v9.4.0
  5. Tcp IPC TEST: PASS

### Expected behavior

contact.weixin suppose to get the weixin id for friends.

### Actual behavior

contact.weixin printing out openid

### Steps to reproduce the behavior (and fixes, if any)

docker run -ti --rm --volume="$(pwd)":/bot zixia/wechaty contact-bot.ts

### Full Output Logs

```shell
$ WECHATY_LOG=silly npm run ts-node mybot.ts

# or 

$ WECHATY_LOG=silly node dist/mybot.js
```

<details>
<summary>
Show Logs
</summary>
### Paste the full output logs here with `WECHATY_LOG=silly` set 

```shell
# PASTE FULL LOG OUTPUT AT HERE:



```
</details>

**Comment by bluefurrymonster** [comment]
and thank you. I appreciate your work. 谢谢

**Comment by lijiarui** [comment]
Wechaty cannot get weixin id, because web wechat cannot get weixin id.

Also, contact.weixin cannot get openid, if it can get an id, it is weixin id, or it is null.

**Comment by zixia** [comment]
This feature might be support by other Puppet.

See #1167
