### ISSUE TITLE
避免重启时的重复扫码

### ISSUE THREAD

**Issue by suntong** [Chatie/wechaty#1061]
How to 避免重启时的重复扫码?

### Provide Your Network Information

1. Where is the location of your server? (Out China, in reputable cloud farm)
1. Which cloud platform are you using? Private cloud platform

### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 

```
$ wechaty run doctor
wechaty: command not found
```

### Expected behavior

重启时避免重复扫码

### Actual behavior

重启时仍需重复扫码

### Steps to reproduce the behavior (and fixes, if any)

run the [**The World’s Shortest ChatBot Code: 6 lines of JavaScript**](http://chatie.io/wechaty/#wechatyinstance) with the changes outlined [here](https://blog.chatie.io/developer/2017/03/20/added-hot-reload-for-bots.html), i.e.:

> profile(OPTIONAL): profile name. if a profile name is provided, wechaty will save login status to it, and automatically restored on next time of wechaty start(restart).
> can be set by environment variable: WECHATY_PROFILE
> 也就是说设置一个profile就可以记住登录态，避免重启时的重复扫码动作。 扫码问题可以得到解决

```shell
$ docker run -it --rm --volume="$(pwd)":/bot zixia/wechaty bot1.ts
```

After it terminated (because of `timeout` and `memory leak` etc, e.g., https://github.com/Chatie/wechaty/issues/1059), restart it again using the same command as above.

**Comment by lijiarui** [comment]
Try `Wechaty.instance({profile: 'yourname'})` and then you can `yourname.wechaty.json`, it can remeber your session.

**Comment by forconz** [comment]
@lijiarui 我找到了 demo.wechaty.json，这个json文件是wechaty源代码里头的一个示例。这个json文件如何生成？ 是 Wechaty.instance({profile: 'demo'}) 自动生成的吗？

{"cookies":[{"name":"webwxuvid","value":"fd1746ce66fedd260915ca235a965e60f5d5413d559263d19eb3044a951b7a461498003ef4e858ed82f1ad36fb74e6d5","domain":".wx2.qq.com","path":"/","expires":1831548906,"size":105,"httpOnly":false,"secure":true,"session":false},{"name":"login_frequency","value":"0","domain":"wx2.qq.com","path":"/","expires":1516710164,"size":16,"httpOnly":false,"secure":true,"session":false},{"name":"last_wxuin","value":"3345489269","domain":"wx2.qq.com","path":"/","expires":1516710161,"size":20,"httpOnly":false,"secure":true,"session":false},{"name":"wxloadtime","value":"1516537362","domain":".wx2.qq.com","path":"/","expires":1516580562,"size":20,"httpOnly":false,"secure":true,"session":false},{"name":"wxuin","value":"3345489269","domain":".wx2.qq.com","path":"/","expires":1516580562,"size":15,"httpOnly":false,"secure":true,"session":false},{"name":"wxsid","value":"lx+eBV49nU5A+/GJ","domain":".wx2.qq.com","path":"/","expires":1516580562,"size":21,"httpOnly":false,"secure":true,"session":false},{"name":"webwx_data_ticket","value":"gScLiyW3CmOxzKAfBSnttfQT","domain":".qq.com","path":"/","expires":1516580562,"size":41,"httpOnly":false,"secure":true,"session":false},{"name":"mm_lang","value":"zh_CN","domain":".wx2.qq.com","path":"/","expires":1516586826,"size":12,"httpOnly":false,"secure":false,"session":false},{"name":"webwx_auth_ticket","value":"CIsBEIe3xZsFGoABH7CzRS10II2xm9PiqyiXHB8rz0btLATboKHyxJbNI7AidZerYsYANuy/zpu9VMYJbQ5nTopZrZGi7i0AX6znjJONmodNOIkcT6rfRXwPl5z+d8vSLsiPBRSQQopzu/gBTkr6SYvhGWgb5iauiIk/qD9KmF8FVhrXXuZndtWukis=","domain":".wx2.qq.com","path":"/","expires":1831897362,"size":205,"httpOnly":false,"secure":true,"session":false},{"name":"MM_WX_NOTIFY_STATE","value":"1","domain":"wx2.qq.com","path":"/","expires":0,"size":19,"httpOnly":false,"secure":false,"session":true},{"name":"MM_WX_SOUND_STATE","value":"1","domain":"wx2.qq.com","path":"/","expires":0,"size":18,"httpOnly":false,"secure":false,"session":true}]}

**Comment by lijiarui** [comment]
yes,  it can save session data, then you can avoid scan qrcode again within a period of time.

**Comment by suntong** [comment]
> Try `Wechaty.instance({profile: 'yourname'})` and then you can find `yourname.wechaty.json`,

Yeah, that's what I did, and I did find that file. 

> then you can avoid scan qrcode again _within a period of time_

Ah, that explain it. I might have tried too late. I'll try again and post back.

**Comment by suntong** [comment]
closing it for now, as I remember it's working (can't verify now).

**Comment by zixia** [comment]
Glad to hear that!

**Comment by WClouds** [comment]
> then you can avoid scan qrcode again within a period of time

How long can I avoid scan qrcode by yourname.wechaty.json?
