### ISSUE TITLE
How to identify those messages that are @me?

### ISSUE THREAD

**Issue by suntong** [Chatie/wechaty#1067]
Just a simple noob question,

How to identify those messages that are @me (sent directly to me in a room)?

thx

**Comment by zixia** [comment]
```
const contactList = message.mentioned()
const mentionedMe = contactList.some(contact => contact.self())
console.log(mentionedMe)
```

See: 
1. http://chatie.io/wechaty/#Message+self
1. http://chatie.io/wechaty/#Message+mentioned

**Comment by suntong** [comment]
Thanks @zixia! closing now, until if I have more questions.

**Comment by suntong** [comment]
This will work even I have different (alias) names in different rooms?

**Comment by zixia** [comment]
It should work when you have different alias names in different rooms.

If it does not work as expected, please report it as a bug by file a new issue.
