### ISSUE TITLE
建议新增发送时间间隔控制参数，避免短时间内频繁发消息

### ISSUE THREAD

**Issue by kainy** [Chatie/wechaty#1070]
### Provide Your Network Information

1. Out China
1. buyvm

### Expected behavior

判断调用 message。say（）时间间隔过短时，停止调用。

### Actual behavior

在用于自动答复时，接收到某些系统消息活着公众号也提供自动答复，就会不断产生对话，导致资源消耗。

**Comment by zixia** [comment]
Thanks for the suggestions.

This issue is duplicated with #596 , PR is welcome.
