### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by DITTOluxiaofei** [Chatie/wechaty#1076]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?

### Full Output Logs

```shell
$ WECHATY_LOG=silly npm run ts-node mybot.ts

# or 

$ WECHATY_LOG=silly node dist/mybot.js
```

<details>
<summary>
Show Logs
</summary>
### Paste the full output logs here with `WECHATY_LOG=silly` set 

```shell
# PASTE FULL LOG OUTPUT AT HERE:



```
</details>

**Comment by lijiarui** [comment]
I thought this is created by mistake...
