### ISSUE TITLE
关于MsgType 的介绍文档404了

### ISSUE THREAD

**Issue by kainy** [Chatie/wechaty#1079]
http://chatie.io/wechaty/MsgType

文档里面的链接，404 了。

**Comment by lijiarui** [comment]
Could you tell me where did you find this url?  I cannot find a doc link to introduce MsgType
Also I should look like this `http://chatie.io/wechaty/#Message`, you miss `#` here.

**Comment by zixia** [comment]
![image](https://user-images.githubusercontent.com/1361891/35527995-6ce3f374-0567-11e8-8d14-bdf8db212b8e.png)

**Comment by zixia** [comment]
@kainy Thank you very much for reporting this bug!
