### ISSUE TITLE
Third options to run wechaty

### ISSUE THREAD

**Issue by suntong** [Chatie/wechaty#1085]
Still another noob question, 

I know for the normal wechaty end user, 

> We have _two_ options to run wechaty

However, as a wechaty module developer, I'd like to stick to the bleeding edge, and would like to know how to run wechaty from git code. 

I know it must be a piece of cake for people who know nodejs, so please bear with me for such noob questions for now. 

thanks

**Comment by suntong** [comment]
hmm... found this, 
https://stackoverflow.com/questions/17509669/how-to-install-an-npm-package-from-github-directly
and trying...

**Comment by suntong** [comment]
that's not working, trying 

https://github.com/Chatie/wechaty/issues/48

**Comment by suntong** [comment]
way too complicated than the two official methods to run wechaty. 

give up and go back to docker.

**Comment by suntong** [comment]
hmm..., 

Going back to docker IS simple to do, however, each time I update, I need to pull in ~1.2G of data -- _not practical_.

So let me leave it open...

**Comment by zixia** [comment]
@suntong I really like the way that you practice in the past days.

So please feel free to let me know your questions by file issues - I'd like to help when I have time.

Happy hacking!

**Comment by suntong** [comment]
No need the third options to get wechaty from git, `npm install` takes care of it nicely. Such knowledge is a piece of cake for people who know nodejs, but for me of such noob, I learnt it the hard way, :-(.

**Comment by zixia** [comment]
Yeah, buddy, learn hard and hack deep. :)
