### ISSUE TITLE
wechaty full API Doc

### ISSUE THREAD

**Issue by suntong** [Chatie/wechaty#1088]
Hi, 

I've been to http://chatie.io/wechaty/, but wasn't able to find the API for the exported `config` & `log` of wechaty. 

Can we have the API Doc for them as well please? Thx.

**Comment by lijiarui** [comment]
wechaty log in see this repo: [brolog](github.com/zixia/brolog), it has some doc.

What do you mean by `config` part of wechaty？

**Comment by zixia** [comment]
Brolog is a solo npm module: https://www.npmjs.com/package/brolog

[config](https://github.com/Chatie/wechaty/blob/master/src/config.ts) is an internal module of Wechaty which should not be used by the end user.

**Comment by suntong** [comment]
gotya. thx!
