### ISSUE TITLE
want help,how can i get the info of WeChat small program(小程序)?

### ISSUE THREAD

**Issue by sjzhangqiang** [Chatie/wechaty#1090]
in latest project, i want to get the info of WeChat small program,bug wechaty always print '收到一条网页版微信暂不支持的消息类型，请在手机上查看'
who can help me ?

**Comment by sjzhangqiang** [comment]
unsuppoted message type，can i modify the wechaty to receive the message info of WeChat small program

**Comment by sjzhangqiang** [comment]
is this tool developed by foreigners?so why English, it's hard to me

**Comment by lijiarui** [comment]
Because for web wechat, when you get the info of Wechat small program, you get the info is  '收到一条网页版微信暂不支持的消息类型，请在手机上查看'

Wechaty is based on web wechat at this period, this is not a bug.
