### ISSUE TITLE
Creating group problem

### ISSUE THREAD

**Issue by spt-shwetech** [Chatie/wechaty#1091]
Docker Command
 sudo docker run -ti --rm --volume="$(pwd)":/bot zixia/wechaty robot/test.ts

When i create the new group including three members, i found the following errors. What should i do ? 
Piece of Code
```
if(/create/.test(content)){
const helperContactA = await to(Contact.find({ name: 'Lamper' }))  // change 'lijiarui' to any contact in your wechat
            const helperContactB = await to(Contact.find({ name: 'Harsat' }))  // change 'juxiaomi' to any contact in your wechat
            // const contactList = []
            var contactList = new Array(); 
            contactList.push(contact)
            contactList.push(helperContactA)
            contactList.push(helperContactB)
            const room = await to(Room.create(contactList, 'testy'))
  }
function to(promise) {  
    return promise.then(data => {
       return data;
    })
    .catch(err => [err]);
 }
```

Error
`10:46:57 ERR PuppetWebBridge roomCreate(@1885c017ab4407c88063a6ed6b56dfdc58e3c743c557b584f26b26f8d30c74d1,@8d4ca0486d21f670ec57da8c20e10e1f1d9e6fd9e84efb3b53f7f74e8a6dbf5e,@13eeb76451548b6a804bc85e800f62e33c77aaf3056034d739b2c999598f84d0) exception: chatroomFactory.create() got empty r.ChatRoomName
10:46:57 WARN PuppetWeb roomCreate(@1885c017ab4407c88063a6ed6b56dfdc58e3c743c557b584f26b26f8d30c74d1,@8d4ca0486d21f670ec57da8c20e10e1f1d9e6fd9e84efb3b53f7f74e8a6dbf5e,@13eeb76451548b6a804bc85e800f62e33c77aaf3056034d739b2c999598f84d0, testy) rejected: chatroomFactory.create() got empty r.ChatRoomName
10:46:57 ERR Room create() exception: Error: chatroomFactory.create() got empty r.ChatRoomName
    at <anonymous>:691:35
    at c (https://res.wx.qq.com/a/wx_fed/webwx/res/static/vendor/vendor_fe62088.js:11:20357)
    at https://res.wx.qq.com/a/wx_fed/webwx/res/static/vendor/vendor_fe62088.js:11:21014
    at c.$eval (https://res.wx.qq.com/a/wx_fed/webwx/res/static/vendor/vendor_fe62088.js:11:26264)
    at c.$digest (https://res.wx.qq.com/a/wx_fed/webwx/res/static/vendor/vendor_fe62088.js:11:24789)
    at c.$apply (https://res.wx.qq.com/a/wx_fed/webwx/res/static/vendor/vendor_fe62088.js:11:26583)
    at l (https://res.wx.qq.com/a/wx_fed/webwx/res/static/vendor/vendor_fe62088.js:11:4916)
    at m (https://res.wx.qq.com/a/wx_fed/webwx/res/static/vendor/vendor_fe62088.js:11:7332)
    at XMLHttpRequest.C.onreadystatechange (https://res.wx.qq.com/a/wx_fed/webwx/res/static/vendor/vendor_fe62088.js:11:7908)
[ { stack: 'Error: chatroomFactory.create() got empty r.ChatRoomName\n    at <anonymous>:691:35\n    at c (https://res.wx.qq.com/a/wx_fed/webwx/res/static/vendor/vendor_fe62088.js:11:20357)\n    at https://res.wx.qq.com/a/wx_fed/webwx/res/static/vendor/vendor_fe62088.js:11:21014\n    at c.$eval (https://res.wx.qq.com/a/wx_fed/webwx/res/static/vendor/vendor_fe62088.js:11:26264)\n    at c.$digest (https://res.wx.qq.com/a/wx_fed/webwx/res/static/vendor/vendor_fe62088.js:11:24789)\n    at c.$apply (https://res.wx.qq.com/a/wx_fed/webwx/res/static/vendor/vendor_fe62088.js:11:26583)\n    at l (https://res.wx.qq.com/a/wx_fed/webwx/res/static/vendor/vendor_fe62088.js:11:4916)\n    at m (https://res.wx.qq.com/a/wx_fed/webwx/res/static/vendor/vendor_fe62088.js:11:7332)\n    at XMLHttpRequest.C.onreadystatechange (https://res.wx.qq.com/a/wx_fed/webwx/res/static/vendor/vendor_fe62088.js:11:7908)',
    message: 'chatroomFactory.create() got empty r.ChatRoomName' } ]
`

**Comment by milkdeliver** [comment]
Issue still here? Do you have any progress on it?

**Comment by spt-shwetech** [comment]
I have no idea. Web Wechat doesn't allow  group creating function. I think it have been terminated by wechat team. I tired  with manual creating group that have also limitation.

**Comment by milkdeliver** [comment]
I dig into the web wechat and it allows to grouping creating. I found the issue is the error response message after creating group.

**Comment by spt-shwetech** [comment]
I didn't find group creating button at web wechat . When i login with new wechat account, i got error that new sim card doesn't support web wechat login.

**Comment by milkdeliver** [comment]
First question,new account can't use web wechat. Please login with old one.

**Comment by spt-shwetech** [comment]
thank

**Comment by zixia** [comment]
Close this issue due to inactive for more than 60 days.
