### ISSUE TITLE
Feature request: sending file with a stream (creating media message with a stream)

### ISSUE THREAD

**Issue by baybal** [Chatie/wechaty#1092]
Current method for sending multimedia messages requires the content to be a file on the disk. I want it to be possible to send a multimedia message by passing it as a stream.

If you have 100 users who are sending 100mb files simultaneously, you have to buffer and save to fs all of that prior to sending it to weixin users. That is both inconvenient and hugely wasteful to resources if the media you are sending already comes as a stream.

During our conversation on 6/2/2018, Huan mentioned that in that case it might be impossible to guess the file mime and filename. I suggest following: in case if the stream object does not contain the common `options` properties like `filename`, `contentType`, and `knownLenght`, you can tell users to set them manually, or add additional options that will be read during MediaMessage creation.

**Comment by zixia** [comment]
Hello @baybal,

This feature is supported from Wechaty v0.15.57 or above versions.

You can test this by `npm install wechaty@next` to opt-in the development branch NPM realease.

Code example:
https://github.com/Chatie/wechaty/blob/699b3ac7fa8988507f1d4c3ad3e4ef055a2a3205/examples/ding-dong-bot.ts#L101-L111

WARNING: 

You should wait for the v0.16 if you want to use Wechaty in a production environment.

The v0.15 have many breaking changes from v0.14. Please make sure you have read the [CHANGELOG](https://github.com/Chatie/wechaty/blob/master/CHANGELOG.md) and be prepared to say hello to the bugs.

### See Also

* WIP WARNING: master branch v0.15 is in heavy development! #1200
