### ISSUE TITLE
hot-reload-bot adding hot-reloading config

### ISSUE THREAD

**Issue by suntong** [Chatie/wechaty#1100]
The [hot-reload-bot demo code](https://github.com/Chatie/wechaty/blob/master/example/hot-reload-bot/index.js) only hot-reload event handling scripts, however, most event handling will need some kind of configuration, so it is nice to hot-reload configurations as well. 

Do you already have some code exist to handle that @Gcaufy? Would you care to update the demo if you do please? 

Otherwise, I'll see if I can do something, _if it is OK_, @Gcaufy, @zixia. But mind you, I've never written any Javascript programs before.

**Comment by zixia** [comment]
Thanks for your idea.

PR is welcome. :)

**Comment by suntong** [comment]
Ok, I'll look into it, since @Gcaufy don't have the extra bandwidth. 

When asking the question, I was thinking to send in PR for the hot-reload-bot demo code, but now, after thinking it over these period, I'm planning to submit a different demo instead, It's is still based on @Gcaufy's hot-reload-bot demo, but will be much more to it, so that's the main reason. What will be included in the new demo will be a turn key solution of getting started with serious wechaty customization blue-print. 

- Pure ES6 code, no Typescript, as per @Gcaufy's existing code
- All even handling, as per @Gcaufy's existing code
- Hot-reload the even handling code, as per @Gcaufy's existing code
- Hot-reload configurations as well
- Auto-save all media files, i.e., incorporate `media-file-bot.ts` into this getting started demo
- Graceful exit on SIGINT/SIGTERM, i.e., to write key info into file, on receiving killing signals (e.g., SIGINT (2), SIGTERM(3)), before termination, so as to do a "graceful shutdown". 

All in all, it's be a true solution for people to get started using wechaty, a one-stop demo for people to get an easy start.

**Comment by suntong** [comment]
oh, on seeing the issues in 

- https://github.com/Chatie/wechaty/pull/935, and 
- https://github.com/Chatie/wechaty/issues/1108

I realize that I'm not anywhere near the position to provide such demo...

**Comment by suntong** [comment]
OK. work started, ref: https://github.com/suntong/wechaty/commits/m1
which will eventually be merged back (after I'm done)...
