### ISSUE TITLE
Regenerate docs/index.md by run `npm run doc`

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#1105]
But the diff seems very large, please make sure there have no any problems with it.

**Comment by zixia** [comment]
The latest version of Wechaty today is 0.13.70, not 0.13.50.

Sorry, mission canceled.

**Comment by lijiarui** [comment]
version 0.13.70 
```
# Wechaty v0.13.72 Documentation
* https://blog.chatie.io
```

version 0.13.50
```
# Wechaty v0.13.50 Documentation
```
