### ISSUE TITLE
Translator to Spanish

### ISSUE THREAD

**Issue by UlisesTJ** [Chatie/wechaty#1107]
hello I would like to collaborate with your project by serving as a translator to Spanish which is my native language could translate the readme, contributing and any other text document as a license among others

**Comment by lijiarui** [comment]
Welcome to join us! We are so glad to hear this, pull request is welcome, and if you have any doc problem, feel free to contact with me.

**Comment by knz** [comment]
@UlisesTJ https://github.com/cockroachdb/cockroach/issues/23038#issuecomment-368220870

**Comment by UlisesTJ** [comment]
ok translate all the text documents as changelog, code_of_conduct, contributing and readme. I'm already working @lijiarui

**Comment by suntong** [comment]
@UlisesTJ have you made any progress this far? did you bumped into any problem at all?

**Comment by zixia** [comment]
Close this issue due to:

1. It's not active
1. It's not very necessary
