### ISSUE TITLE
emoji suggestion

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#1108]
I found [src/misc](https://github.com/Chatie/wechaty/blob/master/src/misc.ts) is trying to strip emoji, HTML and any misc things in a text message. 

I have 2 suggestions:

1.  I feel a bit confused about all emoji rules and this file rules, so I suggest to add some comment here, then if any other one gets some new emoji rules, we can add it here.

2. I suggest to add two functions:
* `message.stripEmoji(): void`: to strip emoji from the text message, then we can get a pure one.
* `message.emoji(): []`: return a list containing all emojis meaning in the text.

I found the following code in [src/misc](https://github.com/Chatie/wechaty/blob/master/src/misc.ts) seems trying to get emoji meaning but it cannot always succeed, also if there is some emotion, like gif in wechat, it doesn't work too. 
```ts
  public static digestEmoji(html?: string): string {
    if (!html) {
      return ''
    }
    return html
          .replace(/<img class="(\w*?emoji) (\w*?emoji[^"]+?)" text="(.*?)_web" src=[^>]+>/g,
                   '$3',
                 ) // <img class="emoji emoji1f4a4" text="[流汗]_web" src="/zh_CN/htmledition/v2/images/spacer.gif" />
          .replace(/<span class="(\w*?emoji) (\w*?emoji[^"]+?)"><\/span>/g,
                   '[$2]',
                 ) // '<span class="emoji emoji1f334"></span>'
  }
```

Well,  thinks more, even it should be a seperate npm module....

**Comment by suntong** [comment]
Oh, thanks for spotting that, I was just about to write my own code to get rid of them. 

When you say _"some emotion ... doesn't work"_, can you give several sample of those not working emotions please? 

Also, talking about cleaning up emoji, wouldn't `clean = Misc.digestEmoji(messy)` (or `Misc.stripEmoji`) be good enough? why proposing a different API? IMHO, I think we should have even fewer APIs, e.g., those people who prefer `Misc.stripEmoji` would most probably use `stripHtml` too, as it is hard to image someone want to get rid of only emoji while keeping other messy html stuff.
