### ISSUE TITLE
npm 安装的时候报错

### ISSUE THREAD

**Issue by ishwy** [Chatie/wechaty#1109]
C:\Users\shwy\Desktop\hongbao-bot-master (1)\hongbao-bot-master>npm config set registry https://registry.npm.taobao.org

C:\Users\shwy\Desktop\hongbao-bot-master (1)\hongbao-bot-master>npm install wechaty

> puppeteer@1.0.0 install C:\Users\shwy\Desktop\hongbao-bot-master (1)\hongbao-bot-master\node_modules\puppeteer
> node install.js

ERROR: Failed to download Chromium r526987! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: connect ETIMEDOUT 172.217.160.112:443
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1181:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '172.217.160.112',
  port: 443 }
npm WARN wechat-node@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.0.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\shwy\AppData\Roaming\npm-cache\_logs\2018-02-28T03_02_54_612Z-debug.log

C:\Users\shwy\Desktop\hongbao-bot-master (1)\hongbao-bot-master>

**Comment by zixia** [comment]
Duplicated with #867
