### ISSUE TITLE
emit error event when listen the page has been closed

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#1110]
I suggest the following log to emit an error event instead of a warning, because when this error, wechaty actually has dead.
```
08:47:37 WARN PuppetWebBridge proxyWechaty() noWechaty exception: Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
```

**Comment by zixia** [comment]
After v0.16 the Wechaty had been rewritten.

Please file a new issue at wechaty-puppet-puppeteer if you have any suggestion for the new version.
