### ISSUE TITLE
`TTL expired` error when login

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#1114]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)
China
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?
AWS

### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 

Starting Wechaty v0.13.32 with Node.js v8.9.1 ...

> wechaty@0.13.32 doctor /wechaty
> npm run check-node-version && ts-node bin/doctor

> wechaty@0.13.32 check-node-version /wechaty
> check-node-version --node ">= 7"

node: 8.9.1
npm: 5.5.1
yarn: not installed

  #### Wechaty Doctor

  1. Wechaty version: #git[9047ce9]
  2. Linux x64 version 3.16.0-4-amd64 memory 80/998 MB
  3. Docker: true
  4. Node version: v8.9.1
  5. Tcp IPC TEST: PASS

### Actual behavior

I'm not sure whether this is related to #970, when I scan qrcode, I got the following error
```shell
Error: TTL expired.
    at PuppetWeb.<anonymous> (/wechaty/dist/src/puppet-web/event.js:66:32)
    at Generator.next (<anonymous>)
    at /wechaty/dist/src/puppet-web/event.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/wechaty/dist/src/puppet-web/event.js:3:12)
    at PuppetWeb.onLogin (/wechaty/dist/src/puppet-web/event.js:61:12)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
error: @@@@@@@@@@@@ exit for {} @@@@@@@@@@@@
```

Even if I delete *.wechaty.json, it still cannot login

**Comment by lijiarui** [comment]
I'm not sure whether this is a forecast of wechat block...

After I change a server, I found my wechat is blocked......

**Comment by lijiarui** [comment]
I thought this is because I start 2 server and save their qrcode to one place and scan again and again....

But not that sure, so keep it open for a while... 

Now, I fix by change another server id...

**Comment by zixia** [comment]
Glad to hear that you had solved your problem.

I'll close this issue because I have no idea about what the `server id` is.

**Comment by TbhT** [comment]
Recently， I also met the issue， and the error stack as follows:

```javascript

Error: Error: onLogin() TTL expired.
--
  | at PuppetPuppeteer.puppet.on.error (/lib/node_modules/wechaty/dist/src/wechaty.js:436:44)
  | at emitOne (events.js:116:13)
  | at PuppetPuppeteer.emit (events.js:211:7)
  | at PuppetPuppeteer.emit (/lib/node_modules/wechaty-puppet/dist/src/puppet.js:171:22)
  | at PuppetPuppeteer.<anonymous> (/lib/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/event.js:75:18)
  | at Generator.next (<anonymous>)
  | at /lib/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/event.js:7:71
  | at new Promise (<anonymous>)
  | at __awaiter (/lib/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/event.js:3:12)
  | at PuppetPuppeteer.onLogin (/lib/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/event.js:70:12)
  | at ontimeout (timers.js:482:11)
  | at tryOnTimeout (timers.js:317:5)
  | at Timer.listOnTimeout (timers.js:277:5)

```

WeChat account was also blocked .
