### ISSUE TITLE
Q: All the media types

### ISSUE THREAD

**Issue by suntong** [Chatie/wechaty#1115]
In https://github.com/Chatie/wechaty/blob/master/example/media-file-bot.ts, there lists some media types:

```
  // if ( m.type() === MsgType.IMAGE
  //   || m.type() === MsgType.EMOTICON
  //   || m.type() === MsgType.VIDEO
  //   || m.type() === MsgType.VOICE
  //   || m.type() === MsgType.MICROVIDEO
  //   || m.type() === MsgType.APP
  //   || (m.type() === MsgType.TEXT && m.typeSub() === MsgType.LOCATION)  // LOCATION
```

This seems not the complete list of all the media types, e.g., the url-shared-as-a-message is not listed there. 

Where can I find the complete list of all the media types (and their explanations for e.g., EMOTICON)? Thx.

**Comment by lijiarui** [comment]
EMOTICON, do you mean emotion?

If it is, this type is MsgType.TEXT

Also, besides MsgTyps, there is AppMsgType, as follows
```ts
export enum AppMsgType {
  TEXT                     = 1,
  IMG                      = 2,
  AUDIO                    = 3,
  VIDEO                    = 4,
  URL                      = 5,
  ATTACH                   = 6,
  OPEN                     = 7,
  EMOJI                    = 8,
  VOICE_REMIND             = 9,
  SCAN_GOOD                = 10,
  GOOD                     = 13,
  EMOTION                  = 15,
  CARD_TICKET              = 16,
  REALTIME_SHARE_LOCATION  = 17,
  TRANSFERS                = 2e3,
  RED_ENVELOPES            = 2001,
  READER_TYPE              = 100001,
}
```

see more in [src/puppet-web/schema.ts](https://github.com/Chatie/wechaty/blob/master/src/puppet-web/schema.ts)

**Comment by suntong** [comment]
thanks a lot @lijiarui!

**Comment by suntong** [comment]
Oh, 

> _besides MsgTyps, there is AppMsgType_

So what's difference between 

`MsgType.TEXT` and `AppMsgType.TEXT`, and all else that are the same between them, e.g., `IMG`, `VIDEO`, etc?

**Comment by zixia** [comment]
Short answer: `AppMsgType` is a sub-type of `MsgType.APP`

Long version: they are inherited from the web-wechat source code, which is designed by Tencent.
