### ISSUE TITLE
Cannot fire room-leave event

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#1121]
## WECHATY VERSION

> wechaty@0.13.72 doctor /Users/jiaruili/git/rui/wechaty
> npm run check-node-version && ts-node bin/doctor

> wechaty@0.13.72 check-node-version /Users/jiaruili/git/rui/wechaty
> check-node-version --node ">= 8.5"

  #### Wechaty Doctor

  1. Wechaty version: #git[b5c0c14]
  2. Darwin x64 version 16.7.0 memory 456/16384 MB
  3. Docker: false
  4. Node version: v9.3.0
  5. Tcp IPC TEST: PASS

## Bug

related to #1116, room leave event cannot be fire for the same reason

But the log shows as follows, it is right with `firer.ts`, will dig in the future for this.
```
[美丽群]<美丽群>:{SYS}You removed "管理员" from the group chat
[美丽群]<美丽群>:{SYS}You removed "小桔建群助手" from the group chat
```

**Comment by zixia** [comment]
#1116 had been merged so could you please close this issue for now?

**Comment by lijiarui** [comment]
No, this still is a bug, because it cannot fire room leave event yet. #1116 now can fire room-join, I don't know why the message is same but cannot fire room-leave, so keep it open when I have time or anyone have time to fix room-leave event.

**Comment by Zhou-Bill** [comment]
this question has been solve？

**Comment by lijiarui** [comment]
nop, pr is welcome :)

**Comment by zixia** [comment]
Moved to <https://github.com/Chatie/wechaty-puppet-puppeteer/issues/32>
