### ISSUE TITLE
请教下怎么列出被删除好友或黑名单的列表，然后怎么批量删除他们？

### ISSUE THREAD

**Issue by callmesoul** [Chatie/wechaty#1128]
请教下怎么列出被删除好友或黑名单的列表，然后怎么批量删除他们？

**Comment by lijiarui** [comment]
If web wechat cannot do this, then wechaty cannot.

Because wechaty is based on web wechat.

**Comment by callmesoul** [comment]
ok,thx

**Comment by zixia** [comment]
It might be able to be done by `wechaty-puppet-padchat`

@callmesoul Could you please close this issue because your question had been answered?
