### ISSUE TITLE
 ERR Wechaty start() exception: Failed to launch chrome!

### ISSUE THREAD

**Issue by LiudaiC** [Chatie/wechaty#1144]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)

1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?
Qcloud
### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 

I don't use docker, I am deploying my Wechat mini program on my dev env.

### Expected behavior

No error log in console.

### Actual behavior

The console gives me the following message:

/data/release/node-weapp-demo/node_modules/puppeteer/.local-chromium/linux-543305/chrome-linux/chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory

### Steps to reproduce the behavior (and fixes, if any)

I add dependency of "wechaty" in my server package.json, then add the example code in one js file.
After that restart the app.
Then I debug the Qcloud.

### Full Output Logs

```shell
$ WECHATY_LOG=silly npm run ts-node mybot.ts

# or 

$ WECHATY_LOG=silly node dist/mybot.js
```

<details>
<summary>
Show Logs
</summary>
### Paste the full output logs here with `WECHATY_LOG=silly` set 

brolog.umd.js:191 23:07:39 ERR PuppetWebBridge init() exception: Error: Failed to launch chrome!
/data/release/node-weapp-demo/node_modules/puppeteer/.local-chromium/linux-543305/chrome-linux/chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

Brolog.printTextDefault @ brolog.umd.js:191
Brolog.log @ brolog.umd.js:182
Brolog.error @ brolog.umd.js:231
(anonymous) @ bridge.js:61
rejected @ bridge.js:5
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
rejected @ bridge.js:5
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
launch @ Launcher.js:160
_tickDomainCallback @ internal/process/next_tick.js:228
async function (async)
launch @ Launcher.js:61
launch @ Puppeteer.js:26
(anonymous) @ bridge.js:83
(anonymous) @ bridge.js:7
__awaiter @ bridge.js:3
initBrowser @ bridge.js:80
(anonymous) @ bridge.js:51
(anonymous) @ bridge.js:7
__awaiter @ bridge.js:3
init @ bridge.js:47
(anonymous) @ puppet-web.js:223
(anonymous) @ puppet-web.js:7
__awaiter @ puppet-web.js:3
initBridge @ puppet-web.js:200
(anonymous) @ puppet-web.js:61
(anonymous) @ puppet-web.js:7
__awaiter @ puppet-web.js:3
init @ puppet-web.js:55
(anonymous) @ wechaty.js:345
(anonymous) @ wechaty.js:7
__awaiter @ wechaty.js:3
initPuppet @ wechaty.js:312
(anonymous) @ wechaty.js:155
(anonymous) @ wechaty.js:7
__awaiter @ wechaty.js:3
start @ wechaty.js:139
(anonymous) @ weblogin.js:63
Module._compile @ module.js:569
Module._extensions..js @ module.js:580
Module.load @ module.js:503
tryModuleLoad @ module.js:466
Module._load @ module.js:458
Module.require @ module.js:513
require @ internal/module.js:11
files.forEach.file @ index.js:22
mapDir @ index.js:20
(anonymous) @ index.js:30
Module._compile @ module.js:569
Module._extensions..js @ module.js:580
Module.load @ module.js:503
tryModuleLoad @ module.js:466
Module._load @ module.js:458
Module.require @ module.js:513
require @ internal/module.js:11
(anonymous) @ index.js:7
Module._compile @ module.js:569
Module._extensions..js @ module.js:580
Module.load @ module.js:503
tryModuleLoad @ module.js:466
Module._load @ module.js:458
Module.require @ module.js:513
require @ internal/module.js:11
(anonymous) @ app.js:15
Module._compile @ module.js:566
Module._extensions..js @ module.js:580
Module.load @ module.js:503
tryModuleLoad @ module.js:466
Module._load @ module.js:458
Module.runMain @ module.js:605
startup @ bootstrap_node.js:158
(anonymous) @ bootstrap_node.js:575
brolog.umd.js:191 23:07:39 ERR PuppetWeb initBridge() exception: Failed to launch chrome!
/data/release/node-weapp-demo/node_modules/puppeteer/.local-chromium/linux-543305/chrome-linux/chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

Brolog.printTextDefault @ brolog.umd.js:191
Brolog.log @ brolog.umd.js:182
Brolog.error @ brolog.umd.js:231
(anonymous) @ puppet-web.js:226
rejected @ puppet-web.js:5
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
rejected @ bridge.js:5
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
rejected @ bridge.js:5
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
launch @ Launcher.js:160
_tickDomainCallback @ internal/process/next_tick.js:228
async function (async)
launch @ Launcher.js:61
launch @ Puppeteer.js:26
(anonymous) @ bridge.js:83
(anonymous) @ bridge.js:7
__awaiter @ bridge.js:3
initBrowser @ bridge.js:80
(anonymous) @ bridge.js:51
(anonymous) @ bridge.js:7
__awaiter @ bridge.js:3
init @ bridge.js:47
(anonymous) @ puppet-web.js:223
(anonymous) @ puppet-web.js:7
__awaiter @ puppet-web.js:3
initBridge @ puppet-web.js:200
(anonymous) @ puppet-web.js:61
(anonymous) @ puppet-web.js:7
__awaiter @ puppet-web.js:3
init @ puppet-web.js:55
(anonymous) @ wechaty.js:345
(anonymous) @ wechaty.js:7
__awaiter @ wechaty.js:3
initPuppet @ wechaty.js:312
(anonymous) @ wechaty.js:155
(anonymous) @ wechaty.js:7
__awaiter @ wechaty.js:3
start @ wechaty.js:139
(anonymous) @ weblogin.js:63
Module._compile @ module.js:569
Module._extensions..js @ module.js:580
Module.load @ module.js:503
tryModuleLoad @ module.js:466
Module._load @ module.js:458
Module.require @ module.js:513
require @ internal/module.js:11
files.forEach.file @ index.js:22
mapDir @ index.js:20
(anonymous) @ index.js:30
Module._compile @ module.js:569
Module._extensions..js @ module.js:580
Module.load @ module.js:503
tryModuleLoad @ module.js:466
Module._load @ module.js:458
Module.require @ module.js:513
require @ internal/module.js:11
(anonymous) @ index.js:7
Module._compile @ module.js:569
Module._extensions..js @ module.js:580
Module.load @ module.js:503
tryModuleLoad @ module.js:466
Module._load @ module.js:458
Module.require @ module.js:513
require @ internal/module.js:11
(anonymous) @ app.js:15
Module._compile @ module.js:566
Module._extensions..js @ module.js:580
Module.load @ module.js:503
tryModuleLoad @ module.js:466
Module._load @ module.js:458
Module.runMain @ module.js:605
startup @ bootstrap_node.js:158
(anonymous) @ bootstrap_node.js:575
brolog.umd.js:196 23:07:39 WARN PuppetWebBridge quit() page.close() exception: TypeError: Cannot read property 'close' of undefined
Brolog.printTextDefault @ brolog.umd.js:196
Brolog.log @ brolog.umd.js:182
Brolog.warn @ brolog.umd.js:253
(anonymous) @ bridge.js:240
(anonymous) @ bridge.js:7
__awaiter @ bridge.js:3
quit @ bridge.js:232
(anonymous) @ puppet-web.js:227
rejected @ puppet-web.js:5
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
rejected @ bridge.js:5
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
rejected @ bridge.js:5
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
launch @ Launcher.js:160
_tickDomainCallback @ internal/process/next_tick.js:228
async function (async)
launch @ Launcher.js:61
launch @ Puppeteer.js:26
(anonymous) @ bridge.js:83
(anonymous) @ bridge.js:7
__awaiter @ bridge.js:3
initBrowser @ bridge.js:80
(anonymous) @ bridge.js:51
(anonymous) @ bridge.js:7
__awaiter @ bridge.js:3
init @ bridge.js:47
(anonymous) @ puppet-web.js:223
(anonymous) @ puppet-web.js:7
__awaiter @ puppet-web.js:3
initBridge @ puppet-web.js:200
(anonymous) @ puppet-web.js:61
(anonymous) @ puppet-web.js:7
__awaiter @ puppet-web.js:3
init @ puppet-web.js:55
(anonymous) @ wechaty.js:345
(anonymous) @ wechaty.js:7
__awaiter @ wechaty.js:3
initPuppet @ wechaty.js:312
(anonymous) @ wechaty.js:155
(anonymous) @ wechaty.js:7
__awaiter @ wechaty.js:3
start @ wechaty.js:139
(anonymous) @ weblogin.js:63
Module._compile @ module.js:569
Module._extensions..js @ module.js:580
Module.load @ module.js:503
tryModuleLoad @ module.js:466
Module._load @ module.js:458
Module.require @ module.js:513
require @ internal/module.js:11
files.forEach.file @ index.js:22
mapDir @ index.js:20
(anonymous) @ index.js:30
Module._compile @ module.js:569
Module._extensions..js @ module.js:580
Module.load @ module.js:503
tryModuleLoad @ module.js:466
Module._load @ module.js:458
Module.require @ module.js:513
require @ internal/module.js:11
(anonymous) @ index.js:7
Module._compile @ module.js:569
Module._extensions..js @ module.js:580
Module.load @ module.js:503
tryModuleLoad @ module.js:466
Module._load @ module.js:458
Module.require @ module.js:513
require @ internal/module.js:11
(anonymous) @ app.js:15
Module._compile @ module.js:566
Module._extensions..js @ module.js:580
Module.load @ module.js:503
tryModuleLoad @ module.js:466
Module._load @ module.js:458
Module.runMain @ module.js:605
startup @ bootstrap_node.js:158
(anonymous) @ bootstrap_node.js:575
brolog.umd.js:196 23:07:39 WARN PuppetWebBridge quit() browser.close() exception: TypeError: Cannot read property 'close' of undefined
Brolog.printTextDefault @ brolog.umd.js:196
Brolog.log @ brolog.umd.js:182
Brolog.warn @ brolog.umd.js:253
(anonymous) @ bridge.js:247
(anonymous) @ bridge.js:7
__awaiter @ bridge.js:3
quit @ bridge.js:232
(anonymous) @ puppet-web.js:227
rejected @ puppet-web.js:5
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
rejected @ bridge.js:5
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
rejected @ bridge.js:5
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
launch @ Launcher.js:160
_tickDomainCallback @ internal/process/next_tick.js:228
async function (async)
launch @ Launcher.js:61
launch @ Puppeteer.js:26
(anonymous) @ bridge.js:83
(anonymous) @ bridge.js:7
__awaiter @ bridge.js:3
initBrowser @ bridge.js:80
(anonymous) @ bridge.js:51
(anonymous) @ bridge.js:7
__awaiter @ bridge.js:3
init @ bridge.js:47
(anonymous) @ puppet-web.js:223
(anonymous) @ puppet-web.js:7
__awaiter @ puppet-web.js:3
initBridge @ puppet-web.js:200
(anonymous) @ puppet-web.js:61
(anonymous) @ puppet-web.js:7
__awaiter @ puppet-web.js:3
init @ puppet-web.js:55
(anonymous) @ wechaty.js:345
(anonymous) @ wechaty.js:7
__awaiter @ wechaty.js:3
initPuppet @ wechaty.js:312
(anonymous) @ wechaty.js:155
(anonymous) @ wechaty.js:7
__awaiter @ wechaty.js:3
start @ wechaty.js:139
(anonymous) @ weblogin.js:63
Module._compile @ module.js:569
Module._extensions..js @ module.js:580
Module.load @ module.js:503
tryModuleLoad @ module.js:466
Module._load @ module.js:458
Module.require @ module.js:513
require @ internal/module.js:11
files.forEach.file @ index.js:22
mapDir @ index.js:20
(anonymous) @ index.js:30
Module._compile @ module.js:569
Module._extensions..js @ module.js:580
Module.load @ module.js:503
tryModuleLoad @ module.js:466
Module._load @ module.js:458
Module.require @ module.js:513
require @ internal/module.js:11
(anonymous) @ index.js:7
Module._compile @ module.js:569
Module._extensions..js @ module.js:580
Module.load @ module.js:503
tryModuleLoad @ module.js:466
Module._load @ module.js:458
Module.require @ module.js:513
require @ internal/module.js:11
(anonymous) @ app.js:15
Module._compile @ module.js:566
Module._extensions..js @ module.js:580
Module.load @ module.js:503
tryModuleLoad @ module.js:466
Module._load @ module.js:458
Module.runMain @ module.js:605
startup @ bootstrap_node.js:158
(anonymous) @ bootstrap_node.js:575
brolog.umd.js:191 23:07:39 ERR PuppetWeb init() exception: Error: Failed to launch chrome!
/data/release/node-weapp-demo/node_modules/puppeteer/.local-chromium/linux-543305/chrome-linux/chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

Brolog.printTextDefault @ brolog.umd.js:191
Brolog.log @ brolog.umd.js:182
Brolog.error @ brolog.umd.js:231
(anonymous) @ puppet-web.js:83
rejected @ puppet-web.js:5
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
fulfilled @ puppet-web.js:4
_tickDomainCallback @ internal/process/next_tick.js:228
Promise resolved (async)
_tickDomainCallback @ internal/process/next_tick.js:228
Promise resolved (async)
_tickDomainCallback @ internal/process/next_tick.js:228
Promise resolved (async)
step @ bridge.js:6
(anonymous) @ bridge.js:7
__awaiter @ bridge.js:3
quit @ bridge.js:232
(anonymous) @ puppet-web.js:227
rejected @ puppet-web.js:5
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
rejected @ bridge.js:5
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
rejected @ bridge.js:5
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
launch @ Launcher.js:160
_tickDomainCallback @ internal/process/next_tick.js:228
async function (async)
launch @ Launcher.js:61
launch @ Puppeteer.js:26
(anonymous) @ bridge.js:83
(anonymous) @ bridge.js:7
__awaiter @ bridge.js:3
initBrowser @ bridge.js:80
(anonymous) @ bridge.js:51
(anonymous) @ bridge.js:7
__awaiter @ bridge.js:3
init @ bridge.js:47
(anonymous) @ puppet-web.js:223
(anonymous) @ puppet-web.js:7
__awaiter @ puppet-web.js:3
initBridge @ puppet-web.js:200
(anonymous) @ puppet-web.js:61
(anonymous) @ puppet-web.js:7
__awaiter @ puppet-web.js:3
init @ puppet-web.js:55
(anonymous) @ wechaty.js:345
(anonymous) @ wechaty.js:7
__awaiter @ wechaty.js:3
initPuppet @ wechaty.js:312
(anonymous) @ wechaty.js:155
(anonymous) @ wechaty.js:7
__awaiter @ wechaty.js:3
start @ wechaty.js:139
(anonymous) @ weblogin.js:63
Module._compile @ module.js:569
Module._extensions..js @ module.js:580
Module.load @ module.js:503
tryModuleLoad @ module.js:466
Module._load @ module.js:458
Module.require @ module.js:513
require @ internal/module.js:11
files.forEach.file @ index.js:22
mapDir @ index.js:20
(anonymous) @ index.js:30
Module._compile @ module.js:569
Module._extensions..js @ module.js:580
Module.load @ module.js:503
tryModuleLoad @ module.js:466
Module._load @ module.js:458
Module.require @ module.js:513
require @ internal/module.js:11
(anonymous) @ index.js:7
Module._compile @ module.js:569
Module._extensions..js @ module.js:580
Module.load @ module.js:503
tryModuleLoad @ module.js:466
Module._load @ module.js:458
Module.require @ module.js:513
require @ internal/module.js:11
(anonymous) @ app.js:15
Module._compile @ module.js:566
Module._extensions..js @ module.js:580
Module.load @ module.js:503
tryModuleLoad @ module.js:466
Module._load @ module.js:458
Module.runMain @ module.js:605
startup @ bootstrap_node.js:158
(anonymous) @ bootstrap_node.js:575
brolog.umd.js:191 23:07:39 ERR Wechaty start() exception: Failed to launch chrome!
/data/release/node-weapp-demo/node_modules/puppeteer/.local-chromium/linux-543305/chrome-linux/chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

Brolog.printTextDefault @ brolog.umd.js:191
Brolog.log @ brolog.umd.js:182
Brolog.error @ brolog.umd.js:231
(anonymous) @ wechaty.js:158
rejected @ wechaty.js:5
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
rejected @ wechaty.js:5
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
rejected @ puppet-web.js:5
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
fulfilled @ puppet-web.js:4
_tickDomainCallback @ internal/process/next_tick.js:228
Promise resolved (async)
_tickDomainCallback @ internal/process/next_tick.js:228
Promise resolved (async)
_tickDomainCallback @ internal/process/next_tick.js:228
Promise resolved (async)
step @ bridge.js:6
(anonymous) @ bridge.js:7
__awaiter @ bridge.js:3
quit @ bridge.js:232
(anonymous) @ puppet-web.js:227
rejected @ puppet-web.js:5
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
rejected @ bridge.js:5
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
rejected @ bridge.js:5
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
_tickDomainCallback @ internal/process/next_tick.js:228
Promise rejected (async)
launch @ Launcher.js:160
_tickDomainCallback @ internal/process/next_tick.js:228
async function (async)
launch @ Launcher.js:61
launch @ Puppeteer.js:26
(anonymous) @ bridge.js:83
(anonymous) @ bridge.js:7
__awaiter @ bridge.js:3
initBrowser @ bridge.js:80
(anonymous) @ bridge.js:51
(anonymous) @ bridge.js:7
__awaiter @ bridge.js:3
init @ bridge.js:47
(anonymous) @ puppet-web.js:223
(anonymous) @ puppet-web.js:7
__awaiter @ puppet-web.js:3
initBridge @ puppet-web.js:200
(anonymous) @ puppet-web.js:61
(anonymous) @ puppet-web.js:7
__awaiter @ puppet-web.js:3
init @ puppet-web.js:55
(anonymous) @ wechaty.js:345
(anonymous) @ wechaty.js:7
__awaiter @ wechaty.js:3
initPuppet @ wechaty.js:312
(anonymous) @ wechaty.js:155
(anonymous) @ wechaty.js:7
__awaiter @ wechaty.js:3
start @ wechaty.js:139
(anonymous) @ weblogin.js:63
Module._compile @ module.js:569
Module._extensions..js @ module.js:580
Module.load @ module.js:503
tryModuleLoad @ module.js:466
Module._load @ module.js:458
Module.require @ module.js:513
require @ internal/module.js:11
files.forEach.file @ index.js:22
mapDir @ index.js:20
(anonymous) @ index.js:30
Module._compile @ module.js:569
Module._extensions..js @ module.js:580
Module.load @ module.js:503
tryModuleLoad @ module.js:466
Module._load @ module.js:458
Module.require @ module.js:513
require @ internal/module.js:11
(anonymous) @ index.js:7
Module._compile @ module.js:569
Module._extensions..js @ module.js:580
Module.load @ module.js:503
tryModuleLoad @ module.js:466
Module._load @ module.js:458
Module.require @ module.js:513
require @ internal/module.js:11
(anonymous) @ app.js:15
Module._compile @ module.js:566
Module._extensions..js @ module.js:580
Module.load @ module.js:503
tryModuleLoad @ module.js:466
Module._load @ module.js:458
Module.runMain @ module.js:605
startup @ bootstrap_node.js:158
(anonymous) @ bootstrap_node.js:575
internal/process/warning.js:28 (node:5314) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to launch chrome!
/data/release/node-weapp-demo/node_modules/puppeteer/.local-chromium/linux-543305/chrome-linux/chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

writeOut @ internal/process/warning.js:28
output @ internal/process/warning.js:76
process.on @ internal/process/warning.js:107
emitOne @ events.js:115
emit @ events.js:210
(anonymous) @ internal/process/warning.js:81
_combinedTickCallback @ internal/process/next_tick.js:131
_tickDomainCallback @ internal/process/next_tick.js:218
internal/process/warning.js:28 (node:5314) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
writeOut @ internal/process/warning.js:28
output @ internal/process/warning.js:76
process.on @ internal/process/warning.js:107
emitOne @ events.js:115
emit @ events.js:210
(anonymous) @ internal/process/warning.js:81
_combinedTickCallback @ internal/process/next_tick.js:131
_tickDomainCallback @ internal/process/next_tick.js:218
```shell
# PASTE FULL LOG OUTPUT AT HERE:



```
</details>

**Comment by zixia** [comment]
Duplicated with #1152
