### ISSUE TITLE
Failed to download Chromium r543305

### ISSUE THREAD

**Issue by MozLee** [Chatie/wechaty#1145]
ERROR: Failed to download Chromium r543305! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: EACCES: permission denied, mkdir '/root/web/www/node_modules/puppeteer/.local-chromium'
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/root/web/www/node_modules/puppeteer/.local-chromium' }

**Comment by demobo-com** [comment]
Got stuck on the same problem. How did you fix this?

**Comment by demobo-com** [comment]
I am using this in US with AWS ec2 us-west-1 instance.

**Comment by huan** [comment]
So your issue is not related to this issue anymore.

I'd like to suggest you change your VPS from AWS to another cloud provider and try again.

**Comment by demobo-com** [comment]
{ [Error: EACCES: permission denied, mkdir '/web/carpedm/ec2/node_modules/wechaty/node_modules/puppeteer/.local-chromium']
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path:
   '/web/carpedm/ec2/node_modules/wechaty/node_modules/puppeteer/.local-chromium' }

This is the error I get.

sudo npm install wechaty-puppet-puppeteer@^0.14.1 --unsafe-perm=true --allow-root
This fixes it.

**Comment by huan** [comment]
Glad to hear that you had fixed it. It seems that you have a local file system permission issue.
