### ISSUE TITLE
cannot refresh room topic or contact name

### ISSUE THREAD

**Issue by fatshaw** [Chatie/wechaty#1157]
when a room topic is changed, but bot cannot get latest room topic.
I have already call await room.refresh() but room.topic() still return the old topic name.

and after i call room.refresh() and room.ready(), i call message.say to send message, it will output warning: 
15:24:31 WARN Room topic() room not ready

the same problem is for the contact instance.

so how can i get the latest room topic and contact name ？

**Comment by zixia** [comment]
Could you please try the latest master branch code (v0.15)? The latest code might fix this because it had been refactored a lot.

If this issue still exist, please provide a reproduce steps for your issue, thanks.

**Comment by zixia** [comment]
Please feel free to leave comments if you are still experiencing this issue with the latest code of master branch.
