### ISSUE TITLE
BREAKING CHANGE: v0.16 will remove `MediaMessage` class

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#1164]
From v0.16, `MediaMessage` will be deprecated.
From v0.18, `MediaMessage` will be removed.

Use `Message` instead.

### Migration Example

```diff
- bot.say(new MediaMessage('/image.png')
+ bot.say(new Message('/image.png')
```

**Comment by lizhongyi** [comment]
不行 ding-dong 那个二维码报错发布出去啊
![image](https://user-images.githubusercontent.com/3292807/39406789-09f5a9dc-4bef-11e8-86a7-c5ff38c886b7.png)

**Comment by zixia** [comment]
Yes, it can't.

Currently v0.15 is in heavy developing, please use it only if you do want to read the source code and help us to find out the bug(with a fix PR will be better).

You can use v0.14 instead and switch to v0.16 after it published.

See also #1158

**Comment by zixia** [comment]
See: #1200

**Comment by zixia** [comment]
Code Example can be found at #1092
