### ISSUE TITLE
Room-join event show  ERR PuppetWebFirer fireRoomJoin() not found(yet) error   (Bug)

### ISSUE THREAD

**Issue by Zhou-Bill** [Chatie/wechaty#1169]
Room-join event show  ERR PuppetWebFirer fireRoomJoin() not found(yet) error
how to solve it

**Comment by Zhou-Bill** [comment]
![image](https://user-images.githubusercontent.com/13554001/39341353-63ea0fc8-4a05-11e8-8560-7fa76916308d.png)

something wrong in this code ,when the  wechaty  do retryPromise function, the people not in room,see the code 1,  (!c) is true，to do the next one，so inviteeContactList.length is 0 # #

**Comment by originlan** [comment]
I also have this problem, then how to solve

**Comment by zixia** [comment]
After the v0.16 the Wechaty had been rewritten and the wechaty-puppet-puppeteer had been split to its new repo at https://github.com/Chatie/wechaty-puppet-puppeteer

This issue will be closed for now, and please feel free to file an issue at https://github.com/Chatie/wechaty-puppet-puppeteer/issues if there still have the problem with puppet-puppeteer.

Thank you very much.
