### ISSUE TITLE
Room-join event show ERR PuppetWebFirer fireRoomJoin() not found(yet)

### ISSUE THREAD

**Issue by originlan** [Chatie/wechaty#1171]
(Bug)Room-join event show log  ERR PuppetWebFirer fireRoomJoin() not found(yet),
.on('room-join', async function (room, inviteeList, inviter) ， inviteeList is empty.

**Comment by Zhou-Bill** [comment]
i have the same problem，i change the source code in firer.js to return 4 args, in the room-join event, i search the contact, so i  can get the source inviteeList, but it is a **string**

**Comment by originlan** [comment]
So,this can be temporarily resolved?@Zhou-Bill

**Comment by Zhou-Bill** [comment]
yes @originlan ，but i want to change it in the source code, but i dont't know how to do

**Comment by Zhou-Bill** [comment]
when they aren't friends , the room-join can't @ him , @originlan

**Comment by zixia** [comment]
Duplicated with #1169
