### ISSUE TITLE
PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000

### ISSUE THREAD

**Issue by atubo2012** [Chatie/wechaty#1173]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)
CHINA
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?
QCLOUD
### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 

DOCKER

### Expected behavior

keep running normally

### Actual behavior

hung after start up for 3hours

### Full Output Logs

```shell
$ WECHATY_LOG=silly npm run ts-node mybot.ts

# or 

$ WECHATY_LOG=silly node dist/mybot.js
```

<details>
<summary>
Show Logs
</summary>

### Paste the full output logs here with `WECHATY_LOG=silly` set 

```shell
# PASTE FULL LOG OUTPUT AT HERE:

17:27:00 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:heartbeat@browser, timeout:60000
17:31:40 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
17:33:49 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
17:35:55 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
17:37:59 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
17:40:04 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
17:42:10 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
17:44:13 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
17:46:18 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
(node:25) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 scan listeners added. Use emitter.setMaxListeners() to increase limit
(node:25) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 login listeners added. Use emitter.setMaxListeners() to increase limit
(node:25) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 logout listeners added. Use emitter.setMaxListeners() to increase limit
(node:25) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 heartbeat listeners added. Use emitter.setMaxListeners() to increase limit

```
</details>

**Comment by atubo2012** [comment]
Thanks reply so quickly, wechaty version is **v0.13.89**. @zixia 
Now I add process.setMaxListener(100) in my code,   hope that will keep running normally for longer .
May I set **WECHATY_LOG=silly** in host environment variable？

**Comment by zixia** [comment]
Thanks for telling me the version.

1. I believe `add process.setMaxListener(100)` is useless and could not help you prevent this happen. It only increases the max number of the memory leak before throw a warning.
1. Yes, you can set the `WECHATY_LOG=silly`, and it's good for debugging. Please post the full output in reply of #981 if you get any noticeable pieces of information.

I'll close this issue and let's move to #981
