### ISSUE TITLE
code example 'media-file-bot' not working

### ISSUE THREAD

**Issue by nujabse** [Chatie/wechaty#1183]
### Provide Your Network Information

China, local computer.

### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 
```
 #### Wechaty Doctor

  1. Wechaty version: #git[69762e1]
  2. Linux x64 version 4.14.34-1-MANJARO memory 5928/8537 MB
  3. Docker: false
  4. Node version: v9.11.1
  5. Tcp IPC TEST: PASS
```

### Expected behavior
run media-file-bot.ts code example to automatically download received picture files.

### Actual behavior
Only empty **jpg** files are generated without any content.

### Steps to reproduce the behavior (and fixes, if any)
```
ts-node examples/media-file-bot.ts
```

### Full Output Logs

```
PuppeteerContact<user> logined
start to readyStream()
finish readyStream() for  9109414383392334751..jpg  size:  0
RECV: Message#IMAGE<866797007780171292..jpg>
IMAGE local filename: 866797007780171292..jpg
start to readyStream()
RECV: Message#IMAGE<6883507788330090547..jpg>
IMAGE local filename: 6883507788330090547..jpg
start to readyStream()
finish readyStream() for  866797007780171292..jpg  size:  0
finish readyStream() for  6883507788330090547..jpg  size:  0
```

**Comment by zixia** [comment]
Please use v0.14 instead of master v0.15

**Comment by nujabse** [comment]
Problem fixed, thanks!

**Comment by zixia** [comment]
Glad to hear that, cheers!
