### ISSUE TITLE
room.say mention is not work

### ISSUE THREAD

**Issue by Zhou-Bill** [Chatie/wechaty#1185]
wechaty  v14.1

room.say(textOrMedia, [replyTo])  i set replyTo but it doesn't work, @someone it seem to  be a string ,so i doesn't  work

**Comment by Zhou-Bill** [comment]
i have test in web wechat , in browser user cann't @ someone,

**Comment by lijiarui** [comment]
see more here:  #362 #287 #512

**Comment by Zhou-Bill** [comment]
网页版是没有@人接口的， 你上面的解决方案是真的有用吗，我没看懂，即网页版发送信息@人无用，在房间@人无用

**Comment by lijiarui** [comment]
Yes, web wechat is a mock @, it cannot show the red @ tips in wechat.

**Comment by Zhou-Bill** [comment]
thanks

**Comment by zixia** [comment]
@Zhou-Bill could you please close this issue for now?
