### ISSUE TITLE
FriendRequest.send() not working

### ISSUE THREAD

**Issue by alamusi** [Chatie/wechaty#1186]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)
North America

1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?
AWS

### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 

> wechaty@0.14.0 doctor /wechaty
> npm run check-node-version && ts-node bin/doctor

> wechaty@0.14.0 check-node-version /wechaty
> check-node-version --node ">= 8.5"

  #### Wechaty Doctor

  1. Wechaty version: #git[32b624e]
  2. Linux x64 version 4.4.0-1054-aws memory 379/7478 MB
  3. Docker: true
  4. Node version: v9.11.1
  5. Tcp IPC TEST: PASS

### Expected behavior

the member in the room receives the friend request

### Actual behavior

nothing happened

### Steps to reproduce the behavior (and fixes, if any)

const wechaty = require('wechaty')

let request = new wechaty.FriendRequest()
request.send({
 id: '@xxxxx' // contact id of Contact object, or UserName of the rawObj 
}, 'hello')

// request.send() resolves to true, but nothing happened on the contact who should receive the friend request

**Comment by zixia** [comment]
The arg of `request.send()` should be a `Contact` instance instead of a `{id: '@xxx'}` Object.

Can you fix the arg type and try again?

**Comment by alamusi** [comment]
just to make sure that all the possibilities were exhausted. i also did load the whole contact object and tried with two different wechat accounts. 

it yield the same result. response is true but nothing happened on the contact side. thanks

```
  sendFriendRequest: function (contactId, message) {
    let fr = new wechaty.FriendRequest()
    let contact = wechaty.Contact.load(contactId)
    return fr.send(contact, message)
  }
```

**Comment by zixia** [comment]
Thanks for your update.

What's the exactly Wechaty version are you using?

I feel that the `wechaty@0.14.0` should not have the `wechaty.FriendRequest()` because it's only introduced from #518 #1159 after the version `0.15`

**Comment by zixia** [comment]
Oh yes, you can.

Then can you run the official friend-bot and to see if it work as expected?

https://github.com/Chatie/wechaty/blob/master/examples/friend-bot.ts

**Comment by alamusi** [comment]
@zixia i tested the friend-bot with accept() function and that works. my use case is to send() friend request and this doesn't seem to be in the example. thanks

**Comment by zixia** [comment]
If the friend-bot works, then we can believe the FriendRequest system communicates with the Browser API correct.

I will look it later when I have time. And I'd like to encourage you to test your account in the Browser(open a chrome) to confirm that you can add new Friend in a room in your Browser, and if so, you can check the WebWxApp API and see where's the problem, it will be the fast way to solve it.

**Comment by alamusi** [comment]
that's very true. that is why i am scratching my head and wonder if this has anything to do with my account or something else. when i sent a friend request on the web through web wechat interface, it didn't get through to the other account either. anyone could shade some light on this please?

PS: i traced all the way down to web wechat angular calls. from what i saw, the function verifyUserRequest() in wechaty-bro.js has identical behaviour with web wechat. should we consider this is a web wechat defect?!

**Comment by zixia** [comment]
Related to #1194

**Comment by zixia** [comment]
Close this issue due to longtime inactivity. Move to #1194 if anyone need future discussion.

**Comment by zixia** [comment]
@alamusi I'd like suggest you to have a look at #1296 , a iPad Puppet might help you resolve your issues better.
