### ISSUE TITLE
room-bot.ts error

### ISSUE THREAD

**Issue by w521aaa** [Chatie/wechaty#1199]
run the room-bot.ts
but error message 

WARN PuppeteerRoom memberList() not ready

**Comment by w521aaa** [comment]
``Message#TEXT<setting to manageDingRoom() after 3 seconds ... >
15:37:14 INFO Bot manageDingRoom()
15:37:15 INFO PuppeteerRoom ready()
    //log.info("==>isReady"+this.payload)
    //log.info("==>isReady"+!(this.payload && this.payload.memberList && this.payload.memberList.length))
    //log.info("==>isReady"+!!(this.payload && this.payload.memberList && this.payload.memberList.length))

15:37:15 INFO ==>isReady      undefined 
15:37:15 INFO ==>isReady      true 
15:37:15 INFO ==>isReady       false 
15:37:15 INFO PuppeteerRoom ready()
15:37:15 INFO ==>isReadyundefined 
15:37:15 INFO ==>isReadytrue 
15:37:15 INFO ==>isReadyfalse 
15:37:15 INFO PuppeteerRoom ready()
15:37:15 INFO ==>isReadyundefined 
15:37:15 INFO ==>isReadytrue 
15:37:15 INFO ==>isReadyfalse 
15:37:15 INFO -------->PuppeteerRoom true
15:37:15 INFO PuppeteerRoom ready()
15:37:15 INFO ==>isReadyundefined 
15:37:15 INFO ==>isReadytrue 
15:37:15 INFO ==>isReadyfalse 
15:37:15 INFO -------->PuppeteerRoom true
15:37:15 INFO PuppeteerRoom ready()
15:37:15 INFO ==>isReadyundefined 
15:37:15 INFO ==>isReadytrue 
15:37:15 INFO ==>isReadyfalse 
15:37:15 INFO -------->PuppeteerRoom true
15:37:15 INFO PuppeteerRoom ready()
15:37:15 INFO ==>isReadyundefined 
15:37:15 INFO ==>isReadytrue

**Comment by zixia** [comment]
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

**Comment by w521aaa** [comment]
i git clone the new version codes
then npm install . in the root path
then exec the command : npm run ts-node example/room-bot.ts
and i have created the room named test

so it will output the message like :

``Message#TEXT<setting to manageDingRoom() after 3 seconds ... >
15:37:14 INFO Bot manageDingRoom()
Room memberList() not ready
Room memberList() not ready
Room memberList() not ready
Room memberList() not ready
Room memberList() not ready
Room memberList() not ready
Room memberList() not ready
Room memberList() not ready
Room memberList() not ready




please focus on the function ready() and isReady() in the room.ts.
