### ISSUE TITLE
WIP WARNING: master branch v0.15 is in heavy development!

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#1200]
To the developers who'd love to check out the latest code from GitHub:

**Please do NOT check out v0.15** unless you'd like to play with the latest BUGs. Use v0.14 instead, it's the latest stable version.

### Source

You can check out the latest v0.14 code from GitHub using the following command:

```shell
$ git clone -b v0.14 git@github.com:Chatie/wechaty.git
```

### NPM

You can install the latest v0.14 module from NPM using the following command:

```shell
$ npm install wechaty@0.14
```

### Docker

You can pull the latest v0.14 image from Docker Hub using the following command:

```shell
$ docker pull zixia/wechaty:0.14
```

use the Docker Official Mirror in China:

```shell
$ docker pull registry.docker-cn.com/zixia/wechaty:0.14
```

### See Also

1. Create New Puppets for Wechaty #1167

**Comment by suntong** [comment]
Glad to see that you are pushing it forward again. Looking forward to the finished product. 

One question, would you anticipating _end user external_ API differences between v0.15  and v0.14? 
Also, any rough ETA when v0.15 might be out? In weeks or in months? Thx

**Comment by zixia** [comment]
@suntong Thanks for keeping watch the project.

1. There will be lots of API breaking changes in the upcoming v0.16. However, the good news is all of them will be very easy to understand and migration.
1. We can expect the v0.15 will be usable in May, and the v0.16 will be published in June.

**Comment by zixia** [comment]
The CI tunes green now.
