### ISSUE TITLE
What is the need to install the Chromedriver?

### ISSUE THREAD

**Issue by shp87285604** [Chatie/wechaty#1204]
node -v
v8.4.0
Google Chrome 
 66.0.3359.170
 Wechaty v0.14.1
 环境信息如上 ，请问是否需要安装Chromedriver？如果不需要那么什么情况下需要安装Chromedriver？如果需要的话应该如何安装 Chromedriver 需要先装python和Selenium么？

**Comment by zixia** [comment]
Could you please tell me why do you think you have to install the Chromedriver, Python, and Selenium, for example, read which part of the document, or watch which video?

I'd like to modify the content of it because that information is out-of-date.

Currently, say Wechaty v0.14, we do not need Python and Selenium, and for the Chrome part, we are using the `puppeteer`, which can be installed automatically when you run `npm install`.

TL;DR: you just need to run `npm install` (be sure there's no wrong, especially you are on a server inside China), then you are set.

**Comment by shp87285604** [comment]
非常感谢您的回答 
我的一些问题来自于下面的简书页面
https://www.jianshu.com/p/974c44fef0d2
有以下几点值得注意的是：

1.Wechaty需要的Node版本最少在6以上，我现在在使用7。
2.有一些环境是需要安装Chromedriver的，根据版本不同，大家可能需要注意一下。
3.如果是在服务器上，需要到Script的脚本中，运行下xvfb.sh的脚本，为Chrome提供一个虚拟的运行环境，并根据运行后的提示，设置程序运行的环境变量。
4.同样可以设置WECHATY_LOG的值来打印系统日志：WECHATY_LOG=SILLY node mybot.js
关于服务器的说明

Wechaty依赖的很多包都在墙外，建议使用国外的VPS，我使用的是digitalocean 如果只是跑一个机器人服务的话，建议使2GB/2 CPUs 以上的配置，一个机器人服务会占用1G内存左右，如果配上swap的话，短期使用也可以。

作者：李佳芮_chatbot
链接：https://www.jianshu.com/p/974c44fef0d2
來源：简书
网上我并没有找到最新的中文文档或者介绍  这一篇的确很老 如果有什么最新的文档或者社区论坛 希望您能推荐给我  

其实开始时并没有特别注意这一段文字
但是运行机器人时（first.js） 出现了报错 我怀疑自己的环境配置出现了问题 具体是
运行之后360卫士 会一直报一个关于Chrome浏览器被调用的警告 而且警告无法关闭忽略警告之后出现下图报错  关闭360卫士和杀毒软件后依然会出现同样的报错

first.js文件如下
var Wechaty = require('wechaty').Wechaty;
var bot = Wechaty.instance();
bot
    .on("scan", function (url, code) { console.log(url); })
    .on("login", function (username) {
    console.log("${username} login");
    var login = url.replace("qrcode", "l");
    require("qrcode-terminal").generate(loginUrl);
})
    .on('message', function (m) {
    var contact = m.from();
    var content = m.content();
    var room = m.room;
    var type = m.type;
    if (m.self()) {
        console.log("bot say ${content}");
    }
    if (type === 1) {
        if (room) {
            console.log("Room ${room.topic()} Contanct ${contact.name()} Content $(content)");
        }
        else {
            console.log("Contanct ${contact.name()} Content $(content)");
        }
    }
})
    .start();

![11111111111113151456](https://user-images.githubusercontent.com/29415590/39964929-c3d1da2e-56c1-11e8-8252-fdb7cefb02ee.png)

上面的例子是根据以前nodeparty 录像里的例子写的 后面的start()是根据报错修正的

可以运行您在wechaty介绍中给出的这个例子
const { Wechaty } = require('wechaty')
const bot = Wechaty.instance()
console.log(bot.version())

package.json 配置如下
{
  "name": "my-bot",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "qrcode-terminal": "^0.12.0",
    "ts-node": "^6.0.3"
  }
}

**Comment by shp87285604** [comment]
非常感谢您的回答
我的一些问题来自于下面的简书页面
https://www.jianshu.com/p/974c44fef0d2
“有以下几点值得注意的是：

1.Wechaty需要的Node版本最少在6以上，我现在在使用7。
2.有一些环境是需要安装Chromedriver的，根据版本不同，大家可能需要注意一下。
3.如果是在服务器上，需要到Script的脚本中，运行下xvfb.sh的脚本，为Chrome提供一个虚拟的运行环境，并根据运行后的提示，设置程序运行的环境变量。
4.同样可以设置WECHATY_LOG的值来打印系统日志：WECHATY_LOG=SILLY node mybot.js
关于服务器的说明

Wechaty依赖的很多包都在墙外，建议使用国外的VPS，我使用的是digitalocean 如果只是跑一个机器人服务的话，建议使2GB/2 CPUs 以上的配置，一个机器人服务会占用1G内存左右，如果配上swap的话，短期使用也可以”。

作者：李佳芮_chatbot
链接：https://www.jianshu.com/p/974c44fef0d2
來源：简书
网上我并没有找到最新的中文范例或者介绍 这一篇的确很老 如果有什么最新的文档或者社区论坛 希望您能推荐给我

其实开始时并没有特别注意这一段文字
但是运行机器人时（TRY2..js） 出现了报错 我怀疑自己的环境配置出现了问题 具体是
运行之后360卫士 会一直报一个关于Chrome浏览器被调用的警告 而且警告无法关闭忽略警告之后出现下图报错 关闭360卫士和杀毒软件后依然会出现同样的报错

![222222222226](https://user-images.githubusercontent.com/29415590/39990747-fd084434-579f-11e8-90f3-dcb55a581abd.png)



TRY2.ts文件如下
const { Wechaty } = require('wechaty')
Wechaty.instance()
.on('scan', (url, code) => console.log(`Scan QR Code to login: ${code}\n${url}`))
.on('login',  user => console.log(`User ${user.name()} logined`))
.on('message',  message => console.log(`Message: ${message.content()}`))
.init()

这个例子也来自上面的简书页面

同时运行您给出的api-ai-bot.ts例子
import 
 {config,
  Wechaty,
  Message}
         from 'node_modules/wechaty/src/'
部分总是报找不到node_modules/wechaty/src/的错 from地址是我项目的地址按照您之前的../src写的
import * as QrcodeTerminal  from 'qrcode-terminal' 采用这种方式的引入就很正常的执行了 其他的文件也有这种引入的问题
我第一次用ts感到很困惑 希望得到您的帮助


![q0](https://user-images.githubusercontent.com/29415590/39990780-126c45c8-57a0-11e8-9b09-4e88928249fc.png)


目前只能运行您在wechaty介绍中给出的这个例子
const { Wechaty } = require('wechaty')
const bot = Wechaty.instance()
console.log(bot.version())

package.json 配置如下
{
  "name": "my-bot",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "finis": "^0.4.2",
    "qrcode-terminal": "^0.12.0",
    "ts-node": "^6.0.3"
  }
}

tsconfig.json配置如下
{
  "compilerOptions": {
    "target": "es6"
    , "module": "commonjs"
    , "outDir": "dist"
    , "declaration": true
    , "sourceMap": true
    , "noLib": false
    , "noEmitOnError": true
    , "noUnusedLocals": true
    , "noImplicitReturns": true
    , "noFallthroughCasesInSwitch": true
    , "strictNullChecks": true
    , "experimentalDecorators": true
    , "emitDecoratorMetadata": true
    , "noImplicitAny": false
noImplicitAny这一项在您的配置里是ture 但是 我这么配置 ts-node 就会报错  只能设为false
报错如下
![1111111111111](https://user-images.githubusercontent.com/29415590/39991640-c572e0b2-57a2-11e8-9fc3-6074426f4124.png)
    , "noUnusedParameters": false
    , "noImplicitThis": false
    , "traceResolution": false
    , "lib": [
        "esnext","es6", "dom", "es2015.collection", "dom"
    ]
  }
  , "exclude": [
      "node_modules/"
    , "dist/"
  ]
  , "include": [
       "app/**/*.ts"
     , "bin/*.ts"
     , "bot/**/*.ts"
     , "examples/**/*.ts"
     , "scripts/**/*.ts"
     , "src/**/*.ts"
     , "tests/**/*.spec.ts"
  ]
}

**Comment by zixia** [comment]
I want to be helpful but I'm afraid that I could not do any support job at here because I'm very busy, sorry about that.

I'd like to suggest you join the `Wechaty Developers' Community` Wechat Room, to discuss with other developers. 

You can find the QRCode from the README, good luck.

**Comment by zixia** [comment]
I'll close this issue because of inactivity.

The better way to discuss question is to join the community and talk to other developers.
