### ISSUE TITLE
Error: class can not be instanciated directly!

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#1217]
Currently, the `Contact`, `FriendRequest`, `Message`, and `Room` classes will not be able to instantiate directly, because they must attach with a Puppet.

They need to be `cloneClass()`-ed first, then attach the puppet, and at last they will be ready for use by:
1. `wechaty.Contact`, or
1. `puppet.Contact`, etc.

### ~~~Do Not~~~

```ts
import { Room } from 'wechaty'
const room = await Room.create(...)
```

The above code will throw error.

### Do

```diff
- import { Room } from 'wechaty'
+ import { Wechaty } from 'wechaty'

- const room = await Room.create(...)
+ const wechaty = new Wechaty()
+ const room = await wechaty.Room.create(...)
```

So does Contact, FriendRequest, and Message.

### See Also

1. Wechaty Multi-Instance Suport #518
1. NPM [clone-class](https://www.npmjs.com/package/clone-class)

**Comment by lijiarui** [comment]
It may should be 
```
const wechaty = Wechaty.instance()
const room = await wechaty.Room.create(...)
```

**Comment by zixia** [comment]
@yarray there's a example that demonstrated how to create a new room, hope that could help you to understand.

https://github.com/Chatie/wechaty/blob/master/examples/room-bot.ts

**Comment by lhr0909** [comment]
@lijiarui @huan What happens if we need to use the type definitions for these classes?

See `_contactPayload` and the `WechatBotAdapter`, which currently we get yelled at for the extended `WechatBotAdapter` for the same issue.

![image](https://user-images.githubusercontent.com/1154575/49265843-c86e3800-f48e-11e8-8113-f9e4e8bc8f5c.png)

**Comment by lhr0909** [comment]
Well, crisis averted. Sorry for the ping

![image](https://user-images.githubusercontent.com/1154575/49265922-0ff4c400-f48f-11e8-85ee-1d13bdf0d7da.png)

**Comment by zulkifalaziz** [comment]
How can I receive and display and image in Python? I have tried finding the solution in documentation but no success.
