### ISSUE TITLE
can't run the typescript examples

### ISSUE THREAD

**Issue by francishero** [Chatie/wechaty#1221]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)
local dev windows 10
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?
none

### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 

$ npm run doctor

> wechaty@0.15.42 doctor C:\Users\towela\Documents\projects\bots-wechat\wechaty
> npm run check-node-version && ts-node bin/doctor

> wechaty@0.15.42 check-node-version C:\Users\towela\Documents\projects\bots-wechat\wechaty
> check-node-version --node ">= 8.5"

  #### Wechaty Doctor

  1. Wechaty version: #git[3912981]
  2. Windows_NT x64 version 10.0.16299 memory 5612/11209 MB
  3. Docker: false
  4. Node version: v9.9.0
  5. Tcp IPC TEST: PASS

### Expected behavior

i do tsc examples/filename.tsc should spit a filename.js to run using node filename.js in the terminal

### Actual behavior

../src/puppet-puppeteer/puppet-puppeteer.ts(626,34): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
../src/puppet-puppeteer/puppet-puppeteer.ts(636,49): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
../src/puppet-puppeteer/puppet-puppeteer.ts(675,6): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
../src/puppet-puppeteer/puppet-puppeteer.ts(743,59): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
../src/puppet-puppeteer/puppet-puppeteer.ts(765,44): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
../src/puppet-puppeteer/puppet-puppeteer.ts(795,19): error TS2693: 'Promise' only refers to a type, but is being used as a value here.
../src/puppet-puppeteer/puppet-puppeteer.ts(813,6): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
../src/puppet-puppeteer/puppet-puppeteer.ts(819,11): error TS2693: 'Promise' only refers to a type, but is being used as a value here.
../src/puppet-puppeteer/puppet-puppeteer.ts(843,6): error TS2304: Cannot find name 'Map'.
../src/puppet-puppeteer/puppet-puppeteer.ts(849,17): error TS2304: Cannot find name 'Map'.
../src/puppet-puppeteer/puppet-puppeteer.ts(849,43): error TS2304: Cannot find name 'Map'.
../src/puppet-puppeteer/puppet-puppeteer.ts(887,6): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` op.....................................

TSError: ⨯ Unable to compile TypeScript
Cannot find global value 'Promise'. (2468)
ding-dong-bot.ts (83,16): An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option. (2705)
ding-dong-bot.ts (124,17): An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option. (2705)
ding-dong-bot.ts (138,18): Property 'name' does not exist on type 'SignalsListener'. (2339)
    at getOutput (C:\Users\towela\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:330:15)
    at Object.compile (C:\Users\towela\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:516:11)
    at Module.m._compile (C:\Users\towela\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:403:43)
    at Module._extensions..js (module.js:660:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\towela\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:406:12)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at Object.<anonymous> 

### Steps to reproduce the behavior (and fixes, if any)

npm i -g typescript
cd wechaty/examples
tsc anyfilename.ts
or 

ts-node filename.js 

### Full Output Logs

```shell
$ WECHATY_LOG=silly npm run ts-node mybot.ts
 WECHATY_LOG=silly npm run ts-node mybot.ts

> wechaty@0.15.42 ts-node C:\Users\towela\Documents\projects\bots-wechat\wechaty
> ts-node "mybot.ts"

Error: Cannot find module 'C:\Users\towela\Documents\projects\bots-wechat\wechaty\mybot.ts'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Function.Module.runMain (module.js:690:10)
    at Object.<anonymous> (C:\Users\towela\Documents\projects\bots-wechat\wechaty\node_modules\_ts-node@6.0.3@ts-node\src\bin.ts:145:12)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wechaty@0.15.42 ts-node: `ts-node "mybot.ts"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wechaty@0.15.42 ts-node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\towela\AppData\Roaming\npm-cache\_logs\2018-05-21T20_49_00_060Z-debug.log

# or 

$ WECHATY_LOG=silly node dist/mybot.js

```

<details>
<summary>
Show Logs
</summary>

### Paste the full output logs here with `WECHATY_LOG=silly` set 

```shell
# PASTE FULL LOG OUTPUT AT HERE:



```
</details>

**Comment by zixia** [comment]
Do a `npm install @types/node` and try again?

**Comment by francishero** [comment]
git clone -b v0.14 git@github.com:Chatie/wechaty.git 

this will fix your issue

**Comment by zixia** [comment]
@luke0zong Please don't use the `latest` tag because it is always not stable.

use docker image `zixia/wechaty:0.14` instead.

See: #1200
