### ISSUE TITLE
Create a websocket ipad demo

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#1228]
As web WeChat always been blocked, so we are trying to find a more stable solution for developers, see more: [puppet](https://github.com/chatie/wechaty/wiki/puppet)

I had co-operated with a third party who has iPad protocol, but we need a WebSocket to test all API, we need a volunteer to test and encapsulated API.

**Comment by binsee** [comment]
under way

https://github.com/binsee/padchat-sdk/

**Comment by lijiarui** [comment]
Thanks!
