### ISSUE TITLE
New Puppet: PuppetPadchat

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#1249]
# Puppet Repository

https://github.com/lijiarui/wechaty-puppet-padchat
~~https://github.com/lijiarui/wechaty/tree/new-puppet-padchat~~

## 1. Message
- [x] save all messageRawPayload  #1250
- [x] read messageRawPayload by id #1253 

then the following functions can easy to implement:
- [x]  function messageForward()  
- [ ]  function messageFile() : save file to local
- [x]  function messageRawPayload()

## 2.  Contact | Room
- [x] function contactFindAll() #1251 
- [x] function roomFindAll()  #1255

## 3.  FriendRequest
- [x] friendRequestSend #1252 
- [x] friendRequestAccept #1254

**Comment by zixia** [comment]
Please check out the latest code and follow the changes. 

The design changes a lot, if you get confusing, I believe the best way is to have a look into `PuppetPuppeteer`.

**Comment by lijiarui** [comment]
There is only one function remain bug!  See: https://github.com/Chatie/wechaty/issues/1349

**Comment by zixia** [comment]
Most of the wechaty examples can be run under PuppetPadchat now!

**Comment by zixia** [comment]
Does this issue needs to be keep open to track something?

I think we had done this and can be closed.

**Comment by zixia** [comment]
@lijiarui

**Comment by lijiarui** [comment]
done, thanks
