### ISSUE TITLE
rewrite contactFindAll()

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#1251]
#1249 

should complete the contactFindAll()

**Comment by zixia** [comment]
Good news: there will be not necessary to implement `contactFindAll()` for a puppet for now.

You need to implement `contactList()` instead, should return all `contactId` as a string[].

Know more from #1255

**Comment by zixia** [comment]
Done.

Please check and close this issue if there's no problem.

**Comment by lijiarui** [comment]
all is ok, thanks!
