### ISSUE TITLE
 read messageRawPayload by id

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#1253]
#1249

When the framework as saved all messageRawPayload, it should provide a function to read messageRawPayload by id.

**Comment by zixia** [comment]
In order to do that, you need to:

1. save `rawMessagePayload` to the `this.cacheXXX` first:

```ts
this.cachePadchatMessageRawPayload.set(id, {
      id: 'xxx',
      data: 'xxx',
    } as any)
```

2. get it back when needed:

```ts
    const rawPayload = this.cachePadchatMessageRawPayload.get(id)
```

See the following commit to learn more.

**Comment by zixia** [comment]
Done. Please close this issue if there's all ok.

**Comment by lijiarui** [comment]
all is ok, thanks!

**Comment by lijiarui** [comment]
all is ok, thanks!
