### ISSUE TITLE
function friendRequestAccept

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#1254]
#1249

should complete the function: friendRequestAccept() and give a code demo

**Comment by zixia** [comment]
Usage:

```ts
await wechaty.FriendRequest.send(contactId, 'hello')
```

### See Also

https://github.com/Chatie/wechaty/blob/917517045eadb1f154ac409d99d2742df045590f/src/friend-request.ts#L72-L86

**Comment by zixia** [comment]
The latest code had been able to accept the friend request with a `ding` message automatically.

Please test and confirm all is ok before you close this issue.

**Comment by lijiarui** [comment]
all is ok, thanks!

**Comment by lijiarui** [comment]
all is ok, thanks!
