### ISSUE TITLE
rewrite roomFindAll() 

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#1255]
#1249

should complete the roomFindAll()

**Comment by zixia** [comment]
Good news: there will be not necessary to implement `roomFindAll()` for a puppet for now.

You need to implement `roomList()` instead, should return all `roomId` as a `string[]`.

**Comment by zixia** [comment]
Done. Please close this issue if all is ok.

**Comment by lijiarui** [comment]
all is ok, thanks!
