### ISSUE TITLE
最新版本Contact没有uin字段了吗？

### ISSUE THREAD

**Issue by Astlvk** [Chatie/wechaty#1276]
version 0.15.97
打印后找不到uin了 不知还有这个字段吗
想用来作联系人的唯一值的。

**Comment by zixia** [comment]
You can use `yourContact.id` as the unique id for the contact after v0.15.

`uin` had been dropped because we have to encapsulate the data payload in order to support different Puppet implementations.

**Comment by Astlvk** [comment]
联系人 id 的话好像每次重新登陆也都会变动？

**Comment by zixia** [comment]
The answer depends.

Yes, id will change everytime you re-login: if you are using **PuppetPuppeteer**, which is based on the web API.

No, id will keep the same across different login sessions: if you use the latest **PuppetPadchat**

Please checkout the latest code from master branch and have a look, also welcome to join the alpha test!

See: #1245

**Comment by Astlvk** [comment]
thx
