### ISSUE TITLE
如何发送消息到指定的微信群？

### ISSUE THREAD

**Issue by zmrbak** [Chatie/wechaty#1292]
我正在使用C#为WeChaty做一个管理微信群的管理软件。
通过C#向选中的微信群中发送消息的时候遇到了困难。

现在已经通过Room.findAll()找到了这个微信加入的微信群，并从中找到了目标微信群，接下来怎么才能够发送呢？

**Comment by zixia** [comment]
You can use `room.say()`, its usage is just as same as the `message.say()`.

See:

https://github.com/Chatie/wechaty/blob/e6794dd5b4543fb00fda4b0cef40b7f034d3d544/examples/room-bot.ts#L310-L316

**Comment by zmrbak** [comment]
All done.
Thank you for your help!

**Comment by zmrbak** [comment]
All done.
Thank you for your help!
