### ISSUE TITLE
feat: PuppetPadchat support send voice(direct play, no download)

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#1300]
```ts
const file = FileBox.fromFile('voice.slk') // must be a silk format.
contact.say(file)
```

All you need is to convert the audio file format to SILK, and keep the length less than 60 seconds.

### See

1. https://github.com/kn007/silk-v3-decoder
1. https://stackoverflow.com/a/42337871/1123955

**Comment by binsee** [comment]
Actually, this can send over 60 seconds of audio files, haha

**Comment by binsee** [comment]
Please note that you need to add a parameter that indicates the length of the speech in milliseconds.

**Comment by zixia** [comment]
@binsee Did you know any good way to get the length of the speech file with silk format in node?

**Comment by binsee** [comment]
If you give me a silk voice file, I can't know the length of time without using a tool to convert the file format.

If the voice is sent by someone else, you can extract the length of the voice from the xml structure of the message.

https://github.com/binsee/padchat-sdk/blob/fc903f62a5d254a4e55cf31bb65543aa99a47283/demo.js#L324

```js
let   match  = data.content.match(/length="(\d+)"/) || []
const length = match[1] || 0
	  match  = data.content.match(/voicelength="(\d+)"/) || []
const ms     = match[1] || 0
logger.info('语音数据语音长度：%d ms，xml内记录尺寸：%d', ms, length)
```

**Comment by binsee** [comment]
Silk v3 decoder: https://github.com/kn007/silk-v3-decoder

**Comment by zixia** [comment]
Move to https://github.com/lijiarui/wechaty-puppet-padchat/issues/100
