### ISSUE TITLE
How to get the user's wechat account（微信号）？

### ISSUE THREAD

**Issue by 3014zhangshuo** [Chatie/wechaty#1307]
I try to get use `wexin()` method, but got `null`. Is there a way to get a wechat account?
```
.on('message', async message => {
  console.log(`RECV: ${message}`)
  const wx_user = message.from()
  console.log(wx_user.weixin()) => null
})
```

**Comment by zixia** [comment]
You can not get wexin id for a contact if you are using the Web API(like PuppetPuppeteer, or PuppetWechat4u).

You can get wexin id if you use stronger Puppets, like PuppetPadchat.

Learn more at: #1296

**Comment by 3014zhangshuo** [comment]
I will try it. Thank you for your answer.

**Comment by zixia** [comment]
Could you please close this issue?

**Comment by radishyell** [comment]
@3014zhangshuo  你获取到微信号了么？PuppetPadchat 这个是不是在 0.15的版本才有支持？
