### ISSUE TITLE
PuppetPadchat: support message type of `StatusNotify` with `op id` push update information

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#1310]
Currently we did not deal with all `StatusNotify` message, however, it seems will be very useful in the future.

For example, when a user is deleted from the phone, or they updated their contact information, or a room has updated its information, it seems the Tencent Server will send a `StatusNotify` to us with an `op id` and the necessary information.

The following StatusNotify message seems like to notify us the user(lizhuohuan) is deleted from the contact(?)

```
14:40:49 VERB PuppetPadchat onPadchatMessage({id=8515776044911905267, type=StatusNotify(5)})
rawPayload: { content:
   '<msg>\n<op id=\'5\'>\n<username>lizhuohuan</username>\n</op>\n</msg>',
  continue: 1,
  description: '',
  from_user: 'wxid_5zj4i5htp9ih22',
  msg_id: '8515776044911905267',
  msg_source: '',
  msg_type: 5,
  status: 1,
  sub_type: 51,
  timestamp: 1528785648,
  to_user: 'lizhuohuan',
  uin: 1928023446 }
```

**Comment by lvxuan263** [comment]
Note: 
Ipad puppet receives StatusNotify(op id=2) when you enter a conversation on the mobile. The field of the notify is the same as yours.

But only if you enter the conversation through the contacts list and then exit the conversation you will receive StatusNotify(op id=5)

**Comment by zixia** [comment]
@lvxuan263 thanks, please keep posting at here about anything you found about the op id.

**Comment by zixia** [comment]
It seems this event can be used to identify: Conversation enter/leave event.

**Comment by zixia** [comment]
Close this issue because I have no idea about how to use it after another week.
