### ISSUE TITLE
Puppet Padchat: Receive image, video, emoticon, and voice messages

### ISSUE THREAD

**Issue by lvxuan263** [Chatie/wechaty#1314]
**File:** puppet-padchat.ts

**Function:** messageFile()

```javascript
switch (payload.type) {
      case MessageType.Attachment:
        break
      case MessageType.Audio:
        result = await this.bridge.WXGetMsgVoice(rawText)
        console.log(result)
        return FileBox.fromBase64(result.data.image, 'test.slk')
      case MessageType.Emoticon:
        result = await this.bridge.WXGetMsgImage(rawText)
        console.log(result)
        return FileBox.fromBase64(result.data.image, 'test.gif')
      case MessageType.Image:
        result = await this.bridge.WXGetMsgImage(rawText)
        console.log(result)
        return FileBox.fromBase64(result.data.image, 'test.jpg')
      case MessageType.Video:
        result = await this.bridge.WXGetMsgVideo(rawText)
        console.log(result)
        return FileBox.fromBase64(result.data.image, 'test.mp4')
      default:
            //......
}
```
 The **result.data** is not exist. 

The base64 field of voice msg is **result.voice**.
The base64 field of image msg is **result.image**.
The base64 field of video msg is **result.video**.

The  emoticon msg is an xml, and CDN url is in the xml. maybe it wouldn't get from ws.

**Comment by zixia** [comment]
Thank you for the contribution!

I had follow your analytics result and now it should get the base64 from the right place.

Please checkout the latest code and let me know if you have any future enhance suggestions.

**Comment by zixia** [comment]
Could you please test the latest code and see if those attachments work as expected?

If it could, can we close this issue for now?

**Comment by zixia** [comment]
Move to https://github.com/lijiarui/wechaty-puppet-padchat/issues/101
