### ISSUE TITLE
PadchatRpc WXCheckQRCode result: {"message":"WS请求错误","status":-19}

### ISSUE THREAD

**Issue by lvxuan263** [Chatie/wechaty#1315]
After testing, it was found that in the case of no login, puppet for **5 minutes** will receive a "WS请求错误", and the error message can still emit scan events.

After an error occurs, puppet will reinitialize the wxuser and then trigger the scan event according to the normal process.

If timeout is better to exit the program or re-initialize automatically?

**Comment by lijiarui** [comment]
could you check out the latest code and see if it is exist?

**Comment by zixia** [comment]
Had done some compatible work on this insistent api return value, please let us know if you have problem with the latest code.
