### ISSUE TITLE
can't send video. need help

### ISSUE THREAD

**Issue by radishyell** [Chatie/wechaty#1317]
THX for wechaty。my english so pool 。 i brief description my problem。
i am refer to example of 'ding-dong-bot.ts' but i find , i can't send video , but image is success.

### my video size 
428 × 240    
233 KB

## just look code:

const r = filePath => path.resolve(__dirname, filePath);
const filepath = r('../resource/video/1.mp4');
var data = new MediaMessage(filepath);
console.log(data);
await msg.say(data)

### error log

16:05:41 ERR PuppetWeb uploadMedia() uploadMedia exception: read ETIMEDOUT
16:05:41 ERR PuppetWeb sendMedia() exception: uploadMedia err: read ETIMEDOUT

### log info :

MediaMessage {
  rawObj: {},
  obj:
   { id: undefined,
     type: undefined,
     from: undefined,
     to: undefined,
     content: undefined,
     status: undefined,
     digest: undefined,
     date: undefined,
     url: undefined },
  _counter: 1,
  id: undefined,
  filePath:
   '/Users/Radish/Desktop/wechat/wechatRobot/resource/video/1.mp4',
  fileName: '1',
  fileExt: 'mp4',
  bridge:
   Bridge {
     domain: null,
     _events:
      { ding: [Function: bound onDing],
        error: [Function],
        log: [Function: bound onLog],
        login: [Function: bound onLogin],
        logout: [Function: bound onLogout],
        message: [Function: bound onMessage],
        scan: [Function: bound onScan],
        unload: [Function: bound onUnload],
        load: [Function: bound onLoad] },
     _eventsCount: 9,
     _maxListeners: undefined,
     options: { head: false, profile: [Profile] },
     state:
      StateSwitch {
        _name: 'PuppetWebBridge',
        log: [Brolog],
        _on: true,
        _pending: false,
        offPromise: [Promise],
        onResolver: [Function: nop],
        onPromise: [Promise],
        offResolver: [Function] },
     browser:
      Browser {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        _ignoreHTTPSErrors: false,
        _setDefaultViewport: true,
        _process: [ChildProcess],
        _screenshotTaskQueue: [TaskQueue],
        _connection: [Connection],
        _closeCallback: [Function: gracefullyCloseChrome],
        _defaultContext: [BrowserContext],
        _contexts: Map {},
        _targets: [Map] },
     page:
      Page {
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        _closed: false,
        _client: [CDPSession],
        _target: [Target],
        _keyboard: [Keyboard],
        _mouse: [Mouse],
        _touchscreen: [Touchscreen],
        _frameManager: [FrameManager],
        _networkManager: [NetworkManager],
        _emulationManager: [EmulationManager],
        _tracing: [Tracing],
        _pageBindings: [Map],
        _ignoreHTTPSErrors: false,
        _coverage: [Coverage],
        _defaultNavigationTimeout: 30000,
        _screenshotTaskQueue: [TaskQueue],
        _workers: Map {},
        _viewport: [Object] } } }

**Comment by zixia** [comment]
@radishyell Thanks for report this issue.

There are many limitations from the Tencent Web API for Wechat for sending video file.

I noticed that you are using Wechaty v0.14, for v0.14, I'd like to suggest you to try to send your video file through the Web in your Browser and see if it can succeed.

In other hands, I'd like to suggest you try the new version of Wechaty v0.15, which is currently in heavy developing in the master branch. You could be able to do more with the new Puppet of Padchat, and I believe if you report the issue for v0.15, we could be able to respond for it more quickly.

Learn more about Wechaty v0.15 at #1296

**Comment by radishyell** [comment]
@zixia  i can send video on wechat web .  but in my code . can't send this video .

**Comment by zixia** [comment]
@radishyell Then there must have some implementation problem with the PuppetPuppeteer code.

If you are interested to fix this bug, please read the code and let me know when you need help.

**Comment by zixia** [comment]
Merge to  #951 because this is related to it. (but notice that this is a `ETIMEDOUT` instead of an `ECONNRESET` error)
