### ISSUE TITLE
Should bot.Contact.findAll() return actual friend list?

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#1320]
#### Now:
`bot.Contact.findAll()` return all related contact, including in the room and non-friendship contact

#### Future:
It should return actual contact list, only the contact has a friendship with the bot.    
The number should the same as the mobile phone number

**Comment by zixia** [comment]
First, we need to make it clear about what is **Contact**

In Wechaty world, everybody is a Contact, which includes: Friends, Members in Rooms, Official Account, etc.

For example: when we received a Message in a Room, we can use `msg.from()` to get a Contact of who said this message, no matter who they are, friend or not.

So, I believe the best way about the behavior of `Contact.findAll()` is to keeping the current behavior: return all the Contact that Wechaty could be able to find.

If you want to filter out the result to only include Friends, you can use the following filter syntax to get it done:

```ts
const contactList = await Contact.findAll()
const friendList = contactList.filter(contact => contact.friend())
```

Friend.findAll()

**Comment by lijiarui** [comment]
got it.

**Comment by zixia** [comment]
Do you still have any problem with this?

If you have, could you please post what you think as the reply so that we could continue discussing this topic;
If you have not, please close this issue.

THANK YOU VERY MUCH.
