### ISSUE TITLE
can't run demo

### ISSUE THREAD

**Issue by radishyell** [Chatie/wechaty#1337]
@zixia  

THX for your wechaty from v0.15.167

i am download from github code . and run in node environment。but i can't run the demo 。 this is my step:

1、 cd  wechaty-master/examples
2、npm start ( ts-node ding-dong-bot.ts )

### show some error 

12:16:44 INFO Wechaty v0.15.167 starting...
12:16:44 INFO Wechaty initPuppet() using puppet: puppeteer
(node:19522) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at PuppetPuppeteer.<anonymous> (/Users/Radish/Desktop/wechaty-master/src/puppet-puppeteer/event.ts:95:33)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/Radish/Desktop/wechaty-master/src/puppet-puppeteer/event.ts:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:19522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19522) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### i have some suggest
i think may be some developer don't know how to run the demo .
if @zixia   you have some time , you can  write a  detail  course  about how to run the demo .
thank you very very much .

## 1、download code an go to file  cd wechaty-master/examples :
      RadishdeMacBook-Pro:examples
## 2、try to look ts-node version , i am no install ts-nodel:
      RadishdeMacBook-Pro:examples Radish$ ts-node -v
      bash: ts-node: command not found
## 3、install ts-node :
      RadishdeMacBook-Pro:examples Radish$ sudo npm install -g ts-node 
      RadishdeMacBook-Pro:examples Radish$ sudo npm install -g typescript
      RadishdeMacBook-Pro:examples Radish$ ts-node -v
      ts-node v6.1.1
      node v10.3.0
      typescript v2.9.2
     cache "/var/folders/2_/tymztdk55lz6mh20cx6ngxg40000gn/T/ts-node-8ad684cb67a82e37dd1ebd0d41951c3503d317f250347ec755aad52d2c9d444e/d6ad0660bc25582c818797f15fa0aba48886bbcc112ec445dd9f0ff9ecabf068)

## 4、try npm install, but fail ,  i try  npm install @types/node, and  npm install, it looks success .
     RadishdeMacBook-Pro:wechaty-master Radish$：npm install @types/node
     RadishdeMacBook-Pro:wechaty-master Radish$：npm install

## 5、 run demo （fail）
    RadishdeMacBook-Pro:examples Radish$ npm start

**Comment by zixia** [comment]
@radishyell Thank you very much for reporting this issue.

This bug was introduced by the latest refactoring work of the new Puppet system.

Please try the latest master branch code, this bug should have already been fixed.

And as we are testing the v0.15 with new Puppet, please also have a look at #1296
