### ISSUE TITLE
Prevent the Floating Promise in the Async/Await Code

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#1346]
According to #1289, we should always await a Promise no matter than what because it will prevent we to make very hard to track mistakes.

So we should enable tslint to check the floating promise for us. So should all the developers do if you are writing async/await code:

Related configuration in ***tslint.json***:

```json
{
    "extends": "tslint:recommended",
    "rules": {
        "no-floating-promises": true
    }
}
```

### See Also

- [Detect missing await in TypeScript](https://www.meziantou.net/2017/11/20/detect-missing-await-in-typescript)

**Comment by zixia** [comment]
@lijiarui Could you please help me to check out the latest master branch of code, and fix all the warnings when running `npm run lint`, then send me back a PR to fix them?

Thanks.

**Comment by lijiarui** [comment]
see #1348

**Comment by zixia** [comment]
Thank you very much.
