### ISSUE TITLE
friendship.accept() should return boolean

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#1357]
When using the `wechaty- puppet-padchat`, `friendship.accept()` return `Promise<void>`

It used to return `Promise<boolean>` before, I suggest returning `Promise<boolean>` this time too, in order to let the developer know whether the operation succeeds or not.

**Comment by zixia** [comment]
Do you still have any problem with this?

If you have, could you please post what you think as the reply so that we could continue discussing this topic;
If you have not, please close this issue.

THANK YOU VERY MUCH.

**Comment by lijiarui** [comment]
well, I still think the developer should know whether the operation had done successfully ...

**Comment by zixia** [comment]
Okay, I understand.
