### ISSUE TITLE
How to run a new wecahty-puppet-padchat

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#1361]
### 1. Install
```shell
npm install wechaty@next
```

### 2. Run

- Get `WECHATY_PUPPET_PADCHAT_TOKEN` from #1296 

- Set `WECHATY_PUPPET_PADCHAT_TOKEN` and Set `WECHATY_PUPPET=padchat`

### 3. Start Command
```shell
WECHATY_PUPPET_PADCHAT_TOKEN=your padchat token WECHATY_PUPPET=padchat   node examples/ding-dong-bot.js

```

### 1. Install
```shell
docker pull zixia/wechaty:latest
```

### 2. Run

- Get `WECHATY_PUPPET_PADCHAT_TOKEN` from #1296 

- Set `WECHATY_PUPPET_PADCHAT_TOKEN` and Set `WECHATY_PUPPET=padchat`

### 3. Start Command

```shell
docker run -t -i  -e WECHATY_PUPPET="padchat" -e WECHATY_PUPPET_PADCHAT_TOKEN="your token"  --volume="$(pwd)":/bot --name=wechaty zixia/wechaty:latest examples/ding-dong-bot.ts
```

**Comment by Zhou-Bill** [comment]
ihad use npm install wechaty@next but i had some error, something like 
![image](https://user-images.githubusercontent.com/13554001/42124626-f7413c54-7c98-11e8-8305-320a7ac535f9.png)

how to solve ? i guess i   miss c++ library

**Comment by suntong** [comment]
- The OP is better moved to the wiki section as leaving issues open and unsolved is a bad thing. 
- The follow up question should better be in its own thread/issue. 

my 2c.

**Comment by lijiarui** [comment]
@suntong agree, move to wiki:

FAQ part : https://github.com/Chatie/wechaty/wiki/FAQ#11-how-to-run-a-new-wecahty-puppet-padchat

Puppet part: https://github.com/Chatie/wechaty/wiki/Puppet#2-run

**Comment by zixia** [comment]
@Zhou-Bill We had not test under the win32 environment yet(since v0.15), please try to use docker, or run under Linux/Osx.

@suntong Thanks for the great suggestion!

**Comment by Zhou-Bill** [comment]
i has install visual studio 2017 , it work ,but when i run "WECHATY_PUPPET=padchat WECHATY_PUPPET_PADCHAT_TOKEN=MY_TOKEN ts-node wechaty-bot.ts"，  it say  
![image](https://user-images.githubusercontent.com/13554001/42130995-43ef6446-7d29-11e8-8455-eb1f2ce8528e.png)

**Comment by Zhou-Bill** [comment]
it works ， thanks
