### ISSUE TITLE
How should we import `ContactType`

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#1368]
see #1366 

```ts
  /**
   * Return the type of the Contact
   *
   * @returns ContactType - Contact.Type.PERSONAL for personal account, Contact.Type.OFFICIAL for official account
   * @example
   * const isOfficial = contact.type() === Contact.Type.OFFICIAL
   */
  const type = Contact.type()
```

We should use import ContactType. 

But now, the import function is 
```ts
import { ContactType } from 'wechaty/dist/src/puppet'
```

I think we should import this from wechaty

**Comment by zixia** [comment]
No need to import `ContactType`.

use `wechaty.Contact.Type` instead.

**Comment by zixia** [comment]
Could you please close your issue**s** if it was solved or there's no any future problem?

**Comment by lijiarui** [comment]
I will check this later...  Because in my case, it doesn't work but I didn't find the reason yet...

Try to dig more in it...

**Comment by zixia** [comment]
@lijiarui You need a better glasses :-\

**Comment by lijiarui** [comment]
fix, thanks

**Comment by zixia** [comment]
Sorry, I don't think there has any problem need "to be fixed".

**Comment by suntong** [comment]
What's the latest way to access it @huan ?

I've tried both `PUPPET.types.Contact.Type.Official` and `PUPPET.types.ContactType.Official`, but both gave:

`TypeError: Cannot read properties of undefined (reading 'Official')`

thx

**Comment by huan** [comment]
@suntong You need to use TypeScript + VSCode to make your life easier, or you have to read the source code before you use it.

I believe with the latest version of the Wechaty v1.x you need to use ` PUPPET.types.Contact.Official`
