### ISSUE TITLE
WARN PuppetPuppeteer

### ISSUE THREAD

**Issue by radishyell** [Chatie/wechaty#1376]
i  run  npm install wechaty@next

version  "wechaty": "^0.15.220"

### init with code 

this.robot = Wechaty.instance();
this.robot.start().catch(function(error) {
            console.error('启动聊天机器人失败：%s', error)
            this.robot.stop()
            process.exit(-1)
        }.bind(this))

### but some warn :

17:20:45 WARN PuppetPuppeteer initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
17:22:47 WARN PuppetPuppeteer initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
17:24:49 WARN PuppetPuppeteer initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
17:26:50 WARN PuppetPuppeteer initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000

what should i do ?

**Comment by lijiarui** [comment]
Which puppet are you using? puppeteer or puppet-padchat?

**Comment by radishyell** [comment]
@lijiarui  to be honest ， i  don't know  what did i use . 
-。-
we init the robot , must have some option?  i apply for a token ‘ padchat-token-xxxxxx’ ， should  i write in optione?
Wechaty.instance({
profile:'?????',
puppet:'puppeteer'/ puppet:'puppet-padchat',
ioToken:'padchat-token-xxxxxx’'
});

**Comment by radishyell** [comment]
@lijiarui  thx for you answer 。
