### ISSUE TITLE
ts-node 7.0 breaking change: Skip `files` by default

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#1383]
Which caused our `src/typings.d.ts` did not load when running tests.

Might have other bugs, will continue monitoring it.

See: https://github.com/TypeStrong/ts-node/releases/tag/v7.0.0

### Update

According to <https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html>, reference typings.d.ts in config.ts could solve this issue better(with the benefits of the speed improvement of ts-node v7).

**Comment by lijiarui** [comment]
How to fix this? I pull the latest version:
```
 1. Wechaty version: 0.17.14
  2. Linux x64 version 3.16.0-4-amd64 memory 10514/15072 MB
  3. Docker: true
  4. Node version: v10.5.0
  5. Tcp IPC TEST: PASS
```

But error still exist..

**Comment by zixia** [comment]
It's a pity that you still do not understand how important of providing the reproduce steps with the logs in detail. sad.

**Comment by zixia** [comment]
@lijiarui Could you please confirm whether this issue is resolved?

If it did, please close this issue.
If it did not, please provide reproduce steps, and any workaround and pr fix is welcome.
