### ISSUE TITLE
Where can I see the complete API documentation of puppet-padchat, such as createRoom and Moment

### ISSUE THREAD

**Issue by Hunk-zhurui** [Chatie/wechaty#1391]
https://chatie.io/wechaty/
This site has only some interfaces for the web version

**Comment by zixia** [comment]
Yes, it's outdated.

Hope we could be able to sync with the latest code soon.

And it would be fantastic if there's anyone wants to help us to write the document!

Before that, the only way to learn the API from Wechaty could only be to read the source code... and make sure you are using VS Code IDE!
