### ISSUE TITLE
contact get payload from cache

### ISSUE THREAD

**Issue by windmemory** [Chatie/wechaty#1396]
I saw the code in `contact.ts` that the payload is get from `puppet.contactPayloadCache()`, which might potentially return undefined result. Is this expected?
Here is the code.
```typescript
  protected get payload(): undefined | ContactPayload {
    if (!this.id) {
      return undefined
    }
    return this.puppet.contactPayloadCache(this.id)
  }
```

If this is expected, then I think we might need to fix function `type` in `contact.ts`, seems like the type will throw error then the payload is `undefined`.
```typescript
  public type(): ContactType {
    return this.payload!.type
  }
```
If this is not expected, then should we change the method to `contactPayload`? Which will check the cache first, then retrieve from the server.

**Comment by zixia** [comment]
Thank you for reading the code so carefully, and this is a good question.

### Short answer

This is expected. 

You can add an `if (!this.payload) { throw new Error('no payload') }` before `return this.payload.type`, how ever, the code behavior will be the exactly same with `return this.payload!.type`: they will all throw an error when there's no payload.

### Long answer:

Yes we can change the method from `contactPayloadCache` to `contactPayload`, and if we change, we have to change all the methods of the `Contact` class from Sync to Async, which means introducing dozens of BREAKING CHANGES:

```diff
- public type(): ContactType {
+ public async type(): Promise<ContactType> {
```

This will be acceptable if we believe the current design pattern should be changed, how ever I'm not sure about that.

**Comment by windmemory** [comment]
Okay, for what you explained, seems make sense. 

Here is another confuse to me, if the user of wechaty get the Contact of someone, and the payload is undefined, is there anyway that the user would know the Contact is partial invalid? To my understanding, the payload carries all the information of the contact except the id, so no payload means contact not valid. if that's the case, maybe when we detect a Contact with empty payload, we make the Contact null to let the user know this Contact is not in good shape.

Is there any specific reason to allow a Contact with id, but no payload?

**Comment by zixia** [comment]
There's no reason to allow a Contact with id bug no payload.

To make it more clear: We should not create a contact with an id that can not get it's payload.

### The History

When we design Wechaty at the beginning, if we get a contact id, the payload will always exist, because in Web API, we get the id from the payload.

### Today

With Padchat Protocol, we will get contact id first, but the protocol will not guarantee we can get the payload, for example, the user is not a friend of the bot.

### Conclusion

In PuppetPadchat, we should filter the contact id out if it can not get any payload.

For example:

https://github.com/Chatie/wechaty/blob/1de61f430f381905fc486750be6ac23c429b4eed/src/puppet/puppet.ts#L391-L407

**Comment by zixia** [comment]
Too many wxids that can not get contact payload...

```
18:30:45 WARN PadchatRpc WXGetContact cannot get user_name, id: westpanda2011, "{}"
18:30:46 WARN PadchatRpc WXGetContact cannot get user_name, id: svxnse, "{}"
18:30:46 WARN PadchatRpc WXGetContact cannot get user_name, id: fqm880904, "{}"
18:30:46 WARN PadchatRpc WXGetContact cannot get user_name, id: wxid_lxowjizk5l9x22, "{}"
18:30:46 WARN PadchatRpc WXGetContact cannot get user_name, id: badboychen1007, "{}"
18:30:46 WARN PadchatRpc WXGetContact cannot get user_name, id: wxid_tm87i8jn6rny22, "{}"
18:30:46 WARN PadchatRpc WXGetContact cannot get user_name, id: qq648462158, "{}"
18:30:46 WARN PadchatRpc WXGetContact cannot get user_name, id: figozhaobaofei, "{}"
18:30:46 WARN PadchatRpc WXGetContact cannot get user_name, id: xiaoying_492349026, "{}"
18:30:46 WARN PadchatRpc WXGetContact cannot get user_name, id: wxid_1k3an4tkemk621, "{}"
18:30:46 WARN PadchatRpc WXGetContact cannot get user_name, id: cungeng, "{}"
18:30:46 WARN PadchatRpc WXGetContact cannot get user_name, id: pengyi519, "{}"
18:30:46 WARN PadchatRpc WXGetContact cannot get user_name, id: wxid_moqhctdmv11t21, "{}"
18:30:46 WARN PadchatRpc WXGetContact cannot get user_name, id: wxid_roymyl6axqyt21, "{}"
18:30:46 WARN PadchatRpc WXGetContact cannot get user_name, id: flashmouse, "{}"
18:30:46 WARN PadchatRpc WXGetContact cannot get user_name, id: Jaster123, "{}"
18:30:46 WARN PadchatRpc WXGetContact cannot get user_name, id: s362391172, "{}"
18:30:46 WARN PadchatRpc WXGetContact cannot get user_name, id: sqi547, "{}"
18:30:46 WARN PadchatRpc WXGetContact cannot get user_name, id: bestpay, "{}"
18:30:46 WARN PadchatRpc WXGetContact cannot get user_name, id: david-roses, "{}"
18:30:46 WARN PadchatRpc WXGetContact cannot get user_name, id: lijingzhao, "{}"
18:30:46 WARN PadchatRpc WXGetContact cannot get user_name, id: haibin8986, "{}"
18:30:46 WARN PadchatRpc WXGetContact cannot get user_name, id: wxid_5476664767912, "{}"
18:30:46 WARN PadchatRpc WXGetContact cannot get user_name, id: tangxiaowei_1982, "{}"
```

**Comment by windmemory** [comment]
Will fix this issue in wechaty-puppet-padchat, move this issue to https://github.com/lijiarui/wechaty-puppet-padchat/issues/81 and close here.

**Comment by zixia** [comment]
Awesome, thanks for cleaning this.
