### ISSUE TITLE
Question about how Alpha version works

### ISSUE THREAD

**Issue by xxxxlr** [Chatie/wechaty#1398]
Question before get wechaty Alpha version tested:

From what I have talked to the ipad-chaty repo chat room, it seems the remote url will act like some sort of agent, and therefore does it mean a third party will see all wechat or even control it? 
I am not saying it will but just want to make sure I understand it before I use it. :)
Or can you point me some documentation about how the communication works? 

Thanks,
Ran

**Comment by zixia** [comment]
> it seems the remote url will act like some sort of agent, and therefore does it mean a third party will see all wechat or even control it?

Yes, your understanding is absolutely right.

The PuppetPadchat needs a Padchat Protocol Agent Server that helps it to communicate with the Tencent Wechat Server. What you do with Wechaty API will go through that server and it will do all the magic for you, including "see all wechat or even control it".

If you want to learn more about how the communication works, I'd like to suggest you to read the `PadchatRpc` module, like from the following piece of code:

https://github.com/Chatie/wechaty/blob/1de61f430f381905fc486750be6ac23c429b4eed/src/puppet-padchat/padchat-rpc.ts#L610-L612

Related to: #1296

**Comment by zixia** [comment]
@xxxxlr Could you please close this issue if your question had been answered?

**Comment by xxxxlr** [comment]
Thanks for your explanation! Will do.
