### ISSUE TITLE
How to automatically add as a friend without verification？

### ISSUE THREAD

**Issue by 3014zhangshuo** [Chatie/wechaty#1412]
WeChat robot account settings -> Privacy -> Closed Add me as friend is need verification
![wechatimg3](https://user-images.githubusercontent.com/22270287/42021120-5a05fa36-7aec-11e8-8234-c6e618f6afd8.jpeg)
Adding WeChat bot after setting this way does not need to send friend request.
Then I use the scan code method to add a robot account friend, successfully added as a friend. But,the robot account did not add me as a friend.
![wechatimg4](https://user-images.githubusercontent.com/22270287/42021427-1f12145e-7aed-11e8-94f2-db91ac15608a.jpeg)
I hope that in this setting case, the robot account can also add me as a friend. Here is the code I tried
```
.on('friend', async (contact, request) => {
  console.log(request) # => get nil

  contact.say('hello') # will not be received

  try {
    if (request) {
      request.accept()
      contact.say('hello')
    }
  } catch (e) {
    console.log(e.message)
  }
})
```
I want to skip `request.hello` verification and automatically add friends. Is there a way to achieve this demand?

wechaty version 0.14

**Comment by zixia** [comment]
Had you tried `FriendRequest.send(contact)` to see if you could be able to add that contact immediately?

Because that contact had already added you, so I guess it should work.

**Comment by zixia** [comment]
@3014zhangshuo Could you please confirm that whether my suggestion could resolve your problem? Thanks.

**Comment by 3014zhangshuo** [comment]
Thanks，but not work.

**Comment by zixia** [comment]
Sad to hear that, you can leave this issue open for tracking in the future.
