### ISSUE TITLE
PuppetPadchat: The contact.star() doesn't work

### ISSUE THREAD

**Issue by kis87988** [Chatie/wechaty#1413]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China) U.S.
2. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using? None

Run in docker 
Wechaty v0.17.46 with Node.js v10.5.0

```js
.on('message', async msg => {
  const contact = msg.from()
  const content: string = msg.text()
  const room: Room | null = msg.room()
  if (msg.self() || !contact)
  {
    return // skip self
  }
  const contact_star = await contact.star()
  console.log("contact star:", contact_star) //output null
})
```

### Expected behavior
Boolean

### Actual behavior
Null
</details>

**Comment by lijiarui** [comment]
Thanks!

And this feature hasn't been implemented by wechaty-padchat yet...

**Comment by zixia** [comment]
@lijiarui Please move this conversation to the puppet-padchat repo, thanks.

**Comment by lijiarui** [comment]
Ok
