### ISSUE TITLE
Maybe we shouldn't syncContactsAndRooms per 3 hours

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#1414]
see here: 
- https://github.com/Chatie/wechaty/pull/1402
- https://github.com/Chatie/wechaty/pull/1407

I'm trying to syncContactAndRooms every 3 hours yesterday, but today I got the following result...

All bots cannot receive the user push message and always get the following result... I'm not sure the exact reason, but maybe we shouldn't sync Contact and Room too frequently...

```shell
10:56:42 WARN PuppetPadchatManager syncContactsAndRooms() cannot get array result: {"message":"不支持的请求","status":-19}
10:56:42 SILL PuppetPadchatManager syncContactsAndRooms() while() syncing WXSyncContact ...
10:56:42 SILL PadchatRpc rpcCall(WXSyncContact, [])
10:56:42 SILL PadchatRpc initHeartbeat() throttleQueue.subscribe(ws.on(message))
10:56:42 SILL PuppetPadchat startWatchdog() padchatManager.on(heartbeat)
10:56:42 SILL PuppetPadchat startWatchdog() watchdog.on(feed, food={type=undefined, data=ws.on(message)})
10:56:52 WARN PuppetPadchatManager syncContactsAndRooms() cannot get array result: {"message":"不支持的请求","status":-19}
10:56:52 SILL PuppetPadchatManager syncContactsAndRooms() while() syncing WXSyncContact ...
10:56:52 SILL PadchatRpc rpcCall(WXSyncContact, [])
10:56:52 SILL PadchatRpc initHeartbeat() throttleQueue.subscribe(ws.on(message))
10:56:52 SILL PuppetPadchat startWatchdog() padchatManager.on(heartbeat)
10:56:52 SILL PuppetPadchat startWatchdog() watchdog.on(feed, food={type=undefined, data=ws.on(message)})
10:57:02 WARN PuppetPadchatManager syncContactsAndRooms() cannot get array result: {"message":"不支持的请求","status":-19}
10:57:02 SILL PuppetPadchatManager syncContactsAndRooms() while() syncing WXSyncContact ...
10:57:02 SILL PadchatRpc rpcCall(WXSyncContact, [])
10:57:02 SILL PadchatRpc initHeartbeat() throttleQueue.subscribe(ws.on(message))
10:57:02 SILL PuppetPadchat startWatchdog() padchatManager.on(heartbeat)
10:57:02 SILL PuppetPadchat startWatchdog() watchdog.on(feed, food={type=undefined, data=ws.on(message)})
10:57:12 WARN PuppetPadchatManager syncContactsAndRooms() cannot get array result: {"message":"不支持的请求","status":-19}
10:57:12 SILL PuppetPadchatManager syncContactsAndRooms() while() syncing WXSyncContact ...
10:57:12 SILL PadchatRpc rpcCall(WXSyncContact, [])
10:57:12 SILL PadchatRpc initHeartbeat() throttleQueue.subscribe(ws.on(message))
10:57:12 SILL PuppetPadchat startWatchdog() padchatManager.on(heartbeat)
10:57:12 SILL PuppetPadchat startWatchdog() watchdog.on(feed, food={type=undefined, data=ws.on(message)})
10:57:22 WARN PuppetPadchatManager syncContactsAndRooms() cannot get array result: {"message":"不支持的请求","status":-19}
10:57:22 SILL PuppetPadchatManager syncContactsAndRooms() while() syncing WXSyncContact ...
```

- When I change the code from server to my local laptop, all works well...
- When I restart docker on the server, all works well...

**Comment by lijiarui** [comment]
no, just the moment when I restart the code.

**Comment by suntong** [comment]
OK. 

I second that we shouldn't syncContactsAndRooms/Pulling every 3 hours, especially it is raising red flag to the WX server, which we should avoid as much as possible. 

Many people might live even without pulling at all, like me.

**Comment by windmemory** [comment]
The sync logic has been removed since `wechaty-puppet-padchat` 0.4.4. This issue can be closed.

**Comment by suntong** [comment]
I was using the latest `wechaty-puppet-padchat` last night, with the simple wechaty-getting-started example, but saw all of sudden a huge list of "_cannot lookup wechat id_" (or something similar) dumped to the terminal. 

Whatever that logic is, that need to be removed as well.

**Comment by windmemory** [comment]
@suntong We are supposed to discuss about the sync issue, so let's move to [wechaty-puppet-padchat](https://github.com/lijiarui/wechaty-puppet-padchat)

Please open an issue in `wechaty-puppet-padchat`, we will track the issue there :)

**Comment by suntong** [comment]
Well, I suspect I was talking about the same thing, now I can prove it:

    20:19:13 WARN PuppetPadchatManager syncContactsAndRooms() cannot get array result: {"message":"不支持的请求","status":-19}

It happened just now, and again, I am using the latest `PuppetPadchat`.

**Comment by zixia** [comment]
@lijiarui Can we close this issue for now?

**Comment by zixia** [comment]
ping @lijiarui

**Comment by lijiarui** [comment]
done
