### ISSUE TITLE
Web version of WeChat looks like  closed group interface

### ISSUE THREAD

**Issue by Zhou-Bill** [Chatie/wechaty#1441]
i use v0.14.10 web wechaty , room.add(contact) isn't work,  and i login in web wechat in chrome , create group or join group button is display none....

someone has same issues?

**Comment by lijiarui** [comment]
Yes, you are right, it is closed... Then web wechat cannot invite people in the room automatically.

**Comment by zixia** [comment]
That's a pity... I think we should write a blog to announce that.

**Comment by zixia** [comment]
@Zhou-Bill Could you please to close this issue because your question was answered?
