### ISSUE TITLE
sending a custom emotic led to an error on the server

### ISSUE THREAD

**Issue by zhaokefei** [Chatie/wechaty#1483]
**When I send a custom emoticon, the server prompts the following error.**

![3911531556551_ pic](https://user-images.githubusercontent.com/16509241/42730104-ba5c8636-881e-11e8-831f-0a22ac407062.jpg)

![3901531556544_ pic_hd](https://user-images.githubusercontent.com/16509241/42730102-b8904e50-881e-11e8-85c7-50088dcb8167.jpg)

**Comment by zixia** [comment]
It seems this issue it's caused by you are using a not implemented feature from PadChat.

You can file an issue at PadChat repository at https://github.com/lijiarui/wechaty-puppet-padchat/issues

**Comment by windmemory** [comment]
@zhaokefei Can you try to get an reproduce with the latest `wechaty` and `wechaty-puppet-padchat`? I tested with the case you provided above, and it seems fine. 

And BTW, I created another issue in `wechaty-puppet-padchat` repository.

**Comment by zixia** [comment]
Moved to https://github.com/lijiarui/wechaty-puppet-padchat/issues/149
