### ISSUE TITLE
Pre-install all official supported Puppets when build docker image

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#1493]
According to #1478, it will be more convenience for the docker user if we can pre-install all the puppets.

**Comment by solarhell** [comment]
Maybe add `docker -e PUPPETEER_DOWNLOAD_HOST=https://storage.googleapis.com.cnpmjs.org` guide for china developer helps.

**Comment by solarhell** [comment]
since we can't put chromium binary to image

**Comment by zixia** [comment]
Current the latest docker image (v0.19.114 or above) should be pre-installed all the puppets, including:

1.  wechaty-puppet-ioscat
1. wechaty-puppet-puppeteer
1. wechaty-puppet-padchat
1. wechaty-puppet-wechat4u

Please let me know if anyone find there's any problems with the docker run.
