### ISSUE TITLE
最新版本的docker下载不能用

### ISSUE THREAD

**Issue by hly990** [Chatie/wechaty#1509]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)
中国
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?
青云
### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 

npm ERR! path /docker-images/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/docker-images/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-27T08_10_57_616Z-debug.log

### Expected behavior
1.执行docker run -ti --rm --volume="$(pwd)":/bot zixia/wechaty mybot.js
2.log里面会出现很多警告：比如：
npm: 
> node-expat@2.3.16 install /wechaty/node_modules/node-expat
> node-gyp rebuild

npm: make: Entering directory '/wechaty/node_modules/node-expat/build'

npm:   CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o

npm: ../deps/libexpat/lib/xmlparse.c: In function ‘gather_time_entropy’:

npm: ../deps/libexpat/lib/xmlparse.c:780:7: warning: variable ‘gettimeofday_res’ set but not used [-Wunused-but-set-variable]
   int gettimeofday_res;
       ^~~~~~~~~~~~~~~~
3.执行到node install.js就卡住不动了

### Steps to reproduce the behavior (and fixes, if any)

> If you know c9 IDE, please goto https://ide.c9.io/zixia/wechaty-bug-reproducer to apply a write access for the workspace so that you can put your reproduceable code over there. If you did that, your issue will be classified with HIGH priority and we will deal with the high priority issues first.

### Full Output Logs

```shell
$ WECHATY_LOG=silly npm run ts-node mybot.ts

# or 

$ WECHATY_LOG=silly node dist/mybot.js
```

<details>
<summary>
Show Logs
</summary>

### Paste the full output logs here with `WECHATY_LOG=silly` set 

```shell
# PASTE FULL LOG OUTPUT AT HERE:



```
</details>

**Comment by zixia** [comment]
Merge to #1493
