### ISSUE TITLE
calling await bot.stop() can't stop the bot

### ISSUE THREAD

**Issue by BetaSu** [Chatie/wechaty#1519]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?

### Expected behavior

stop the bot and delete profile file.

### Actual behavior
still can receive new msg
![image](https://user-images.githubusercontent.com/15828041/43500549-bf9740c4-9583-11e8-9c5a-7038913000e5.png)

### Steps to reproduce the behavior (and fixes, if any)

> If you know c9 IDE, please goto https://ide.c9.io/zixia/wechaty-bug-reproducer to apply a write access for the workspace so that you can put your reproduceable code over there. If you did that, your issue will be classified with HIGH priority and we will deal with the high priority issues first.

### Full Output Logs

```shell
$ WECHATY_LOG=silly npm run ts-node mybot.ts

# or 

$ WECHATY_LOG=silly node dist/mybot.js
```

<details>
<summary>
Show Logs
</summary>

### Paste the full output logs here with `WECHATY_LOG=silly` set 

```shell
# PASTE FULL LOG OUTPUT AT HERE:



```
</details>

**Comment by zixia** [comment]
Please **Paste the full output logs in text format here with WECHATY_LOG=silly** or we cannot help any.

**Comment by zixia** [comment]
@BetaSu had you solved your problem from this issue?
