### ISSUE TITLE
Puppet Padchat Not Supported Attachment File Type in Message.

### ISSUE THREAD

**Issue by JesseWeb** [Chatie/wechaty#1524]
i really hope we can support more file types,then i can use this lib to make a file center even if server in intranet.

**Comment by zixia** [comment]
You can use `wechaty-puppet-puppeteer` to download attachments.

`wechaty-puppet-padchat` is not supported download attachments yet, you can vote it up at here: <https://github.com/lijiarui/wechaty-puppet-padchat/issues/101>

**Comment by JesseWeb** [comment]
do we have some documents for "wechaty-puppet-puppeteer"? or this puppet used in the same way as "wechat4u"

**Comment by zixia** [comment]
Yes, you are right, all puppet will be used in the same way.

You do not need the specific document from the `wechaty-puppet-puppeteer`, but you only need to use Wechaty, with `WECHATY_PUPPET=wechaty-puppet-puppeteer` environment variable set.

See the wechaty-puppet-puppeteer source code at: <https://github.com/Chatie/wechaty-puppet-puppeteer>

**Comment by zixia** [comment]
Merge to https://github.com/lijiarui/wechaty-puppet-padchat/issues/101
