### ISSUE TITLE
New Puppet: Ioscat (iPhone Wechat App Hook)

### ISSUE THREAD

**Issue by huan** [Chatie/wechaty#1528]
- Puppet Repository: <https://github.com/linyimin-bupt/wechaty-puppet-ioscat>
- Usage Wiki: <https://github.com/linyimin-bupt/wechaty-puppet-ioscat/wiki/PuppetIoscat-usage>
- Alpha Tester Application: #1530 

### See Also

- Puppet List: #1167

**Comment by lijiarui** [comment]
see #1530
