### ISSUE TITLE
feat: add receive and send link

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#1539]
Moved from #1538 , author: @windmemory 

This is a prototype of dealing with link message. 

My proposal design here is adding another field in the message, which is `linkPayload`, and store the content inside it. And when user want to send link message, then can `say` the `linkPayload`, then `wechaty` will send a link message. 

<img width="312" alt="link" src="https://user-images.githubusercontent.com/6801292/43962490-65d204ac-9cea-11e8-8498-012d516850bb.png">

The structure of the `linkPayload` is below, refer to the screenshot above
```typescript
export interface LinkPayload {
  des?: string,
  thumburl?: string
  title: string,
  url: string,
}
```

The reason I didn't combine other card with link is that I found different type of card has different properties, if we put them all together, and leave some property as optional, it might cause confusion, so I added the specific payload for link. 

In this change, I just implemented the `Message.say()`, since `Contact` or `Room`'s `say()` method are similar to each other. 

@zixia 
Please let me know your thought about this implementation. And I used Amazon cloud9 environment this time, here is the [link](https://us-west-2.console.aws.amazon.com/cloud9/ide/230d341d0a924ceda2f5d907e3bd4769)

I've sent out an invitation email to you, please use that credential to access the cloud9. Let me know if you can not access the cloud9.

**Comment by zixia** [comment]
wechaty@0.19.142 & wechaty-puppet@0.13.7 had been published and included all the changes that you need.

Please try them and let me know if there are any problems.

**Comment by windmemory** [comment]
`wechaty-puppet-padchat` `v0.9.26` has been published, the link message's send, receive and forward operations are implemented. This issue could be closed.
