### ISSUE TITLE
Want to create UrlLink with control on all properties

### ISSUE THREAD

**Issue by windmemory** [Chatie/wechaty#1541]
When create a new UrlLink, the `title`, `thumbnailurl` and `description` are immutable, and I can not assign customize properties to it. I think these properties should be assignable. 

## Use case
I would like to generate some url link message myself, and save it to db. Every time I start the bot, I want the bot to load the url message and distribute to my users. 

What do you think?

**Comment by zixia** [comment]
I think it can be easily done by the current immutable UrlLink.

I believe you can create as many UrlLink instances as you like, for example:

```ts
for (const payload of getFromDb()) {
  wechaty.say(new UrlLink(payload))
}
```

**Comment by windmemory** [comment]
Well, that works, thanks for the clarification! You are the best :)

**Comment by zixia** [comment]
Great, you are welcome
