### ISSUE TITLE
 ERR PuppetPuppeteer roomRawPayload

### ISSUE THREAD

**Issue by TbhT** [Chatie/wechaty#1547]
well ,  when i run the `node examples\advanced\room-bot.js` ,  the global event `room-join, room-leave, room-topic`, errors happens.  

it is in the project [https://github.com/Chatie/wechaty-getting-started](https://github.com/Chatie/wechaty-getting-started).

```javascript

17:28:32 ERR PuppetPuppeteer roomRawPayload(********) 
exception: no payload
(node:10140) UnhandledPromiseRejectionWarning: Error: no payload
    at PuppetPuppeteer.<anonymous> (D:\wechaty-getting-started\node_modules\_wechaty@0.19.154@wechaty\node_modules\wechaty-puppet-puppeteer\dist\src\puppet-puppeteer.js:601:23)
    at Generator.next (<anonymous>)
    at fulfilled (D:\wechaty-getting-started\node_modules\_wechaty@0.19.154@wechaty\node_modules\wechaty-puppet-puppeteer\dist\src\puppet-puppeteer.js:22:58)
(node:10140) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or by rejecting a promise which was  not handled with .catch(). (rejection id: 1)
(node:10140) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the  future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit  code.

```

**Comment by zixia** [comment]
Could you please provide the full log messages, and describe the reproduce steps of your problem? 

For example, which event will trigger this error, or every event will?

That will help much for me to understand what happened.

**Comment by TbhT** [comment]
1.  clone the [https://github.com/Chatie/wechaty-getting-started](https://github.com/Chatie/wechaty-getting-started) and upgrade the package to `0.19.154`

2.  cd the project root dir,  run `node examples/advanced/root-bot.js` and login account

3.  change one test room name , then error occurs as follows: 

```javascript
20:30:35 INFO Bot manageDingRoom()
20:30:37 WARN Bot there is no room topic ding(yet)
20:30:44 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
20:30:45 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
20:30:46 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
20:30:47 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
20:30:48 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
20:30:49 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
20:30:50 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
20:30:52 ERR PuppetPuppeteer roomRawPayload(@[this is a wechat id and ignore it ]) exception: no payload
(node:19960) UnhandledPromiseRejectionWarning: Error: no payload
    at PuppetPuppeteer.<anonymous> (D:\wechaty-getting-started\node_modules\_wechaty@0.19.154@wechaty\node_modules\wechaty-puppet-puppeteer\dist\src\puppet-puppeteer.js:601:23)
    at Generator.next (<anonymous>)
    at fulfilled (D:\wechaty-getting-started\node_modules\_wechaty@0.19.154@wechaty\node_modules\wechaty-puppet-puppeteer\dist\src\puppet-puppeteer.js:22:58)
(node:19960) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19960) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by TbhT** [comment]
I have changed the `HELPER_CONTACT_NAME` to one of friends name, But it seems like the global event such as `room-join , room-leave` , doesn't work and `room-topic` occurs error stack above. 

Can you provide some advice for the problem ?

**Comment by zixia** [comment]
@TbhT I had just run `room-bot.js` with Wechaty v0.19.154 and `wechaty-puppet-padchat`, it works without any problem:

```
11:08:51 VERB Room ready()
11:08:51 INFO Bot EVENT: room-topic - Room "Room<300人群（备用一x）>" change topic from "300人群（备用一x）" to "300人群（备用一）" by member "Contact<李卓桓>"
11:08:51 VERB Room say(room-topic - change topic from "300人群（备用一x）" to "300人群（备用一）" by member "李卓桓", )
11:08:51 VERB PuppetPadchat messageSend({"roomId":"3453262102@chatroom"}, room-topic - change topic from "300人群（备用一x）" to "300人群（备用一）" by member "李卓桓")
```

I'll try puppeteer later.

**Comment by TbhT** [comment]
aha, i will reinstall the package for a try.  First time i  install wechaty with node 10.8.0 but it cannot work in windows10, and when node version changed to  10.7.0 it works,  emmmm.

By the way , my wechat name is T_ ,  and i had add your wechat . : )

**Comment by streamDream** [comment]
@huan 
我也遇到了同样的问题(修改群名称之后, topic事件的回调报错)。所用库信息如下：
    "cookie-parser": "~1.4.3",
    "debug": "^4.1.1",
    "express": "~4.16.0",
    "http-errors": "^1.7.1",
    "log4js": "^3.0.6",
    "pug": "^2.0.3",
    "querystring": "^0.2.0",
    "request": "^2.88.0",
    "uuid": "^3.3.2",
    "wechaty-puppet-puppeteer": "^0.14.1",
    "puppeteer": "1.11.0",
    "wechaty": "^0.22.1"

日志如下：
[2019-01-10T16:20:57.509] [INFO] normal - LOG LABEL User:Contact<C~C> login at Thu Jan 10 2019 16:20:57 GMT+0800 (GMT+08:00)
16:21:08 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
16:21:09 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
16:21:10 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
16:21:11 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
16:21:12 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
16:21:13 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
16:21:14 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
16:21:15 ERR PuppetPuppeteer roomRawPayload(@bd3027051c7f539fdbd055a934ba6616) exception: no payload
(node:17968) UnhandledPromiseRejectionWarning: Error: no payload
    at PuppetPuppeteer.<anonymous> (/home/chong/Code/nodejs_wechat_robot/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:603:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/chong/Code/nodejs_wechat_robot/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:22:58)
(node:17968) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17968) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by TbhT** [comment]
I  had fixed this bug and will make a PR later .

**Comment by huan** [comment]
@TbhT Glad to hear that, and please refer to this issue in your PR, thank you very much!
