### ISSUE TITLE
wechaty-puppet-puppeteer room.del(from)踢人无效

### ISSUE THREAD

**Issue by zmrbak** [Chatie/wechaty#1558]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)
My Home
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?
My Windows 10
//---------------------------------------------------------------------
myWeixinBot.on('message', async function (msg) {
const from = msg.from()
const room = msg.room()
if (room) {
                  let result = await room.del(from);
                    if (result) {
                        console.log(`remove ${from.name()} from ${room.topic()} successfully! `)
                    } else {
                        console.log(`failed to remove ${from.name()} from ${room.topic()}! `)
                    }
}
}
//-------------------------------------------------------------------------
踢人总是失败。

**Comment by zmrbak** [comment]
Wechaty <default> start() v0.18.5

**Comment by zmrbak** [comment]
Wechaty <default> start() v0.19.161

**Comment by zmrbak** [comment]
找到原因了：微信Web版本已经取消了群中踢人、从群中加人、拉人进群。

**Comment by zmrbak** [comment]
现在Web版越来越鸡肋了，在Web版本上开发，已经没有什么价值了。

**Comment by lijiarui** [comment]
So  maybe you need to change to ipad solution :)

**Comment by zixia** [comment]
Close this issue because the question was answered.
