### ISSUE TITLE
[Feature request] Sending Stickers

### ISSUE THREAD

**Issue by dcsan** [Chatie/wechaty#156]
I searched the repo and there doesn't seem to be any specific issues except the Image/Video on #4 

It would be awesome if Wechaty could support stickers. It seems to give 
`WARN MediaMessage stream() exception: Error: protocol unknown: null`
currently on receiving.

But **Sending** would be the major thing to support. 
I guess this is quite a large task since static image sending is not supported either yet.

But one of the big differences between a 1:1 chat with a person and an official account 'bot is animated stickers... so would be a great feature addition 

related steps:
https://github.com/wechaty/wechaty/issues/4#issuecomment-266054802

⬆️  upvotes  ⬆️

![icon_006](https://cloud.githubusercontent.com/assets/514002/21441058/22a934fa-c8d1-11e6-97ff-fcbbb0489a70.gif)

**Comment by zixia** [comment]
Yes, I agree that sending sticker is a must have feature for Wechaty. 

Can you post how to reproduce `WARN MediaMessage stream() exception: Error: protocol unknown: null` here?

And for receiving stickers, you can have a try with `example/media-file-bot.ts`, it will save all the files(including stickers) to local files.

**Comment by dcsan** [comment]
The error:
I used the code from media-file-bot 
When I send a sticker to myself I got the above error
Perhaps this is with official "paid" stickers (like the one above) rather than just free .gifs. The webUI currently I don't think enables ordinary "user generated" stickers to be sent?
I will check again and confirm later.

It seems to capture incoming gifs very well.

**Comment by zixia** [comment]
It looks wechat server had denied the web image link for sticker package according to https://github.com/geeeeeeeeek/electronic-wechat/issues/2 and https://github.com/geeeeeeeeek/electronic-wechat/issues/393

**Comment by zixia** [comment]
@binsee Do you think this could be implemented based on your file upload & mediaId code?

**Comment by binsee** [comment]
The server filters the stickers message, webwx can not get.

https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxsync?sid=&skey=@&pass_ticket=
`paid` stickers json:
```json
"MsgType": 47,
"Content": "",      // is blank
```

But,a small part can be passed, such as Tusky. Can be sent, but available in small quantities.

**Comment by zixia** [comment]
It seems we have not found any good way to implement/resolve this issue.

Closed now. 

Please let me know if there's any future enhancement we could do.
