### ISSUE TITLE
Pass mention list down to puppets

### ISSUE THREAD

**Issue by windmemory** [Chatie/wechaty#1560]
I wondered why we generate the at list manually into a text, then pass it down to puppet. Why not just pass the mention id list? If there any specific reason for doing this?

https://github.com/Chatie/wechaty/blob/ae8eecd83af63032cf6a3866b561ee56ffdae9ca/src/user/message.ts#L502-L527

In iPad protocol, message send has a parameter to set the mention list, if the user mentioned is not passed in that params, the user won't get really mentioned. So I would like to know why this information is not passed down.

**Comment by zixia** [comment]
It should passed to the puppet 

The current design is because it was based on the web api before.

PR will welcome to fix this.

**Comment by windmemory** [comment]
Created PR for this change, will try to setup an cloud env to test this for you.

**Comment by windmemory** [comment]
Cloud9 env: https://us-west-2.console.aws.amazon.com/cloud9/ide/20a9743b61294a3cb10f8f70e64c7883

Was try to create env with coder, but have problem running node and npm on it, so back to AWS Cloud9 again.
