### ISSUE TITLE
bot logined, but `scan` event still.

### ISSUE THREAD

**Issue by TbhT** [Chatie/wechaty#1567]
In the local env,  it seems it is ok when logined.  But in remote server, even bot scaned the qrcode, the `scan`  event was still emitted and the `bot.logonoff()`   was  `false` .  Weird, it can received msg.

Some advice ?

**Comment by zixia** [comment]
Could you reproduce it with steps in details?

**Comment by TbhT** [comment]
well , maybe it has not relations with wechaty. I closed it .

**Comment by collinsyu** [comment]
> well , it has not relations with `wechaty`. My mistakes.

hi,how to solve this problem, i have the same problem
