### ISSUE TITLE
How can I send a hyperlink?

### ISSUE THREAD

**Issue by fidonium** [Chatie/wechaty#1568]
In wechat, we can easily send a hyperlink by input this HTML code.
`<a href="https://github.com">Hyperlink</a>`
Send the message and it would be like this.
[Hyperlink](https://github.com/)

But, when I tried to write this code in my robot:
`contact.say('<a href="https://github.com">Hyperlink</a>');`
my friend will just receive this:
`<a href=" ">Hyperlink</a >`

Could you give me some advice?

**Comment by lijiarui** [comment]
> In wechat, we can easily send a hyperlink by input this HTML code.
<a href="https://github.com">Hyperlink</a>
Send the message and it would be like this.
Hyperlink

Have you tried if you send this `<a href="https://github.com">Hyperlink</a>` on your phone, what it will happen?

I just tried, if I send `<a href="https://github.com">Hyperlink</a>` on my phone manually, my friend will just receive this:
<a href=" ">Hyperlink</a >

**Comment by fidonium** [comment]
I tried on my Android phone, my phone will display this message as [Hyperlink](https://github.com). But, indeed, my friend will just receive `<a href=" ">Hyperlink</a >`.
I'm wondering that personal account doesn't have this feature, only official account can do this.
