### ISSUE TITLE
Closing wechaty-puppet-padchat beta test

### ISSUE THREAD

**Issue by windmemory** [Chatie/wechaty#1572]
We are closing Beta testing in wechaty-puppet-padchat.

After update wechaty-puppet-padchat to v0.16.1 or higher, we will switch to a new server. Old token will not be able to connect to the server. If you are a paid user, please contact us to get new ones. And please refer to this migration guide

Versions earlier than v0.15.5 are still connecting to old server, which will still be running for 2 more weeks, and it will be closed on 09-12-2018. If you are running production service with old version, please prepare to do the migration.

**Comment by zixia** [comment]
Added the puppet-padchat token for unit testing in the travis.yaml after encrypted.

**Comment by windmemory** [comment]
@zixia Seems like travis doesn't like the encrypted token you just added :P

Could you please take a look at the config? 

Many thanks.

**Comment by zixia** [comment]
v0.22.1 had just been published.

**Comment by windmemory** [comment]
Thanks!
