### ISSUE TITLE
Refresh contact self when updating self name or signature

### ISSUE THREAD

**Issue by windmemory** [Chatie/wechaty#1576]
Refer to issue: https://github.com/lijiarui/wechaty-puppet-padchat/issues/161

Currently we don't do a refresh when we update the info for `ContactSelf`. I think we should do that after the update. 

`wechaty-puppet-padchat` has updated the logic: https://github.com/lijiarui/wechaty-puppet-padchat/commit/96e2b54e6c17cdb93050268e83d3d0bf1c41f9f1

**Comment by zixia** [comment]
Thanks for the PR, merged.
