### ISSUE TITLE
Sending messages with MessageType=1 is not supported

### ISSUE THREAD

**Issue by liggege** [Chatie/wechaty#1588]
Sending messages with MessageType=1 is not supported？

**Comment by superl2080** [comment]
this also bothers me, I can't forward a type1 message too.

**Comment by superl2080** [comment]
I find a UrlLink file, but it's error to call .say(UrlLink instance), it seems should use the padChat version

**Comment by lijiarui** [comment]
Yes, urlLink only support on padChat version at this time, see https://github.com/Chatie/wechaty-puppet/wiki/Compatibility

I will close this issue due to no discussion for months, feel free to reopen this or file a new issue if you have any questions.
