### ISSUE TITLE
How to apply padchat token?

### ISSUE THREAD

**Issue by tianshunjian** [Chatie/wechaty#1591]
In [#1296](https://github.com/Chatie/wechaty/issues/1296) , @zixia says that "apply padchat token at [BotOrange.com](http://www.botorange.com/)". But there is only the introduction of "小桔机器人".

**Comment by zixia** [comment]
Move to https://github.com/lijiarui/wechaty-puppet-padchat/issues/178

**Comment by lijiarui** [comment]
Anyone who want apply padchat token, please scan the following qrcode to contact the botorange:

![image](https://user-images.githubusercontent.com/6419514/45479213-6f88e080-b778-11e8-87f5-b69e8e4bae11.png)
