### ISSUE TITLE
docker image size is too large

### ISSUE THREAD

**Issue by lampda** [Chatie/wechaty#1603]
docker size is tooooo large.
can you make it smaller?

![image](https://user-images.githubusercontent.com/5571922/45922148-d041b700-bef6-11e8-8c72-4a09f0a5f006.png)

**Comment by huan** [comment]
Wechaty docker image is based on the Ubuntu standard version and it also pre-installed all the puppets and the related NPM modules, the compressed size is arount 400~500MB.

It is possible to reduce the size, but it will cause the cost of the maintainment to be high.

So I'd like to keep the things simple: use the standard base image and install everything for easy maintain and use.

If you need a smaller image, please feel free to write a better Dockerfile by yourself.

Good luck!
