### ISSUE TITLE
room mention contact should using roomAlias

### ISSUE THREAD

**Issue by kis87988** [Chatie/wechaty#1604]
Purpose:
For now, 
Our room.say(content,contact) will call contact name, but if contact has room alias, it should do room alias. 
the order should be roomAlias > name. If the contact not set roomAlias, it would be name.
Is this a good idea? if so, I can do this PR

**Comment by zixia** [comment]
Yes, the idea is the right direction that we should go.

PR is welcome.

**Comment by zixia** [comment]
PR merged.

Thanks for your contribution!

**Comment by kis87988** [comment]
I see! That is why. 
Thank you. I have learned a lesson 👍

**Comment by zixia** [comment]
We had added an additional check for this special case: we do not allow to use promise as boolean anymore.

```
ERROR: /Users/zixia/chatie/wechaty/src/user/room.ts[437, 52]: Promises should be awaited when used in boolean expressions
```

See: https://github.com/Microsoft/tslint-microsoft-contrib/issues/174#issuecomment-362366666
