### ISSUE TITLE
the room.add function can't work

### ISSUE THREAD

**Issue by jimmywangzhiping** [Chatie/wechaty#1606]
0. Report Issue Guide

1. Expected behavior

**Question: What behavior do you expect?**

Answer: I need new friend add a room

2. Actual behavior

**Question: What actual behavior did you experience?**

Answer: the Room.add function doesn't work, and the response is undefined.

3. Steps to reproduce your problem (and fixes, if any)

The admin logins successfully, new friend contact well and the message function has correct response.

**Question: What're the reproducible steps for us to see your problem?**

Answer: The function of Room.add response is undefined. 

 4. Full Output Logs

<details>
<summary>
Contact<Jimmy.wang> login
17:53:20 WARN Message content() DEPRECATED. use text() instead.
Contact: 况颜 Content:room
17:53:20 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
17:53:20 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
keyroom is Room {
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  id:
   '@@29419a4fa1a4ebfb5a009d280c9e0b205cf16c84e3c2dd57747bea97473fca95',
  payload:
   { id:
      '@@29419a4fa1a4ebfb5a009d280c9e0b205cf16c84e3c2dd57747bea97473fca95',
     memberIdList:
      [ '@51241b3f330715626a98f80ca6617962173a3e220e9f82a22b551c25bc159401',
        '@e94a35d378ad8c22a0456c1adf64993288fee5fe771c540cba926b4f9ca79c3f',
        '@1d1967a33e5371bec268b708410fa946d0863d6f877570a405b28d5d093b9232' ],
     topic: 'test' },
  [Symbol(name)]: 'Room',
  [Symbol(counter)]: 5 }
contact=== Contact {
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  id:
   '@01d0728b29b8961e1794d5010b8e4858d3154601428a28331f37ac69bc28d65e',
  payload:
   { avatar:
      '/cgi-bin/mmwebwx-bin/webwxgeticon?seq=665417363&username=@01d0728b29b8961e1794d5010b8e4858d3154601428a28331f37ac69bc28d65e&skey=@crypt_570e4d07_bd72dea77fd4feb27bed9d81460fd1e9',
     friend: true,
     star: false,
     address: '',
     alias: '范宏伟',
     city: 'Pudong New District',
     gender: 1,
     id:
      '@01d0728b29b8961e1794d5010b8e4858d3154601428a28331f37ac69bc28d65e',
     name: '况颜',
     province: 'Shanghai',
     signature: '静默行走。',
     weixin: '',
     type: 1 },
  [Symbol(name)]: 'Contact',
  [Symbol(counter)]: 3 }
keyroom add function Result is undefined
17:53:23 WARN Message content() DEPRECATED. use text() instead.
Room:[object Promise]  Contact:Jimmy.wang  Content: @况颜 welcome
</summary>

```shell


Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:
Admin login successfully and  can connect the admin   
```
</details>

**Comment by jimmywangzhiping** [comment]
the wechaty version is 0.22.4
the puppet is wechaty-puppet-puppeteer

**Comment by zixia** [comment]
wechaty-puppet-puppeteer is no longer supporting that feature according to the Tencent API change.

Learn more about the limitations of each Puppet Provider at: https://github.com/Chatie/wechaty-puppet/wiki/Compatibility
