### ISSUE TITLE
room.on('join',function(room, inviteeList, inviter)), can not get the inviteeList i.e. the new member

### ISSUE THREAD

**Issue by muxiaoshan** [Chatie/wechaty#1613]
### 0. Report Issue Guide

0. Please search in the issue first, and make sure your problem had not been reported before.
1. If your issue is related to _wechaty-puppet-padchat_, please report the issue at <https://github.com/lijiarui/wechaty-puppet-padchat/issues/new>
2. If your issue is related to _wechaty-puppet-puppeteer_, please report the issue at <https://github.com/Chatie/wechaty-puppet-puppeteer/issues/new>
3. If your issue is DIRECT related to Wechaty, then please follow the below template and make sure you fill it as required in detail.

### 1. Expected behavior

**Question: What behavior do you expect?**

Answer: I want detect the new member who join the room

### 2. Actual behavior

**Question: What actual behavior did you experience?**

Answer: room.on('join',function(room, inviteeList, inviter)), can not get the inviteeList

### 3. Steps to reproduce your problem (and fixes, if any)

This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

**Question: What're the reproducible steps for us to see your problem?**

Answer: My code like the follows

async function onLogin (user) {
  console.log(`${user.name()} login`)
  var roomTopic = '增长黑客002'
  const room1 = await bot.Room.find({topic: roomTopic})
  console.log(`monitor ${room1} topic is ${roomTopic}`)
  if (room1) {
    room1.on('join', async (room, inviteeList, inviter) => {
        console.log(`Room ${roomTopic} got new member ${inviteeList}, invited by ${inviter}`)
    })
  }
}

But I got this

Message#Text(👥Room<增长黑客002>🗣Contact<增长黑客002>👤Contact<冰河时代>)<"山的那边"邀请"鲜花:-)若水"加入了群聊>
**Room 增长黑客002 got new member Contact<山的那边>, invited by undefined**

I can not get the new member  鲜花:-)若水

### 4. Full Output Logs

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

**Comment by lijiarui** [comment]
### Need More Information

In order to help us to find the problem out, could you provide all the detail information about the issue. Please make add add the full log, and the more important: **provide the steps to reproduce the problem**.

Thanks! :)
