### ISSUE TITLE
发送图片没有任何反应

### ISSUE THREAD

**Issue by bryonliu** [Chatie/wechaty#1618]
场景：使用 https://github.com/Chatie/wechaty-getting-started 脚本中的es6的脚本，添加如下代码
```
   async function onMessage(msg) {

  if (/^ding$/i.test(msg.text())) {
    console.log("ding text")
    const fileBox = FileBox.fromUrl('https://chatie.io/wechaty/images/bot-qr-code.png')
    console.log(fileBox.metadata)
    await msg.say(fileBox)
    await msg.say('dingdingding')
  }

  console.log(msg.toString())

}
```
问题 ：  await msg.say(fileBox) 这一行代码没有起作用，也没有任何报错信息

**Comment by zixia** [comment]
Have you tried this one: <https://github.com/Chatie/wechaty-getting-started/blob/master/examples/basic/ding-dong-bot.js> ?

**Comment by bryonliu** [comment]
> Have you tried this one: https://github.com/Chatie/wechaty-getting-started/blob/master/examples/basic/ding-dong-bot.js ?

This demo is working , but I can't find why and which's difference between
them.

**Comment by kis87988** [comment]
@bryonliu 
maybe you have to post more detail.

**Comment by lijiarui** [comment]
Sometimes, if the picture is too big, it may be stuck. You can also compress the image and have a try.

**Comment by secreter** [comment]
(node:38) UnhandledPromiseRejectionWarning: Error: unknown msg: FileBox#Url<reply.jpg>
    at AnotherOriginalClass.<anonymous> (/wechaty/dist/src/user/message.js:388:23)
    at Generator.next (<anonymous>)
    at /wechaty/dist/src/user/message.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/wechaty/dist/src/user/message.js:3:12)
    at AnotherOriginalClass.say (/wechaty/dist/src/user/message.js:345:16)
    at Object.onText (/bot/src/lib/common.js:50:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:38) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

npm 安装方式可以正常返回图片；在服务器上用docker onbuild 就失败

**Comment by henrycpp** [comment]
> Have you tried this one: https://github.com/Chatie/wechaty-getting-started/blob/master/examples/basic/ding-dong-bot.js ?

demo现在也不能发送图片了，是微信服务端做了过滤了吗？

**Comment by henrycpp** [comment]
大家有遇到不能发送图片的问题吗？

**Comment by yuqingc** [comment]
我也不能发图了，前几天还是可以的。但是 say 函数是可以返回的，没有报错。@huan

**Comment by runME** [comment]
+1,也是前几天还行,现在不行了 @huan

**Comment by huan** [comment]
Which puppet are you using?

I guess you are using the [wechaty-puppet-puppeteer](https://github.com/Chatie/wechaty-puppet-puppeteer)?

**Comment by yuqingc** [comment]
我么用的 puppet-puppteer 版本的
@huan 是不是微信关闭了网页版原来的接口了？

**Comment by caffreycc** [comment]
@huan 
Puppet can not send Image now.
Do you mind showing some detail about this issues?
1、wechaty version: 0.27.3
2、OS： CentOs 7.x
3、[wechaty-puppet-puppeteer](https://github.com/Chatie/wechaty-puppet-puppeteer)

**Comment by huan** [comment]
It seems that there's many case that can not send image via the puppeteer puppet.

Could there anyone can check whether the web version is WeChat could be able to send image files for now?

If it could, then there's must some bug in our property.

If it could not, then that means we can not do anything to fix it except changing to other puppets like padpro or iosbird.

**Comment by yuqingc** [comment]
> It seems that there's many case that can not send image via the puppeteer puppet.
> 
> Could there anyone can check whether the web version is WeChat could be able to send image files for now?
> 
> If it could, then there's must some bug in our property.
> 
> If it could not, then that means we can not do anything to fix it except changing to other puppets like padpro or iosbird.

网页版是可以发的 @huan

**Comment by caffreycc** [comment]
Wechat web version can send Image now.
Test-time: 2019-05-14 14:27

**Comment by jh11200** [comment]
版本：
wechaty-puppet@0.15.9
wechaty@0.26.1
PuppetWechat4u & PuppetPuppeteer
问题：
我下载了这个项目：https://github.com/wechaty/wechaty-getting-started.git
测试了example/ding-dong-bot.js 图片发送，发现没有效果，并没有发送成功，也没有报错。

**Comment by wangji817** [comment]
我使用了 puppeteer@1.18.1 wechaty@0.27.6之后依然不能正常发送本地图片至好友
而项目跟目录下图片生成正常，且正常展示，缺无法发送

**Comment by huan** [comment]
Please upgrade `wechaty-puppet-puppeteer` to  v0.17.23 or later version to get rid of this bug.

See: https://github.com/Chatie/wechaty-puppet-puppeteer/pull/106
