### ISSUE TITLE
can robot join room by qrcode？

### ISSUE THREAD

**Issue by yanguoyu** [Chatie/wechaty#1622]
can robot join room by qrcode?

**Comment by kis87988** [comment]
not now, maybe future. 
but you may try to save the qrcode and try to get the link info may help

**Comment by yanguoyu** [comment]
@kis87988 robot can join room by the link?

**Comment by kis87988** [comment]
@yanguoyu not sure, but it should have some info when you scan QR code with the value. 
I will try it later as well

**Comment by yanguoyu** [comment]
thanks, i try it
