### ISSUE TITLE
Why I stuck here?

### ISSUE THREAD

**Issue by onedou** [Chatie/wechaty#1624]
![image](https://user-images.githubusercontent.com/3422640/46924098-8f4f4500-d053-11e8-9c67-ce8672fdad62.png)

**Comment by kis87988** [comment]
is the code running after couple minutes?

**Comment by yanguoyu** [comment]
国内下载puppeteer很缓慢，而且下载chromium失败。

**Comment by onedou** [comment]
It's works! when I use proxy.
![image](https://user-images.githubusercontent.com/3422640/47074060-31c22080-d22c-11e8-8cdc-7939dd83e117.png)
