### ISSUE TITLE
支持标签功能

### ISSUE THREAD

**Issue by xinbenlv** [Chatie/wechaty#1627]
希望支持

联系人
- 查看标签
- 设置标签
- 清除标签

标签列表
- 修改标签

**Comment by windmemory** [comment]
Do you have a rough design for this feature? @xinbenlv

**Comment by xinbenlv** [comment]
not yet but could not be hard, the padchat supports it but web wechat doesnt so what is your suggestion for same  Wechaty interface but some puppet doesnt support?

**Comment by windmemory** [comment]
Yep, you are right. But there are already some features only supported by padchat puppet not all puppets. So that won't be a problem. 

Actually I would like to discuss that whether we want to have a new class called `Label` or link the label to contacts and rooms as an attribute.

@zixia do you have any suggestion on this issue?

**Comment by zixia** [comment]
I'd like to suggest we add `Contact.tag()` to the Contact class.

查看标签: c.tag()
设置标签: c.tag(newTag)
清除标签: c.tag(null)

**Comment by windmemory** [comment]
How about the list of tags?

**Comment by zixia** [comment]
Should be easy by:

```ts
contactList = await bot.Contact.findAll()
tagList = await contactList.map(c => c.tags())
tagSet = new Set(...tagList)
```

**Comment by zixia** [comment]
I can not understand that the `tagList` is an ordered list, I thought it should be an unordered list?

And from the abstract perspective, Wechaty should not return the number to you, it should return the exact tag name to you because we can not grantee the number will be consistent between different puppet implementations, also the most meaningful part of the tag is the name itself?

**Comment by windmemory** [comment]
For clear tag, I am a little confuse.

Say I have a Contact that have two labels on it, `friend` and `football`, then I want to remove `friend` label from it, how to achieve that?

```typescript
const tags = contact.tag()
contact.tag(null)
tags.filter(t => t !== 'friend').map(t => contact.tag(t))
```

For the design above, I can only come up with the code above to achieve that, but not elegant I think.

**Comment by xinbenlv** [comment]
+1 to @windmemory, the `delete` method needs to identify itself. After a second thought, I think we should make it clear about what `c` in `c.tag()` is. If `c` is `Contact` class, I don't think it works.

There is a *One-to-Many* relation between Contact and Tag

I think we can do this (the Contact-level interfaces)

`typescript

class Contact {
   public addTag(tagName)
   public removeTag(tagName)
   public getTagList():string[]
}
```
and there should be WeChaty instance level interfaces


```
// I forgot exact intent
class Wechaty { 
  public getTagList():string[];
  public updateTag(oldTag, newTag); // create by setting oldTag to null, or delete by setting newTag to null
  public findByTag(tag):Contact[];
}
```

Also I mentioned there is a `number` representation and it's a `ordered list` in the PadChat implementation is because it's possible there is a out-of-sync if a user logged in the Wechaty and on their phone they update a Tag(string), so I like to discuss whether we want to find way to force sync `tagList` before updating any list. If so

```
class Wechaty {
  public updateTagList();
}
```

**Note: might need to make some function interfaces `async`. ***

**Comment by windmemory** [comment]
+1 to @xinbenlv 's design. Just one confusion, what does the `updateTag` do? I didn't get the idea of the comment, could you please explain more about it?

**Comment by windmemory** [comment]
So @huan do you agree with @xinbenlv ? I think the design that @xinbenlv came up with is great.

**Comment by xinbenlv** [comment]
I think `updateTagList();` could change to something like `refreshTagList();`

**Comment by huan** [comment]
Thanks for the discussion and the suggestion for the new API.

I'll have a look into them later and share my thoughts at here when I got time.

**Comment by huan** [comment]
Another question: what things in Wechat can have a tag? currently, I only know two of them: `Contact` & `Favorite`.

Do we need a Tag Manager to implement the tag related methods? like:

```ts
await Tag.add(contact, '损友')
await Tag.del(contact, '基友')
tagList: string[] = await Tag.list(contact)
```

**Comment by windmemory** [comment]
### A brief summary below of what we came up with along the conversation

|operation|1|2|3|
|---|---|---|---|
|add tag to contact|`c.tag(newTag)`|`c.addTag(t)`|`bot.Tag.add(c,t)`|
|get all tags for contact|`c.tag()`|`c.getTagList()`|`bot.Tag.list(c)`|
|delete tag|`c.tag(null)`|`c.removeTag(t)`|`bot.Tag.del(c,t)`|
|get all tags across bot|`bot.getTagList()`|`bot.Tag.list()`|
|search by tag|`bot.findByTag(t)`|`bot.Tag.findAll(t)`|
|refresh data|`bot.refreshTagList()`|

I will vote for 2 1 2 2 2 1
And for operation: get all tags for contact, I would prefer to use `c.tags()`

Feel free to extend the table or vote for the options :)

Let's pick the highest voted one?

**Comment by xinbenlv** [comment]
`c.tag()` sounds like a singular Tag instead of a list of Tags, how about `c.tags():string[]`

**Comment by windmemory** [comment]
I agree with you @xinbenlv so I would prefer to use `c.tags()`

**Comment by huan** [comment]
Question: what things in Wechat can have a tag? currently, I only know two of them: `Contact` & `Favorite`.

Is there other things that need to be tagged?

**Comment by xinbenlv** [comment]
@huan `c.tag(null)` does not work, needs to update to make a valid delete

**Comment by windmemory** [comment]
@huan I don't know anything else has tag other than `Contact` and `Favorite`.

**Comment by huan** [comment]
@windmemory Could you please show me the underlying Wechat Raw API of Tag operations?

I need to understand the low-level wechat API so that we can align our design with it.

**Comment by windmemory** [comment]
Haven't tested them out, I might need some time to do this, @xinbenlv is using `padchat-sdk` which has underlying support for `Tag`, he might share some knowledge on that?

@xinbenlv Could you please share some details about the underlying APIs?

**Comment by xinbenlv** [comment]
https://raw.githubusercontent.com/binsee/padchat-sdk/master/README.md


| **标签管理**       |
| 添加标签           | addLabel            |
| 删除标签           | deleteLabel         |
| 获取所有标签       | getLabelList        |
| 设置用户标签       | setLabel            |

**Comment by huan** [comment]
@xinbenlv Appreciate for letting me know this.

@windmemory Could you please show me the low-level API from your side? 

I'll be able to decide which design I prefer after I see the low-level API interfaces.

Thank you very much.

**Comment by huan** [comment]
@windmemory This topic had no activities since we last discussed it 10 months ago.

I'll assign it to you because we need you to show some low-level API from your side. Please feel free to let me know if you need any help from my side.

CC @lijiarui

**Comment by windmemory** [comment]
I tested the low-level APIs, and the modify api is not working correctly, so I haven't put the results here. 

The work on fixing the low-level API is still on going, will update here once any progress is made.

**Comment by huan** [comment]
Great to hear that we will keep this issue being updated in the future.

Thank you can much.

**Comment by windmemory** [comment]
> Thank you can much

What does this mean? Never saw this word.

**Comment by huan** [comment]
It means that I'm using the sliding input method.

Yeah, it's Typo.

**Comment by su-chang** [comment]
@huan 
Here are some Raw API and their response data.

- Raw API name : AddLabel

> bot.Tag.newTag(tag: string)

```js
{
  labelList:
    [ { LabelName: '测试标签1', LabelID: 1 }, ],
  loginer: 'xxx',
  count: 1,
  message: '',
  status: 0,
}
```

- Raw API name : GetAllLabel
> bot.Tag.tagList()
```js
{
  labelList:
   [ { LabelName: '测试标签1', LabelID: 1 },
     { LabelName: '测试标签3', LabelID: 3 },
     { LabelName: '测试标签2', LabelID: 2 } ],
  loginer: 'xxx',
  count: 3,
  message: '',
  status: 0
}
```

- Raw API name : ModifyLabel
> contact.addTag(contactId:string, tag: string)
> we can get `contactId` by contact
```js
{
  loginer: 'xxx',
  labelIds: '1,3',
  message: '',
  userName: 'Soul001001',
  status: 0
}
```

**Comment by huan** [comment]
I would like to think about the design of our Tag system as the following code demonstrating, based on all the above discussions:

```ts
class Tag {
  static get (name: string): Tag
  add(to: Contact | Favorite): Promise<void>
  del(from: Contact | Favorite): Promise<void>
}

const tag = bot.Tag.get('myTag')
await tag.add(contact)
await tag.del(contact)
```

### The design behind the code

1. if users want to modify, you only need to do a `del() then add()`, which had been demonstrated above;
1. Users need not care about "create" any tag. All they need to do is to just "get" a tag by `Tag.get()`. We create the tag automatically if it does not exist.
1. If users want to "list" all tags, all they need to do is a very simple forEach loop to save them to a array:
    ```ts
    const contactList = await bot.Contact.FindAll()
    const tagList: Tag[] = []
    contactList.forEach(c => {
        c.tags().forEach(t => {
          if (!tagList.contains(t)) {
            tagList.push(t)
          }
        }
    })
    ```

I believe the above code will be very easy to understand to the users, and it's clean and concise.

Please think about them, and let me know what you think.

Thank you very much.

**Comment by windmemory** [comment]
@huan 
The code to get the tag list is easy to understand, but we know that this piece of code will be written thousands of times by our developers if we implement the method like you describe above, because to get the list is a very common action.
So how about we add the `findAll` method to `Tag` also, which is consistent with the other class that we have, the `Contact` and `Room`. In this way, our developers could achieve this goal with only one line code:
```ts
const tagList = bot.Tag.findAll()
```

**Comment by huan** [comment]
No problem. 

Add a new method like Tag.findAll() is acceptable.

I wrote the code before for demonstrating how the under design works.

**Comment by windmemory** [comment]
So the label feature will be implemented with the `Tag` class you demonstrated above, and one more method `tags` on `Contact` class, am I right?

**Comment by huan** [comment]
Yes, that's exactly what we are talking about right now.

Please go ahead and I'm good with them.

**Comment by huan** [comment]
Merge to #1856
