### ISSUE TITLE
New Puppet - wechaty-puppet-padpro

### ISSUE THREAD

**Issue by windmemory** [Chatie/wechaty#1629]
Hi @zixia ,

Here is a new puppet `wechaty-puppet-padpro`. This puppet is also implemented with iPad protocol, but different protocol service. Could you please add this puppet to the supported puppet list?

Here is the npm page: https://www.npmjs.com/package/wechaty-puppet-padpro

Let me know if any more detail information you need to know for this issue.

**Comment by windmemory** [comment]
Here is the github link: https://github.com/botorange/wechaty-puppet-padpro

**Comment by zixia** [comment]
It's great to hear that you had created this new puppet, and best wishes to it!
