### ISSUE TITLE
在docker容器中，npm install wechaty，运行mybot报错：Failed to launch chrome!

### ISSUE THREAD

**Issue by MalavitaC** [Chatie/wechaty#1636]
`root@1111f6b894f:/data# node myBot.js 
11:31:16 INFO Wechaty <default> start() v0.22.4 is starting...
11:31:16 ERR PuppetPuppeteerBridge start() exception: Error: Failed to launch chrome!
/node_modules/_wechaty@0.22.4@wechaty/node_modules/puppeteer/.local-chromium/linux-599821/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory`

**Comment by zixia** [comment]
You can use `zixia/wechaty` as your docker base image to fix this.

**Comment by MalavitaC** [comment]
The problem has been solved.
Look:   [https://github.com/Chatie/wechaty/issues/48](url)

**Comment by zixia** [comment]
Good to hear that!
