### ISSUE TITLE
请问， 怎么让机器人通过手机号添加好友

### ISSUE THREAD

**Issue by Free-loops** [Chatie/wechaty#1639]
Is it possible to search tel(手机号) to add a friend?

**Comment by ytldsimage** [comment]
目前WebAPI 不可能，或者模拟器，或者Android实机，或者appium（也是实机）

**Comment by Free-loops** [comment]
> 目前WebAPI 不可能，或者模拟器，或者Android实机，或者appium（也是实机）

好的 谢谢
