### ISSUE TITLE
Upgrade wechaty-puppet-padchat stable version

### ISSUE THREAD

**Issue by windmemory** [Chatie/wechaty#1642]
`wechaty-puppet-padchat` minor version 0.17 has been published for a while, and some fixes are pushed into this version. `v0.18.1` just got published, which we think should be a stable version for people to use. So please update the `wechaty-puppet-padchat` version in `puppet-config` to `v0.18.1`

**Comment by zixia** [comment]
Merged.

**Comment by windmemory** [comment]
Closed :)
