### ISSUE TITLE
About wxid or chatroomID

### ISSUE THREAD

**Issue by Fnckerpoi** [Chatie/wechaty#1644]
请问如果我想要确保群和群用户改昵称（改名）也能准确识别同一个人，能获取到wxid和群ID么

**Comment by lijiarui** [comment]
网页版本没有唯一的id
ipad 版本有唯一的id

相关issue：
- https://github.com/Chatie/wechaty/issues/90
- https://github.com/Chatie/wechaty/issues/1276
- https://github.com/Chatie/wechaty/issues/133
- https://github.com/Chatie/wechaty/issues/1307

相关文档：
https://docs.chatie.io/wechaty/puppet#3-wechaty-puppet-compatibility

**Comment by zixia** [comment]
@lijiarui Please add a note to denote which issue it duplicate to. Thanks.

**Comment by lijiarui** [comment]
@zixia As I list above, #90 #1276 #133 #1307  Whether can we get unique wxid or chatroom id.

**Comment by zixia** [comment]
The issue that duplicated to should be kept as simple as only one, instead of many.

**Comment by lijiarui** [comment]
I see

**Comment by lijiarui** [comment]
@Fnckerpoi  没有更多问题的话，可以关掉这个issue 了 :)

**Comment by Fnckerpoi** [comment]
> @Fnckerpoi 没有更多问题的话，可以关掉这个问题了:)

ok

**Comment by llh1187** [comment]
> pad 版本有唯一的id

page not found

**Comment by su-chang** [comment]
See: https://wechaty.js.org/v/zh/puppet

**Comment by llh1187** [comment]
> See: https://wechaty.js.org/v/zh/puppet

请问下购买网页是要翻墙的吗？打不开

**Comment by llh1187** [comment]
https://token.juzi.bot/

**Comment by su-chang** [comment]
> https://token.juzi.bot/

It is deprecated, see more info here: https://github.com/wechaty/wechaty/wiki/Support-Developers
