### ISSUE TITLE
[RFC] custom id on Contact

### ISSUE THREAD

**Issue by windmemory** [Chatie/wechaty#1647]
Recently while working on `wechaty-puppet-padpro` project, I found that there is a way to get the real wechat id from underlying service. So for each contact, there will be two ids, one is wxid, which is allocated by wechat system, the other one is the use name, which is created by the user. 

I am suggesting here to have an optional `customId` field on `Contact` class. For developers who want to get the real wechat id, they could try to get the `customId` first, then fallback to the `id`, in this way, they will get the id that same as the one on wechat. 

Does this make sense?

**Comment by zixia** [comment]
There's already a `weixin` in ContactPayload, and it was designed for the real wechat id.

Please have a look into it and let me know whether it cloud fulfill your requirement.

**Comment by windmemory** [comment]
Got it, will assign that value to `weixin`.
