### ISSUE TITLE
强烈建议增加判断收到消息是否红包消息

### ISSUE THREAD

**Issue by crdsoft** [Chatie/wechaty#1652]
我们项目里需要判断收到的消息是否属于红包，如果是红包需要回复特定消息。

**Comment by lijiarui** [comment]
Which puppet are you using now?

**Comment by crdsoft** [comment]
web now。support？

**Comment by crdsoft** [comment]
那怎么办？安卓的出了吗？

**Comment by lijiarui** [comment]
If you don't have more question about this issue, please close this issue, thanks :)
