### ISSUE TITLE
How to get the wx_id when user had wx account?

### ISSUE THREAD

**Issue by xmsz** [Chatie/wechaty#1658]
### 1. Expected behavior

**Question: What behavior do you expect?**

Answer: Get wx_id from Contact.id not wx account 

### 2. Actual behavior

**Question: What actual behavior did you experience?**

Answer: When user had set the wx account (ex: test), it will return 'test'. But, I want the wx id ,not the wx account. 
Case, wx_id is unique, wx account can be changed

**Comment by lijiarui** [comment]
Question: Which puppet are you using?

> Get wx_id from Contact.id not wx account

Yes, using `Contact.id` just can get contact unique id according to the puppet, see more:  #1644 #90 #1276 #133 #1307

If you want to get weixin id, you can use `Contact.weixin()`, but this isn't supported at this time, it is coming very soon! see #1647 

- If you are using iPad version, Contact.id is unique ID of and always the same id across sessions. It means when you login again, you always get this unique id.
- If you are using Web version, Contact.id is unique id but it will change across sessions. It means when you login again, you may get a different id even it is the same user.

**Comment by xmsz** [comment]
Thanks
