### ISSUE TITLE
Errors occur sometimes when bot running

### ISSUE THREAD

**Issue by TbhT** [Chatie/wechaty#1675]
Follows are the errors , which occur during the wechat bot running : 

- `Error: Error: Protocol error (Network.deleteCookies): Target closed.`

- `Error: Failed to add page binding with name wechatyPuppetBridgeEmit: window['wechatyPuppetBridgeEmit'] already exists!`

- `Error: TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded`

- ` Error: Protocol error (Network.deleteCookies): Target closed.`

Well , the bots are running in multiprocess or the single process , and the errors not always  happen.

**Comment by huan** [comment]
It seems all the above errors are related to the `wechaty-puppet-puppeteer`.

It's better to:

1. move this issue to https://github.com/Chatie/wechaty-puppet-puppeteer/issues, and
1. find out how to reproduce it with specific minimum steps, or we can not analytics them.

Thanks for list them out, and Merry X'mas!

**Comment by TbhT** [comment]
Too :) .

Well , I will try to reproduce it but it may need more time .
