### ISSUE TITLE
登录二维码为什么不能在手机中识别？

### ISSUE THREAD

**Issue by baixiaoyu2997** [Chatie/wechaty#1682]
version:0.22.6

问题：
启动机器人后生成的qr地址 发送到手机，在微信中点击识别二维码，然后提示无法识别的二维码

期待结果：
不想用手机再扫描电脑，希望用一台手机就搞定登录问题，请问有什么更好的解决方案吗？ 感谢

**Comment by frankgo81** [comment]
![image](https://user-images.githubusercontent.com/33563058/53696311-ac1cc700-3e00-11e9-9e84-dde988da7ef7.png)
The QR code generated on terminal is NOT recognizable by your phone..because of the resolution..you need to copy and paste the generation URL on your browser and scan from there...
