### ISSUE TITLE
Why `findAll()` returns `[]` ?

### ISSUE THREAD

**Issue by daoxiaozhang** [Chatie/wechaty#1689]
### package:
"wechaty": "^0.22.6"

### code:
`const bot = new Wechaty();`
`Wechaty.instance().start();`
`// I had logined ,then i run bottom code,i cant get anything`
`const room = await bot.Contact.find({topic: 'test'})`
`-->null`
`const roomList = await bot.Room.findAll()`
`--> []`

**Comment by huan** [comment]
Could you try to do a `await bot.sleep(10 * 1000)` before `bot.Contact.find` ?

I guess you are using the default puppeteer puppet.

We will emit a `ready` event in the future, see https://github.com/Chatie/wechaty-puppet-puppeteer/issues/63

**Comment by huan** [comment]
Oh, yes, it is. 

Glad to hear that, cheers!
