### ISSUE TITLE
Document bug in README

### ISSUE THREAD

**Issue by huan** [Chatie/wechaty#1690]
README markdown format needs to be fixed:

![image](https://user-images.githubusercontent.com/1361891/50878166-4b7c9980-1410-11e9-8212-94871df16459.png)

<https://github.com/Chatie/wechaty/blob/master/README.md>

**Comment by TbhT** [comment]
I will fix these later .

**Comment by TbhT** [comment]
[here](https://github.com/Chatie/wechaty/pull/1713)  is the pr . :)

**Comment by huan** [comment]
I'll close this issue because the PR had been merged.

Thank you very much @TbhT !
