### ISSUE TITLE
生成二维码的链接访问不了

### ISSUE THREAD

**Issue by TigerBill2016** [Chatie/wechaty#1693]
### 0. Report Issue Guide

0. Please search in the issue first, and make sure your problem had not been reported before.
1. If your issue is related to _wechaty-puppet-padchat_, please report the issue at <https://github.com/lijiarui/wechaty-puppet-padchat/issues/new>
2. If your issue is related to _wechaty-puppet-puppeteer_, please report the issue at <https://github.com/Chatie/wechaty-puppet-puppeteer/issues/new>
3. If your issue is DIRECT related to Wechaty, then please follow the below template and make sure you fill it as required in detail.

### 1. Expected behavior

**Question: What behavior do you expect?**

![image](https://user-images.githubusercontent.com/19324557/51083470-e13c5f80-1755-11e9-8119-7dc0fac4b393.png)

登录机器人，需要扫码 链接生成的二维码，现在访问不了，谢谢

![image](https://user-images.githubusercontent.com/19324557/51083475-09c45980-1756-11e9-8c53-16f5b74f2fdf.png)

Answer:

### 2. Actual behavior

**Question: What actual behavior did you experience?**

Answer:

### 3. Steps to reproduce your problem (and fixes, if any)

This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

**Question: What're the reproducible steps for us to see your problem?**

Answer:

### 4. Full Output Logs

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

**Comment by lijiarui** [comment]
Please give more information:
1. Which puppet are you using
2. Please give the reproduce code.

Thanks

**Comment by blissCheng** [comment]
> Please give more information:
> 
> 1. Which puppet are you using
> 2. Please give the reproduce code.
> 
> Thanks


I have encountered this problem。

```
node v11.6.0
16:10:37 INFO PuppetManager install(wechaty-puppet-puppeteer@^0.14.1) please wait ...
npm:
> puppeteer@1.11.0 install /Users/apsun/Applications/wechatBot/node_modules/wechaty/node_modules/puppeteer
> node install.js
```

My code:

```
import { Wechaty } from 'wechaty';

const myWechat = Wechaty.instance()
  .on('scan', (qrcode, status) => {
    console.log(qrcode);
  })
  .on('login', (user) => {
    console.log(JSON.stringify(user));
  })
  .on('message', (message) => {
    console.log(message);
  })

export default myWechat;
```

the qrcode returns the result as  https://login.weixin.qq.com/l/wYt1ExXFNA== .
Actually https://login.weixin.qq.com/qrcode/wYt1ExXFNA== is a valid qrcode.

**Comment by lijiarui** [comment]
I suggest you try the example here: https://github.com/wechaty/wechaty-getting-started/blob/master/examples/starter-bot.js

**Comment by blissCheng** [comment]
> I suggest you try the example here: https://github.com/wechaty/wechaty-getting-started/blob/master/examples/starter-bot.js

Oh~~~ Thanks

**Comment by lijiarui** [comment]
You are welcome, you can close this issue if you don't have other questions ：）

**Comment by lijiarui** [comment]
It seems there isn't any questions about this issue, I will close this issue then.
