### ISSUE TITLE
小桔机器人挺好用，希望详细对比WeTools，并分享开发Roadmap，谢谢

### ISSUE THREAD

**Issue by ImHUan** [Chatie/wechaty#1712]
**Is your feature request related to a problem? Please describe.**
无关联问题

**Describe the solution you'd like**
刚用了 https://wechat.botorange.com/  挺好用的。我们正在用WeTools很久了，小桔这种不用挂机的网页端显然更加灵活。目前考虑迁移的可行性，希望能有一个详细的功能对比表格，以及独家功能的演示视频。以供参考。

**Describe alternatives you've considered**
另外，目前新版功能只有【用户信息标注、聊天、群发】，希望能了解其他旧版功能、以及接下来开发新功能的周期，看看是否能配合得上我们的业务和技术路线，以便考虑是否从WeTools方案整体迁移过来

**Additional context**
建议新建个Repo来专门展现Roadmap，和用户bug区分开来。谢谢！

[enhancement]

**Comment by lijiarui** [comment]
remove to https://github.com/botorange/xiaoju/issues/1

Thanks for your suggestion!
