### ISSUE TITLE
wechaty-puppet-padpro 获得的语音消息文件是slk格式

### ISSUE THREAD

**Issue by z372183629** [Chatie/wechaty#1720]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

通过web api获取到的语音格式是mp3类型的，pad pro获取的是slk格式，没法儿解码。请问各位有什么处理方法吗。

**Comment by libin8952** [comment]
请问你最后是怎么解决的

**Comment by z372183629** [comment]
> 请问你最后是怎么解决的

还没有去解决，只能通过服务器做转码

**Comment by libin8952** [comment]
请问具体怎么转的呢。最后转出了什么格式呢。
