### ISSUE TITLE
Recalled message design

### ISSUE THREAD

**Issue by windmemory** [Chatie/wechaty#1728]
**Is your feature request related to a problem? Please describe.**
Add new message function for recalled message

**Describe the solution you'd like**
The design would be like below
### For recalled message
* It will have a different message id from the original message
* The type for the message will be `Recall`
* There will be a new method named `recalled` to be added to the `Message` class and used to retrieve the original message

**Describe alternatives you've considered**
No alternatives :P

**Comment by huan** [comment]
Related to: https://github.com/Chatie/wechaty-puppet-puppeteer/issues/31#issuecomment-470789051

@windmemory Please feel free to connect other related issues as well.

**Comment by huan** [comment]
@windmemory Please close this issue if there's no more work needs to do on it.

**Comment by windmemory** [comment]
Close this issue since the feature is implemented. Thanks for the help @huan
