### ISSUE TITLE
How to get the sender's real wechat Id instead of weixin id (wxid) from a message?

### ISSUE THREAD

**Issue by psfr937** [Chatie/wechaty#1736]
I am using ```wechat-puppet-padchat``` for the puppet in wechaty.
 When I check James from the wechat app, it shows "james321", which is not surprising because weChat do let user change their id once. However, when James sends me a message and I use ```m.from().id``` in the Message object, it only shows for example wxid_bz4eto56p2g399. 

I can confirm wxid_bz4eto56p2g399 and "james321" represents the same person. Because no matter which one I use, when I send him a message with ```m.puppet.messageSendText```, he can get the message.  

So, I think wxid_bz4eto56p2g399 might be his old wechatId. 

I want to know which contact send me the message. So I try if old wechatId is stored in Contact object. When I try to list all my Contact with ```Contact.findAll```, unfortunately it only shows his new wechat Id "james321". 

I cannot find where his old WeChat id comes from. So, whenver I got a message, I don't know who send me the message. How might I use the old wechatId in the message object to find his corresponding new WechatID , or vice versa?

**Comment by psfr937** [comment]
similar to #1307, #1647, #1658

**Comment by psfr937** [comment]
It seems that I always get null from ```Contact.weixin``` .  Is there a way I can know the real wechat Id from the wxid shown in the Message object?

**Comment by lijiarui** [comment]
Which puppet are you using?

If you use puppeteer, it cannot get wechat ID.

If you use padpro, it can get wechat ID.

See [Wechaty Puppet Compatibility](https://docs.chatie.io/puppet#3-1-puppet-contact-api)

**Comment by psfr937** [comment]
Thanks. I have changed from Padchat puppet to Padpro puppet and it works.

**Comment by jusicorpuz** [comment]
Hi! can someone help me know how to find an old contact in Wechat? I badly need to communicate with him. I have his wxid only :(

**Comment by stinger58** [comment]
Hi did you find someone to help? I have the same problem. I used a Wechat a few different 3rd party programs to recover contacts and messages and all I could recover was their We Chat ID starting with wxid_ However, if someone out can help. Please post your contact I formation. I’m not a developer so I really some help...thanks GB

**Comment by BadgerLin** [comment]
You may find how to trace one's real WeChat ID via the way mentioned via [This Link](https://chinanudge.com/how-to-find-friends-through-wxid-how-to-add-friends-through-wxid/):

**Comment by Chapstick98** [comment]
This link doesnt work for me I am trying to find someones current id from their old wxid

**Comment by SignDawn** [comment]
The link has expired.
Are there any other links？
@BadgerLin
