### ISSUE TITLE
how to use room.memberAll（）to @ some menbers in Room, rather than one person or all members？()

### ISSUE THREAD

**Issue by Liusq-Cindy** [Chatie/wechaty#1742]
we have know than use room.memberAll([query]) ⇒ Promise.>  could find one person or all members in room , which depends on what query is. such as:
![image](https://user-images.githubusercontent.com/41781513/56284598-8268f680-6147-11e9-8ab5-f1c4534b0ae6.png)

    In my code, i use it to get someone's Contact
![image](https://user-images.githubusercontent.com/41781513/56284665-c22fde00-6147-11e9-8c63-36a386396f09.png)
    and then i use **`bot.say('messages', user)`** to @someone or allmembers
    This has be proved feasible，but how to use this method to get some members in room and aggregate them in one variable for robot to @ some members together? 
    such as @liuliu@maomao hello world
Does wechaty support simultaneous lookup of multiple members in a room?

**Comment by Liusq-Cindy** [comment]
I have found a solution , **`room.memberAll`** the person one by one, and then use `**.concat**` to link these array

**Comment by huan** [comment]
Related to: #1718

**Comment by Liusq-Cindy** [comment]
> Related to: #1718

okay，thank you

**Comment by huan** [comment]
Close this issue because I believe it had been resolved.

Please feel free to let me know if you have any other questions by leaving comments.
