### ISSUE TITLE
Could you please upgrade dependency for wechaty-puppet-puppeteer

### ISSUE THREAD

**Issue by yuqingc** [Chatie/wechaty#1758]
Ther current dependency of wechaty-puppet-puppeteer is really outdated, which has some bugs. For instance, a bug fixed by https://github.com/Chatie/wechaty-puppet-puppeteer/pull/75

wechaty-puppet-puppeteer has released its new version of 0.15.4. (I'm not sure if this version includes the pr I mentioned above) Could you please upgrade the dependency for wechaty?

Related issue: https://github.com/Chatie/wechaty/issues/1547

**Comment by huan** [comment]
The wechaty@0.25.11 will use the wechaty-puppet-puppeteer@0.16.1, which will be the latest code for you.

**Comment by huan** [comment]
@yuqingc Could you please close this issue if it had been resolved for you?

**Comment by yuqingc** [comment]
This issue is resolved.
