### ISSUE TITLE
请问可以通过c++程序，调用wechaty给某个好友发消息么？

### ISSUE THREAD

**Issue by opengpu** [Chatie/wechaty#1762]
【求助】您好，请问可以通过c++程序，调用wechaty给某个好友发消息么？

如果wechaty不行的话，请问您知道有没有其他的库或者办法可以实现这样的功能？
比如通过wxpy，或者自己逆向hook PC版微信？

多谢多谢~

**Comment by huan** [comment]
Duplicated with #1760
