### ISSUE TITLE
请问是否有识别用户发出的语音？或者将语音转文字的能力？

### ISSUE THREAD

**Issue by yangguo1122** [Chatie/wechaty#1783]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by huan** [comment]
Of course, we can.

Please refer to <https://github.com/wechaty/wechaty-getting-started/blob/master/examples/professional/speech-to-text-bot.ts>
