### ISSUE TITLE
添加用 id 寻找Room RoomQueryFilter

### ISSUE THREAD

**Issue by xinbenlv** [Chatie/wechaty#1785]
**Is your feature request related to a problem? Please describe.**

NO

**Describe the solution you'd like**

添加用 id 寻找Room RoomQueryFilter

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by xinbenlv** [comment]
这个可以用 `Room.load(id:string)`这个接口，请ignore

**Comment by huan** [comment]
I decide to implement this feature because:

1. `Room.load()` is not a public API
1. `Room.load()` can not guarantee the id is valid
1. `Room.load()` cannot throw the exception when the id is invalid

So add an `id` to the QueryFilter will be a better way to resolve the above problems.

**Comment by huan** [comment]
Using `id` as a QueryFilter key had been supported by:

1. `wechaty-puppet-puppeteer@0.17.22` or later version
1. `wechaty-puppet-padpro@unknown`: after this [PR](https://github.com/botorange/wechaty-puppet-padpro/pull/151) had been merged.
