### ISSUE TITLE
Cannot `Contact.say(imageAsFileBox)` with puppeteer

### ISSUE THREAD

**Issue by hywhuangyuwei** [Chatie/wechaty#1795]
- What is your wechaty version?
Answer: 0.26.1

- Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...)
Answer: puppeteer

- What is your wechaty-puppet-XXX（padchat/puppeteer/） version?
Answer: 0.16.1

- What is your node version? (run `node --version`)
Answer: 11.13.0

- What os are you using
Answer: Red Hat Enterprise Linux Server release 7.6 (Maipo)

## 2. Describe the bug
Give a clear and concise description of what the bug is.
Contact.say(imageAsFileBox) didn't work but Contact.say(text) works perfectly

## 3. To Reproduce
This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

const somebody = await bot.Contact.find({ name: someone })
await somebody.say("Hi") //works perfectly here
const fileBox = FileBox.fromFile(someValidPath)
console.log(fileBox)
/*
FileBox {
  name: 'Al1o5iAceHAf9UJgMjM4Clwn.png',
  boxType: 2,
  mimeType: 'image/png',
  localPath: '/tmp/Al1o5iAceHAf9UJgMjM4Clwn.png' }
and the image size is 2.8K
*/
await somebody.say(fileBox) //nothing happend, and no error was thrown

## 4. Expected behavior
Give a clear and concise description of what you expected to happen.
pass

## 5. Actual behavior
If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.
pass

## 6. Full Output Logs
Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)
I set the env but I cannot find the log

## 7. Additional context
pass

[bug]

**Comment by lumingwen** [comment]
发送不了图片嘛

**Comment by hywhuangyuwei** [comment]
> 发送不了图片嘛

yes

**Comment by lumingwen** [comment]
why 腾讯改了吗

**Comment by lijiarui** [comment]
Tencent change some code on web wechat.

Related issue: https://github.com/Chatie/wechaty-puppet-puppeteer/issues/91

We fix here: https://github.com/Chatie/wechaty-puppet-puppeteer/pull/106

This PR should be published on v0.17.23 or later version, please update the code and you can send image or file!

cheers!

**Comment by huan** [comment]
@lijiarui Please add the `Bug` label to the issue if it is a confirmed bug.

**Comment by huan** [comment]
Is there anyone who can confirm this bug had been fixed successfully?

**Comment by huan** [comment]
@hywhuangyuwei @lumingwen Could you please help us to confirm that whether this bug had been fixed in the next version of the wechaty-puppet-puppeteer ?

**Comment by hywhuangyuwei** [comment]
@huan Fixed!
`Contact.say(imageAsFileBox)` works perfectly with wechaty@0.27.53 and wechaty-puppet-puppeteer@0.17.23.

**Comment by huan** [comment]
Thank you very much for confirming this fix and closing this issue.

Cheers!
