### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by moling1234** [Chatie/wechaty#1797]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]

![image](https://user-images.githubusercontent.com/32126933/59961726-32732b00-950e-11e9-8cd4-28442eab0e84.png)

**Comment by huan** [comment]
If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

**Comment by huan** [comment]
Close this issue because the problem had been fixed.

See <https://github.com/wechaty/wechaty-getting-started/issues/83>
