### ISSUE TITLE
Room announcement is not working properly for some puppet implementation

### ISSUE THREAD

**Issue by windmemory** [Chatie/wechaty#1816]
Today we tested the room announcement feature with `wechaty-puppet-padpro`.

Seems like the room announcement is a special type of message, which mentions everyone in the room, and the data structure is different from the regular messages. So calling the `mention()` or `mentionSelf()` method on an announcement message will throw out errors with `wechaty-puppet-padpro`. I haven't got time to pull out the actually message content yet, will do this later, but before that, I wondered how should we handle such message, and would like to start the discussion about the way that we deal with such kind of message.

Shall we put all room members in the `message.mention()` call? Or we could have some other message type?

Please let me know what you think @huan 

---

After we have conclusion of how to deal with the room announcement message, we need to fix the room announcement implementation in `wechaty-puppet-padpro`, issue here: https://github.com/botorange/wechaty-puppet-padpro/issues/166

Other puppet implementation needs to check the function is working as expected.

**Comment by huan** [comment]
I will think that the announcement message should be seen from the user side as a normal mention message for themselves.

**Comment by windmemory** [comment]
Okay, if we implement the feature in that way, then for `Message.mention()` function, we shall return back the whole list of the room members, is that correct?

**Comment by huan** [comment]
Correct. That's the idea. Please go ahead.

**Comment by windmemory** [comment]
Okay, will impl in that way. Close this issue.

**Comment by huan** [comment]
Great.

Looking forward to this new feature, and thank you very much for keeping improving the Wechaty.

Cheers!

**Comment by huan** [comment]
BTW: I'd like to keep this issue to be open so that you could be able to reference this issue in your Pull Request and commits.

**Comment by windmemory** [comment]
This issue was originally opened for discussion of how to deal with room announcement message, and we have a conclusion, so this topic should be considered as closed.

But you want to track this issue's progress, so let's rename this issue and pivot the purpose of this issue to `fix the room announcement message implementation`

**Comment by huan** [comment]
Thank you for renaming this issue and keeping track it.

Would love to know the following works related to this issue.

**Comment by windmemory** [comment]
This issue is resolved in `wechaty-puppet-padpro` for version that is newer than `v0.3.12`

Can we close this issue? @huan

**Comment by huan** [comment]
Of course. And it would be great if you could link the related issues & pull request to this issue before closing it.

Thanks for the contribution!

**Comment by windmemory** [comment]
Okay, linked the issue and close this issue :)
