### ISSUE TITLE
登录不了，有办法解决吗？

### ISSUE THREAD

**Issue by cwjfeifei** [Chatie/wechaty#1842]
ERR PuppetPuppeteerBridge onLoad() exception: Error: 为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com

**Comment by lijiarui** [comment]
see https://docs.chatie.io/v/zh/#web-limit-1

**Comment by fishfree** [comment]
@lijiarui  Page not found, now. How to do?

**Comment by lijiarui** [comment]
@fishfree because we delete the Chinese doc. See: https://docs.chatie.io/#web-wechat-limitations

**Comment by huan** [comment]
Merge to #603
