### ISSUE TITLE
Function message `toContact()` should to be implemented.

### ISSUE THREAD

**Issue by su-chang** [Chatie/wechaty#1855]
**Is your feature request related to a problem? Please describe.**

As we know, we can send `ContactCard` message peer to peer or to room in Wechaty, but we can do nothing when we received a `ContactCard` message in Wechaty.

**Describe the solution you'd like**

I hope that we can use `ContactCard` to add friend. Then we can add friend in room or pm by Wechaty.

**Describe alternatives you've considered**

We can do something like `UrlLink`, create a model named `contact-card` in Wechaty, and it need a ContactCardPayload like this: 
```js
export interface UrlLinkPayload {
  userName : string,
  nickName: string,
  headImgUrl: string,
}
```
When the bot received ContactCard message,  then we use function `message.toContact()` to get `userName` from ContactCardPayload, and then the bot can add friend by `userName`.

**Additional context**

I will create a PR for this issue later.

[enhancement]

**Comment by huan** [comment]
Could you explain that why don't we use the Contact directly for this case?

Is there any reason make us have to create a new class for using it?

**Comment by su-chang** [comment]
> Could you explain that why don't we use the Contact directly for this case?
> 
> Is there any reason make us have to create a new class for using it?

you are right, the `ContactCardPayload` should be replaced by `ContactPayload`.

I just mean `ContactCardPayload` for message type `ShareCard`, there's no need to create a new class in coding. Thx for pointing out this.

**Comment by su-chang** [comment]
All the supported `toContact()` method PR here:

https://github.com/Chatie/wechaty/pull/1862
https://github.com/Chatie/wechaty-puppet/pull/59
https://github.com/botorange/wechaty-puppet-padplus/pull/38

**Comment by huan** [comment]
Please remember to reference this issue in your other PRs/Issues, so that we can get a clear reference list when reading this issue.

**Comment by huan** [comment]
The above links from the PR to here can make the status clear, that's the reason why we should reference this issue in other PRs/Issues.
