### ISSUE TITLE
Function xxx.say() should return message id, make Wechaty message easy to extend.

### ISSUE THREAD

**Issue by su-chang** [Chatie/wechaty#1857]
**Is your feature request related to a problem? Please describe.**

When I want to recalled the message which I have send just now, I don't know the message unique id of it in Wechaty.

**Describe the solution you'd like**

The return type of function `xxx.say()` should change from `Promise<void>` to `Promise<string>`, let's make it return the message id for extend options.

For example:
```js
public async contact.say(text: string): Promise<string>

const msgId = await contact.say('hello')
const messagePayload = await bot.Message.load(msgId)
// do something with the `messagePayload`
```

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by huan** [comment]
I liked this idea. Would love to see your PR and study how you could implemented it.

After that, we will be able to discuss it in details.
