### ISSUE TITLE
[new feature] Forward Message

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#200]
Forward a message to a contact

~~message.forward(contact: Contact): Promise\<void\>~~
```ts
message.forward(contact: Contact): Promise<boolean>
```

**Comment by dcsan** [comment]
is this just for text message types? or is there a way to use the forward function to forward other media types, without wechaty having to understand the content type of the message? 

this could be useful for all the other media types until wechaty is able to send images directly. we could send a message to a wechaty bot and just have it "store and forward"

**Comment by zixia** [comment]
No, this is not just for text message types.

This new feature should implement a `Message.forward()` method for all type of messages. Just like you _right click on a message_ on Web Wechat, which can forward any message, not only the text message but also picture/video/link/attachment message.

You will be able to do this without _understand the content type of the message_ by this new feature. 

And send image is planned to be implemented with this feature together, at [Milestone v0.8](https://github.com/wechaty/wechaty/milestone/8)

**Comment by dcsan** [comment]
OK awesome. so this feature is for 0.8 and send image is for 0.9? I can't wait for `sendImage`!

**Comment by zixia** [comment]
Those will all belongs to v0.9. 

`sendImage` feature was first planned at v0.2, I can't wait for it too! :P

**Comment by zixia** [comment]
Move to #726
