### ISSUE TITLE
[new feature] set bot's nickname in the group

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#201]
I'm trying to get room unique id for the bot.

Issue #90 has talked about the result of room id, @zixia  says it is impossible to get the permanent id for a room when using the webwxApp API.

So, maybe we can set a unique nickname(wechaty called it display name) for a bot in the room, then we can use the bot's nickname in the room as `this room's unique id`.

I found wechaty can set contact's remark, but it cannot remark one's name in the room. 

So could you please add an API to set one's name in the room?

**Comment by zixia** [comment]
There will be many scenarios that we need to identify a room between wechat sessions. Your idea is an excellent solution that makes Wechaty identify a room between sessions.

Could you please make an API proposal for this new feature in this issue? We can discuss based on it.

**Comment by lijiarui** [comment]
Thanks!

1. Add the following obj from `Room Class` in `Contact` property
```
export type RoomRawMember = {
  UserName:     string
  NickName:     string
  DisplayName:  string
}
```

2. maybe the following API is a good choice:
`Contact.displayname()` : get one's nickname in the group
`Bot.displayname(name: string)` : set the bot's nickname in the group, because we cannont set other's nickname in the group
`Bot.displayname(null)`: delete the bot's nickname in the group

**Comment by zixia** [comment]
This proposal is not complete because the design leaks important information.

> Contact.displayname() : get one's nickname in the group

1. how could this API get displayname, which room?

> Bot.displayname(name: string) : set the bot's nickname in the group, because we can not set other's nickname in the group

2. same as Q1: which room?

I believe your `displayname` should rename to `displayName`, and this method should belong to a Room instance?

Also, how could we get Display Name from another Contact in a particular room? This scenario should be considered in the design as well.

**Comment by zixia** [comment]
And I forgot the most important part: does Web Wechat support **change display name in a room** ?

**Comment by lijiarui** [comment]
I'm sorry I forgot the most important part.....
so, any others have any good idea, welcome......

**Comment by zixia** [comment]
@lijiarui What's your mean?

Did you mean you confirmed that Web Wechat not support modify display name?

**Comment by dcsan** [comment]
I can confirm that you can use the "edit alias" feature on a user name.

It does NOT seem to work on your own username by clicking personal profile icon

BUT if you select yourself in a group and then change it this will seem to work.

My phone also updates, so the information on updated alias is being sent to the network / propagated.
BUT i don't see any messages in wechaty log when editing aliases. So perhaps alias update events are not sent to wechaty/web client, or you have some other filtering of the messages higher in the chain that stops them being logged.

**Comment by lijiarui** [comment]
@zixia yes, I found Web Wechat does not support modify display name in the group....   

@dcsan Do you have some good idea to help?

**Comment by zixia** [comment]
@dcsan Awesome, your method is the key to implementing this feature, thanks, buddy!

@lijiarui Could you follow @dcsan's method, and continue editing your API proposal with my suggestion?

**Comment by zixia** [comment]
@lijiarui could you please confirm with @dcsan whether _select yourself in a group and then change alias_ work in web wechat?

I just tried this method, it seems not work as expected, because I can not see any change of my room display name on my phone.

**Comment by lijiarui** [comment]
For me , "select yourself in a group and then change alias" doesn't works in web wechat.  

When I change bot's remark in the room, it doesn't have any change in my phone.

And, I found when using webWeixin， I thought I changed one's display name in a room, but actually I changed one's remark. So, when I change one's display name in a room, it works in all the room....

**Comment by dcsan** [comment]
I think remark and alias are mixed up in the english translation of wechat webUI.

Also when I checked just now, the phone did NOT update. I'm sure it did before... >.<

I also enabled more debugging and don't see any messages when changing that field, so I think this maybe a client side only setting, or at least only shared with wechat servers and not echoed to other clients.

**Comment by lijiarui** [comment]
`remark === alias ` as we talked in wechat developers home

**Comment by zixia** [comment]
1. About the name `remark`

All methods and variables in webwxapp that modify alias are named `remark`. That is the reason why Wechaty use `remark` instead of `alias`

2. Get _Display Name_ from a contact in a room

In webwxapp, the user alias name in a room is named `DisplayName`.

Even we can not set _Display Name_, we can also get the display name without any problem because this name is saved in the Room's `MemberList` array variable.

To identify the room as @dcsan said before, we can still set the display name on our phone, then get display name from Wechaty.

So @lijiarui you can still go ahead for the API design because it's still useful even we can only read it.

**Comment by lijiarui** [comment]
@zixia 
Maybe after you approve my PR related to #174 , then maybe I can design this API well.

**Comment by zixia** [comment]
This one? [document] should list only the public/stable API to users #174

**Comment by lijiarui** [comment]
Oh, I'm sorry, #173

**Comment by zixia** [comment]
@lijiarui Is this issue outdated and should be close now?

**Comment by lijiarui** [comment]
We cannot set bot's alias in a room, but we can get the bot's alias in the room.
So if we want to get the room unique id, we can set the bot's alias manually, then use room.alias(contact) to check the alias.

**Comment by dcsan** [comment]
neat hack. So basically you manually name your own bot something related to the roomname.

**Comment by lijiarui** [comment]
yes，maybe is the best way so far. If you have any good idea, glad to hear from you ^-^
