### ISSUE TITLE
Avatar return empty image in example/contact-bot.ts

### ISSUE THREAD

**Issue by xinbenlv** [Chatie/wechaty#246]
Under  example directory

### Actual behavior
Images are empty

### Steps to reproduce the behavior (and fixes, if any)
docker run -ti --volume="$(pwd)":/bot --rm zixia/wechaty contact-bot.ts

### Paste the full output logs here with `WECHATY_LOG=silly` set
https://login.weixin.qq.com/qrcode/wdTdOlMO4A==
[408] Scan QR Code in above url to login:
https://login.weixin.qq.com/qrcode/wdTdOlMO4A==
[201] Scan QR Code in above url to login:
INFO Bot 好室友小帮手 logined
INFO Bot #######################
INFO Bot Contact number: 2

INFO Bot Contact: : 芃 with avatar file: 0-芃.jpg
INFO Bot Contact: : 周载南 with avatar file: 1-周载南.jpg
INFO Bot I will re-dump contact weixin id & names after 7 second...
INFO Bot #######################
INFO Bot Contact number: 34

INFO Bot Contact: : Aoni_W with avatar file: 0-Aoni_W.jpg
INFO Bot Contact: arielzhouaihua: Arielzhou with avatar file: 1-Arielzhou.jpg
INFO Bot Contact: fireisborn0318: Chris Hsu with avatar file: 2-Chris Hsu.jpg
INFO Bot Contact: claireyunyunwhatsup: Claire Yunyun with avatar file: 3-Claire Yunyun.jpg
INFO Bot Contact: : 大梁 with avatar file: 4-大梁.jpg

**Comment by zixia** [comment]
Which version?

I could always run contact-bot without any problem before.

**Comment by zixia** [comment]
I will close this issue. Please submit a new issue if you still have problem with this feature.

Thanks.
