### ISSUE TITLE
add `room-bot-leave` event

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#250]
We have a `room-event` when bot removed others from the room, but when others removed the  bot from the room, we don't have any event.

So I suggest adding an event when the bot is removed from the owner of one room.

Then I have a question: 

##### 2. `room-leave`: use `leaverList` to identify the differences.

I prefer the `room-bot-leave`,  because I think `bot remove others from the room` and `others remove bot from the room` used in different scene.

#### Sys Message as follows:

> You were removed from the group chat by "桔小秘"
> 你被"李佳芮"移出群聊

**Comment by lijiarui** [comment]
@zixia What do you think about it?

**Comment by zixia** [comment]
I agree that when the bot is removed out of a room, the `leave` event should be fired. 

And I agree with your option 2. When bot itself is removed, `leaverList` will include the bot, and we can use `Contact.self()` to identify if a `leaver` is the bot.

The existing event `leave` / `room-leave` have already covered this scenario which makes great sence; I think there's no need to introduce a new event.

PR is welcome.

**Comment by lijiarui** [comment]
@zixia If we use option 2, do you think we should tell who removed the bot from the room? 

If we want to tell the user who removed the bot from the room, we cannot just use `leaver`, we should add a parameter like `remover`. 

It may seems like this:

```
.on('room-leave', function(this, room, leaver, remover) {
  log.info('Bot', 'EVENT: room-leave - Room %s lost member %s by %s'
                , room.topic()
                , leaverList.map(c => c.name()).join(',')
                , remover.name()
              )
})
```

#### 1.If the bot removes a contact from the group:
leaver = contact
remover = bot
#### 2.If the others remove the bot from the group:
leaver = bot
remover = contact

**Comment by zixia** [comment]
Of course. If we can "tell who removed the bot from the room", then tell it.

Your design looks perfect.
