### ISSUE TITLE
[doc] Contribute to the doc editing[ jsdoc / jsdoc2md / typedoc ]

### ISSUE THREAD

**Issue by ax4** [Chatie/wechaty#252]
Hi, 

I find the API doc need:  
* some minor fix (such as the different naming [Message Class](https://github.com/wechaty/wechaty/wiki/API#message-class) & [Class Room](https://github.com/wechaty/wechaty/wiki/API#class-room)) 
* improvement on the formatting, e.g. the level setting of each title 
* maybe, add an index for better guiding

I am volunteering to contribute to doc. I was wondering what should I do?  Thanks!

**Comment by zixia** [comment]
Hi @ax4 ,

Welcome!

An useful FrameWork with good document will help the community save lots of times. Wechaty is an useful ChatBot FrameWork, it need to be well ducumented.

We have a plan to re-document Wechaty, you can join us. Please see #73 .

Thank you very much for your volunteering!

**Comment by lijiarui** [comment]
@ax4  We are trying to just give  outlined api in API doc, could you give an outline suggestion here?

**Comment by ax4** [comment]
@lijiarui Hi, good to hear that!! I think, a good API doc should be based on User's most demand.  So I would suggest the outline as below:  

* Introduction to Wechaty
    * HelloWorld
    * Save my login status (profile)
* Basic Events of Wechaty
    * scan
    * login
    * logout
    * message
    * error
    * friend
    * room-join
    * room-leave
    * room-topic
* Reply a Message to Contact / Room 
    * Reply to Contact
    * Reply to Room
* Search for Contact / Room (Query Type)
    * Contact Query Type
    * Room Query Type
* API Details of Class
    * Wechaty Class
        * Wechaty.instance(profile:string): Wechaty
        * Wechaty.init(): Wechaty
        * Wechaty.send(message: Message): Wechaty
        * Wechaty.say(content: string)
    * Message Class
        * Message.from(contact?: Contact|string): Contact
        * Message.to(contact?: Contact|string): Contact | void
        * Message.content(content?: string): string
        * Message.room(room?: Room|string): Room | void
        * Message.type(): MsgType
        * Message.typeApp(): AppMsgType
        * Message.say(content: string): Promise
        * Message.self(message: Message): boolean
        * Message.id: string
        * Message.filename():string
    * Contact Class
        * Contact.id: string
        * Contact.name(): string | ''
        * Contact.city(): string | undefined
        * Contact.province(): string | undefined
        * Contact.gender(): Gender | undefine
        * Contact.avatar():
        * Contact.alias(): string | null
        * Contact.alias(alias: string): Promise
        * Contact.weixin(): string | ''
        * Contact.star(): boolean
        * Contact.refresh(): Promise
        * Contact.self(): boolean
        * Contact.stranger(): boolean
        * Contact.say(content: string): Promise
        * Contact Query Type
    * Room Class
        * Room.say(content: string, replyTo: Contact|Contact[]): Promise
        * Room.refresh(): Promise
        * Room Events
        * Room Query Type
        * Room.add(contact: Contact): Promise
        * Room.del(contact: Contact): void
        * Room.topic(newTopic?: string): string | void
        * Room.alias (contact: Contact): string
        * Room.has(contact Contact): boolean
        * Room.owner(): Contact | null
        * Room.member(name: string): Contact | null
        * Room.member({alias: string}): Contact|null
        * Room.member({name: string}): Contact|null
        * Room.memberList(): Contact[]
    * FriendRequest Class
        * FriendRequest.hello: string
        * FriendRequest.accept(): Promise
        * FriendRequest.send(contact: Contact, hello: string): Promise

**Comment by lijiarui** [comment]
@ax4 Sounds Great! 

@zixia  How do you think about it?

**Comment by zixia** [comment]
Fantastic. It's very clear and effective for introducing Wechaty API.

After we finished the new documents, I'd like to invite @ax4 to write a blog post for Wechaty about the API usage introduction. I believe it will be one of the most useful article of Wechaty for new developers.

Thanks!

**Comment by lijiarui** [comment]
@ax4 Sorry for not contacting you in a long time.

We suggest using JsDoc to generate doc automatically where @zixia had said in #73 

I have added a contact doc here in [New PR](https://github.com/Chatie/wechaty/pull/321) to show you the example.

I suggest we can use jsDoc for the following wechaty classes to generate doc [here](https://github.com/lijiarui/wechaty/blob/testDoc/docs/index.md#genderundefined-2) and then use the outline you write in wiki. Then as you said,  leading one to see more in detail in the doc.

About wechaty Class, I suggest the following files to add jsDoc:
- src/message.ts
- src/room.ts
- src/wechaty.ts
- src/friend-request.ts

#### Reference 
- [](url)
- [](url)
- [](url)
- [](url)

**Comment by lijiarui** [comment]
@ax4 hi, how are things going?
I'm glad to help if you have any questions, or you can add my wechat: 13141321843

**Comment by ax4** [comment]
@lijiarui @zixia Hi, I have found another doc-generator: TypeDoc (http://typedoc.org)

I would recommend TypeDoc rather than jsDoc or jsDoc2md, based on the facts:
* TypeDoc has better support for TypeScript, than the other two tools 
* TypeDoc give an API document as a HTML site, which is more informative than a single markdown file. 
* It also supports the embedded jsDoc syntax.  

Overall, I will vote for TypeDoc. 

Reference: 
[TypeDoc Official](http://typedoc.org)
[Generating Document for Typescript Project (TypeDoc) by Cloudflare](https://blog.cloudflare.com/generating-documentation-for-typescript-projects/)
My PR #375

**Comment by lijiarui** [comment]
Glad to hear from you!
Waiting for your new PR ^-^

**Comment by zixia** [comment]
@ax4 I had read all of the typedoc doc before, include the cloudflare one.

Typedoc is the first tool I would like to choice at first.But finally I found it does not meet my following two requirement:

1. Simple and clear: it generate to much information than we needed. It is more like a Microsoft style.
1. Generate markdown for better readable version control and github page hosting.

I try to find a tsdoc to md plugin, but only found some in progress one.

That's the reason why I choice tsc + jsdoc at last. 

My suggestion is to finish the first version of our jsdoc document with the current tsc + jsdoc flow. After that, we can start to compare other methods.

**Comment by kis87988** [comment]
I will try to contribute about this issue

**Comment by kis87988** [comment]
I will try to contribute about this issue

**Comment by zixia** [comment]
@kis87988 That's awesome, welcome and looking forward to your PR for documents!

**Comment by zixia** [comment]
Merge to #73
