### ISSUE TITLE
add an event when the bot is invited into a room

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#255]
When others join in the room, it can emit 'room-join' event, but when the bot is invited to a room, we don't have any event.

So I suggested to add an event when the bot is invited to a room.

Maybe we can still  use `room-join` event.

Sys Message as follows:

> "李佳芮"邀请你加入了群聊，群聊参与人还有：洁云微商、感觉、逗比
> “李佳芮”invited you to a group chat with 独留一人、于、DEE

**Comment by zixia** [comment]
Thanks, this event should be included in the `room-join` event(and `join event for Room).

PR is welcome!

**Comment by zixia** [comment]
Moved to puppet puppeteer repo for more specific tracking.
