### ISSUE TITLE
[docker] to prevent docker users install a local dependence of wechaty

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#281]
When you are using the Docker solution, have a local Wechaty dependency is not necessary, sometimes harmful.

To fix it, the quick & dirty way is to run `rm -rf node_modules/wechaty` before start docker.

The right way is: **Get rid of wechaty dependency in your package.json if you are using Docker solution.**

The reason that not add dependency is that the Docker image already shipped the right version of Wechaty, which is installed globally. The correct usage should be good documented and show a warn message at Docker starting if meet this issue.

If you guys have any suggestion, please let me know, thanks. @xinbenlv @lijiarui @JasLin

**Comment by lijiarui** [comment]
So useful!

**Comment by zixia** [comment]
Done by get rid of dependence when build the docker image.
