### ISSUE TITLE
Room.find({topic: topic}) should allowed to return null

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#291]
Now, function public static async find(query: RoomQueryFilter): Promise<Room>` , when we cannot get room, it will throw new Error.

source code as follows:
```
 public static async find(query: RoomQueryFilter): Promise<Room> {
    log.verbose('Room', 'find({ topic: %s })', query.topic)

    const roomList = await Room.findAll(query)
    if (!roomList || roomList.length < 1) {
      throw new Error('no room found')
    }
    const room = roomList[0]
    await room.ready()
    return room
  }
```

I thought it should return null when we cannot find the room instead of throw error.

**Comment by lijiarui** [comment]
Then I look up into `Class Contact`, I think 
```
public static async find(query: ContactQueryFilter): Promise<Contact>
```
it should return null too when we cannot find the contact instead of throw error

**Comment by zixia** [comment]
I agree. PR is welcome.
