### ISSUE TITLE
How about add a new kind of name called `Display` in the room

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#334]
@zixia  I think maybe we should keep three kind of name in the room.
besides `name` and `alias`, we should also add `display`

We had 2 kinds of roomMap now:

#### nickMap
```
"nameMap": {
            "@4c32c97337cbb325442c304d6a44e374": "22acb030-ff09-11e6-8a73-cff62d9268c5", 
            "@cd7d467d7464e8ff6b0acd29364654f3666df5d04551f6082bfc875f90a6afd2": "小桔同学", 
            "@36d55130f6a91bae4a2ed2cc5f19c56a9258c65ce3db9777f74f607223ef0855": "50fb16c0-ff09-11e6-9fe5-dda97284d25b"
        }, 
```

#### aliasMap
```
"aliasMap": {
            "@4c32c97337cbb325442c304d6a44e374": "", 
            "@cd7d467d7464e8ff6b0acd29364654f3666df5d04551f6082bfc875f90a6afd2": "", 
            "@36d55130f6a91bae4a2ed2cc5f19c56a9258c65ce3db9777f74f607223ef0855": ""
        }
```

`nameMap` can identify the contact by bot version.
`aliasMap` as your request, should return roomAlias，if not set, it should return ''

**Then, what if other contact's vision in a room?** I think we should consider this.

For example,  when I `@舞哩客服`， whose alias is  `50fb16c0-ff09-11e6-9fe5-dda97284d25b`  set by the bot. but I cannot find the contact by any kind of map, sometimes, it real confused the developer.

#### 2. As I suggested long long ago, add a new kind of map: `displayMap`, it return `alias || name`.

Then we can find the contact by name, alias, and display.

What's your concern?

BTW, About the Display Order, I have talked in #173 

> ### Definition
> * `nickName`  Contact's wechat nickName
> * `remark` When the bot set alias or remark for a contact in contact list, we call it remark.
> * `displayName` When a contact set its's alias in the group,  we call it displayName, so displayName is bind to one room.
> 
> 
> ### Display order:
> 
> #### @ Event
> When someone @ a contact in  a room, wechat recognise the name order as follows:   
> `displayName > nickName`
> 
> #### system message
> When room event happens(join, leave, changetopic), system message recognise the name order as follows:   
> `remark > nickName`
> 
> #### on-screen Names
> The contact name showed to the wechat user in the group   
> `remark > displayName > nickName`

Related Issues : #173 #217

**Comment by lijiarui** [comment]
>  i don't understand what is "contact's version in a room

About this, I mean others contact(not the bot, and not the message sender) in the room.

For example:
The room has the following 3 contacts:
`李佳芮`， `zixia`, `桔小秘`，  

- `桔小秘` is the bot, and set alias for `李佳芮`(22acb030-ff09-11e6-8a73-cff62d9268c5) and  `zixia`(50fb16c0-ff09-11e6-9fe5-dda97284d25b)
- `李佳芮`  set her roomAlias in the room called `芮芮-管理员`
- then, what  `zixia` saw their names in the room?-----this is other contact's vision(sorry for the typo....)

**Comment by zixia** [comment]
firstly, what you said

> aliasMap as your request, should return roomAlias，if not set, it should return ''

Is not true. I never request that. the master branch will return null if room alias is not set, which is from your PR.

secondly, you should use `room.member()` to get the contact from a name.

**Comment by lijiarui** [comment]
sorry， it return null. I said by mistake.

But, using `room.member()` cannot get the contact from a name when the bot set alias for the contact as nameMap showed:
```
"nameMap": {
            "@4c32c97337cbb325442c304d6a44e374": "22acb030-ff09-11e6-8a73-cff62d9268c5", 
            "@cd7d467d7464e8ff6b0acd29364654f3666df5d04551f6082bfc875f90a6afd2": "小桔同学", 
            "@36d55130f6a91bae4a2ed2cc5f19c56a9258c65ce3db9777f74f607223ef0855": "50fb16c0-ff09-11e6-9fe5-dda97284d25b"
        }, 
```

**Comment by zixia** [comment]
Yes, that's what you need to think about.

**Comment by lijiarui** [comment]
###  I have 2 solutions:
#### 1. As I had done before: let aliasMap return `alias || name`, that means if one not set its roomAlias, it return name.

#### 2. As I suggested long long ago, add a new kind of map: `displayMap`, it return `alias || name`.

Then we can find the contact by name, alias, and display.

**Comment by zixia** [comment]
I do not understand why you have to do this.

I suggest you write your code in your forked code base, and use your code base in your bot environment.

After you feel very comfortable about that, you can send this PR again.

**Comment by lijiarui** [comment]
> I do not understand why you have to do this.

Because when someone `@name` in the room, I want to find the contact by name(not any alias). But when the bot set alias for this contact, it doesn't work.

**Comment by zixia** [comment]
This explanation could only reflect how lazy you are. :-D

**Comment by lijiarui** [comment]
- add function `room.memberAll():Contact[]` correspond to `room.member(): Contact`
- change room.member() query to 3 types:
 - name
 - roomAlias
 - contactAlias

**Comment by zixia** [comment]
Duplicated with #365
