### ISSUE TITLE
[discuss] Rename Wechaty to Chatie?

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#346]
Hi all,

I have been thinking about **renaming Wechaty** for a long time.

The reason makes me think about it, is not because I do not like this name. I love this name, just as many of you, it has many Pros: short, easy to be remembered and pronounced.

However, the Cons of this name is very hard to SEO. When we want to search Wechaty in Google, there almost all of the results is about Wechat. Wechaty is treated as a typo of Wechat and is very hard to appear on the first result page.

That's a terrible situation for a project name. I try to find another name for Wechaty, and I think **Chatie** is a good candidate name.

But rename a project is not as easy as just rename. I know many of you are using Wechaty, renaming will means you have to use another name in your code. 

So I want to hear from you about:
1. Do you think it's necessary to rename?
1. Do you love the new name: Chatie?
1. What will you get when you search `Wechaty` on the search engine?

Please leave comments on this issue, Thanks!

**Comment by Gcaufy** [comment]
https://github.com/pugjs/pug/issues/2184

**Comment by Gcaufy** [comment]
BTW. this is screenshots of my google.com.hk searching results:

![image](https://cloud.githubusercontent.com/assets/2182004/24133510/71f3e9ae-0e38-11e7-8684-271a3dca71d5.png)

**Comment by zixia** [comment]
@gcaufy thanks for the feed back! 

I agree with you that user are lazy, so my plan is to change the name before a big version update, ie, send image/cloud management.

However, your search result is amazing. If all search could show this I will be very comfortable about that.

Could you try to logout out of your Google account and try again? I'm afraid that this result is only for yourself according to your visit history.

**Comment by Gcaufy** [comment]
I tried it on my colleague's computer, it's also getting the same results.
Not sure it's a network issue or not. but apparently it can be SEO optimized.

**Comment by Jolly23** [comment]
Here is my screenshots of google, only Github project link is shown in the first page.

<img width="1440" alt="screen shot 2017-04-17 at 16 00 28" src="https://cloud.githubusercontent.com/assets/17488831/25083013/0920e3d2-2387-11e7-818b-f7e5acd43c12.png">

**Comment by Jolly23** [comment]
Rename the project will affect lots of developers, but it is necessary for SEO.
So I agree your plan that to change the name before a big version update.
I love the name "Chatie".

**Comment by zixia** [comment]
@Jolly23 Thank you very much for your feedback.

It seems wechaty is at the first position at your google search result page?

It's a very good result, and if it can always be there, then the rename might not necessary.

**Comment by Jolly23** [comment]
Actually, it was placed on the second item in the searching result page when I searched it first time.

**Comment by zixia** [comment]
Final Decision: Keep Wechaty name for now, because the search result seems better and better.
