### ISSUE TITLE
How to identify a contact/room is a saved contact/room?

### ISSUE THREAD

**Issue by 51168** [Chatie/wechaty#357]
The existing interface doesn't seem to have this feature
Please help me if there is an implementation interface

**Comment by lijiarui** [comment]
how about `Room.findAll()`

**Comment by 51168** [comment]
我想只拿到添加到通讯录->群聊->下的全部群。而findall()则是拿全部群。有没有办法只拿已经添加通讯录下群？I want to get added to the mail list - > - > all the group chat group. And findall () is to take all the group. Is there any way to get the address book group? thanks, good job.

**Comment by lijiarui** [comment]
Sorry, I think there is no way on this moment.

**Comment by zixia** [comment]
I suggest to have a look on `rawObj` of the room; there might have some values which could help us to identify whether the room is a `saved` contact.

**Comment by 51168** [comment]
good job, i try。

**Comment by 51168** [comment]
run 
```
Room.findAll({ topic:/小白伴读101-亲子阅读/g}).then(dingRoom =>{
      dingRoom.forEach(r => {
        console.log(r)
      })
  })
```
result:
Room {
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  id: '@@xxxxxxxxx' 
}
no identify field;I think this demand is necessary, there should be a lot of people need. Can you iterate over a version?thanks.

**Comment by zixia** [comment]
@51168 

Could you try this again:

```ts
Room.findAll({ topic:/xxxxx/g}).then(dingRoom =>{
      dingRoom.forEach(r => {
        r.ready().then(r2 => {
          console.log(r2)
        })
      })
  })
```

**Comment by 51168** [comment]
Thanks, Good job; I try。

**Comment by 51168** [comment]
it work, but i only want find all saved contact room, not's all room. i check Room.rawObj not identily field Is not the contact/room or saved contact/room。how? @zixia

**Comment by zixia** [comment]
If you can not find any value to identify whether the room is saved before, then you will not be able to do what you want.

However, I remembered this information is stored in somewhere, `rawObj` or other arrays that can finger this out.

You can try to find it. If you could found it, then we can fix it.

**Comment by 51168** [comment]
I did not find a few times to find. There is no other solution? @zixia

**Comment by zixia** [comment]
Sorry, no other solution now. Because there must have someone to dig it out.

If you can not do it, then you have to wait for others to get this done.

Good luck!

**Comment by zixia** [comment]
I just remembered there is a method named `contact.stranger()`, maybe you will be interested.

**Comment by 51168** [comment]
tomorrow I try,thanks good job.

**Comment by zixia** [comment]
@51168 Hello, did you make it?

**Comment by 51168** [comment]
no, i don't make

**Comment by zixia** [comment]
Close this issue because it can be filtered by `stranger()` method.
