### ISSUE TITLE
Room.member() cannot find contact correctly

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#365]
Bug: When the bot set alias for a contact, using function `room.member({name: name})` cannot get the contact.

What's more, if there are two contacts has the same name in one room, room.member() cannot get the correct contact.

So, I have the following suggestion:

- add function `room.memberAll():Contact[]` correspond to `room.member(): Contact`. Using function `memberAll()` can get all the matches contacts.
- change room.member(query) query to the following three types:
  - name: find the contact by wechat name in a room.
  - roomAlias: find the contact by alias set by the contact in a room.
  - contactAlias: find the contact by alias set by the bot in a room.

Related issues: #334 #173 #217

**Comment by lijiarui** [comment]
fix

**Comment by ladypiapia** [comment]
sorry to bother,but how I can get roomAlias?I'm a beginner,sorry.
```
bot.ready().then(async () => {
    const allRooms = await bot.Room.findAll();
    log.info(LOGPRE, `all rooms: ${allRooms.length}`);

    const room = await bot.Room.find({topic: 'test room'});

    const memberList = await room!.memberAll();
    
    memberList.forEach(menber => {
        
        console.log(menber.name()); // how to get the roomAlias? 
         
    });

    log.info(LOGPRE, `room: ${memberList.length}`);
});
```
