### ISSUE TITLE
jsdoc2md may flush some pieces of the embedded doc

### ISSUE THREAD

**Issue by ax4** [Chatie/wechaty#378]
**In brief, this issue is caused by our auto-doc working flow, at the 1st step `npm run dist` (compile TS into JS), it flushes some pieces of embedded doc** May Impact #252 #73 

Our auto-doc working flow (with **jsdoc / jsdoc2md**):
```md
1. dev in TS
2. embedded doc insert in TS
3. compile TS into JS (#warning# this step cause flush)
4. run jsdoc / jsdoc2md
5. get the final doc
```

**See more in details:** 
1. A piece of embedded doc in TS 
https://github.com/Chatie/wechaty/blob/b77c241d7d716635c5481ed734b32e303fce8e4c/src/contact.ts#L430-L505
2. The compiled JS missing "that piece"
![flush_cause](https://cloud.githubusercontent.com/assets/8946060/24517748/0082426c-15b2-11e7-9637-23908881229f.png)
3. Cause the missing in the final doc
![flush_result](https://cloud.githubusercontent.com/assets/8946060/24517754/057927ea-15b2-11e7-84f9-5b95605ab9f1.png)

**Comment by ax4** [comment]
I will look deeper into this problem, and **trying to solve it, within 24 hours!**  

**Possible solution: (I haven't tried, I will do it)** 
1. Give up the ['one-to-one edit strategy' like this](https://github.com/Chatie/wechaty/blob/b77c241d7d716635c5481ed734b32e303fce8e4c/src/contact.ts#L430-L505), try to put only one piece for the same name function, and see if this can avoid flush?
2. Use TypeDoc, it generate good & informative doc, directly from TS files
3. Manually apply the missing piece onto JS files (need human / bot to do the job)

**Comment by zixia** [comment]
Glad to see you start working on this! :+1:

**Comment by zixia** [comment]
Merge to #252
