### ISSUE TITLE
[jsdoc] in example code, shall we use ' or ` for the string type

### ISSUE THREAD

**Issue by ax4** [Chatie/wechaty#381]
```
/**
 * @exmaple
 * console.log('hello world')
 */
```
vs 

```
/**
 * @exmaple
 * console.log(`hello world`)
 */
```

**Comment by zixia** [comment]
What's pros and cons of two types?

**Comment by ax4** [comment]
http://stackoverflow.com/questions/242813/when-to-use-double-or-single-quotes-in-javascript 

As this stackoverflow mentioned: 
>Another option, new in ES6, are Template literals which use the back-tick character:

**Comment by zixia** [comment]
:+1:

**Comment by zixia** [comment]
Duplicated with #252
