### ISSUE TITLE
group names have HTML in them

### ISSUE THREAD

**Issue by dcsan** [Chatie/wechaty#382]
sometimes group/room names come in like:

```
中国爱<img class="emoji emoji1f1e81f1f3" text="_web" src="/zh_CN/htmledition/v2/images/spacer.gif" />
```

I'm not sure how we should handle this - try and understand which emoji they are referring to and fix the group name to be ASCII?
at the least we should probably remove the `spacer.gif` html slug?

**Comment by zixia** [comment]
Could you provide the code snip that how to get this room name?

I don't think `room.topic()` will return this, because I remembered that it will strip all the HTML before turn the topic string.

**Comment by zixia** [comment]
@dcsan Please let me know if you still have the problem with this.

I'll close this issue now because it's inactive for a long time.

Have a good weekend!
