### ISSUE TITLE
MediaMessage in ding-dong-bot example can not be create

### ISSUE THREAD

**Issue by zhaozhiming** [Chatie/wechaty#399]
### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 

[The code here](https://github.com/Chatie/wechaty/blob/master/example/ding-dong-bot.ts#L75-L78), run with error as follow: 
```
ERR Bot on(message) exception: SyntaxError: Unexpected token / in JSON at position 0
```
I saw the source code in my project `node_module`. It seems different with the code in github.  

#### local: media-message.ts ( my project node_modules/wechaty)

```ts
export class MediaMessage extends Message {
  private bridge: Bridge

  constructor(rawObj) {
    super(rawObj)
    // FIXME: decoupling needed
    this.bridge = (Config.puppetInstance() as PuppetWeb)
                        .bridge
  }
``` 
#### [github：message.ts ](https://github.com/Chatie/wechaty/blob/master/src/message.ts#L550-L576)

Is there something wrong happen to me? Help.
My wechaty version is: 0.7.41.

### Expected behavior

Can run the example correctly.

### Actual behavior

Run the example with error as follow: 
```
ERR Bot on(message) exception: SyntaxError: Unexpected token / in JSON at position 0
```

### Steps to reproduce the behavior (and fixes, if any)

Run ding-dong-bot example and send code to bot.

**Comment by zixia** [comment]
> My wechaty version is: 0.7.41.

You need the latest version of Wechaty to run this demo for send image.

Please have a try with v0.7.62
