### ISSUE TITLE
Can we do forwarding or send the message whose type is news or others

### ISSUE THREAD

**Issue by lvsjack** [Chatie/wechaty#405]
可以发送或者转发图文消息吗？

example below:
[link of photo](http://o9mkyqbb3.bkt.clouddn.com/2017-04-12--Users-Jack-Downloads-IMG_4090.jpg)

as the image shows, the bot reply me the message with link and images. 

can we do that?  how?

**Comment by zixia** [comment]
At the current version, Wechaty is not supporting 转发图文消息(yet).

Could you confirm if Web Wechat could 转发图文消息? 

If Web Wechat could do this, then you can expect Wechaty implement this in the near future.

**Comment by zixia** [comment]
Ref: #200
