### ISSUE TITLE
cannot remark friend in centos system

### ISSUE THREAD

**Issue by amyhuangxbd** [Chatie/wechaty#406]
### Steps to reproduce the behavior (and fixes, if any)
1. code: 
    ```
bot.on('friend', async function (contact, request){
await request.accept()
    const remarkName = contact.get('name')
    const ret = await contact.alias(remarkName)
                  if (ret) {
                      console.log('ok')
                    } else {
                      console.error('failed')
                    }
                    await contact.refresh()
                    log.info('Bot', 'get alias: %s', contact.alias())
})
```

**Comment by amyhuangxbd** [comment]
`setTimeout(async function(){
                 const remarkUser = ' ' + contact.get('name')
                 const ret = await contact.alias(remarkUser)
                 if (ret) {
                     console.log('ok')
                   } else {
                     console.error('failed')
                   }
                   await contact.refresh()
                   log.info('Bot', 'get alias: %s', contact.alias())
               }, 1000 * 30)`

I use setTimeout to fix this issue

**Comment by zixia** [comment]
Great to hear that you had solved this problem.

But I did not understand why run your code after 30 seconds would fix this. Do you know why? If so, could you explain it so we could think about how to deal this situation inside the FrameWork, make developers happier.

**Comment by amyhuangxbd** [comment]
Personally, I think the main reason is that my server has low performance and has some other running projects.

**Comment by xhh** [comment]
The same issue also happens to me *sometimes* (failed to set alias for a Contact on event of 'friend'), here are the logs:

```
10:20:05 WARN PuppetWebBrowser executeAsync() exception: asynchronous script timeout: result was not received in 10 seconds
  (Session info: chrome=58.0.302
10:20:05 WARN PuppetWebBridge executeAsync() exception: asynchronous script timeout: result was not received in 10 seconds
  (Session info: chrome=58.0.3029.110)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-72-generic x86_64)
10:20:05 WARN PuppetWebBridge proxyWechaty() exception: asynchronous script timeout: result was not received in 10 seconds
  (Session info: chrome=58.0.3029.110)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-72-generic x86_64)
10:20:05 WARN PuppetWebBridge contactRemark() does not work on contact is not a friend
10:20:05 WARN PuppetWeb contactRemark(@bf4f2823cfc66120cb567dcd907e9ad9, [0]) bridge.contactRemark() return false
```

It seems that the Contact is not a "friend" although I have `await request.accept( )` before setting alias.
`contact.refresh()` does not work either.

**Comment by zixia** [comment]
@xhh It's my first time that sees an `asynchronous script timeout` message on Wechaty, and I do not know why.

If you could provide steps to reproduce this message, that would help a lot.
