### ISSUE TITLE
send message to all groups would be failed when count of group exceed 100

### ISSUE THREAD

**Issue by yanboshu** [Chatie/wechaty#412]
給联系人（群组）群发时，超过100个群就会收到错误。

{"log":"08:58:49 INFO Bot talk: 发送消息过于频繁，可稍后再试。\r\n","stream":"stdout","time":"2017-04-17T08:58:49.536821537Z"}

测试代码：
```
.on('message', async msg => {
  // Skip message from self, or inside a room
  if (msg.self()) return 
  log.info('Bot', 'from: %s', msg.from().name())
  var bot = '北冥Master'
  if (msg.from().name().indexOf(bot) == -1) return
  var content = msg.content()
  const rooms = await Room.findAll()
  for(var i = 0; i < rooms.length; i++) {
      console.log('room info: ', rooms[i])
      var ro = new Room(rooms[i].id)
      ro.say(content + ' : ' + i)
  }
})
```

**Comment by yanboshu** [comment]
如果群联系人很少，比如20个，连续发送5次也会报错。

**Comment by zixia** [comment]
The throttled rate of Wechat Server will affect your bot a lot in this scenario.

I suggest you to have a look at our Wiki page about this topic: https://github.com/Chatie/wechaty/wiki/Throttled-Rate-for-WeChat-Say-Event , and I'll really appreciate if you could contribute more about this.

Thanks.

**Comment by lijiarui** [comment]
@yanboshu hi, you didn't set interval for each message send, which I have told in wechaty developers' home....

try `setTimeout()` or `await sleep(1000)`

**Comment by zixia** [comment]
Duplicated with #596
