### ISSUE TITLE
ERR PuppetWeb initBridge() exception: execute proxyWechaty(init) error: 503, init() without a ready angular env

### ISSUE THREAD

**Issue by amyhuangxbd** [Chatie/wechaty#414]
### Actual behavior
Starting Wechaty ... NodeJS Version=v7.9.0v0.7.62

Working directory: /bot
Please make sure you had installed all the NPM modules which is depended by your bot script.
Executing ts-node mybot.ts
10:42:59 INFO Wechaty v0.7.62 initializing...
10:43:06 ERR PuppetWeb initBridge() exception: execute proxyWechaty(init) error: 503, init() without a ready angular env
10:43:06 ERR PuppetWeb init() exception: Error: execute proxyWechaty(init) error: 503, init() without a ready angular env
    at Bridge.<anonymous> (/wechaty/src/puppet-web/bridge.ts:71:15)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/dist/src/puppet-web/bridge.js:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
10:43:06 ERR Wechaty init() exception: execute proxyWechaty(init) error: 503, init() without a ready angular env
(node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: execute proxyWechaty(init) error: 503, init() without a ready angular env
(node:23) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Steps to reproduce the behavior (and fixes, if any)
1. system: centOS
2.The wechaty has run normally for about 3 days, But it doesn't trigger scan event when it logout.
   so I restart the wechaty by run : docker run -ti --volume="$(pwd)":/bot --rm zixia/wechaty mybot.ts
3. Then it cannot restart, and show the err PuppetWeb initBridge() exception: execute proxyWechaty(init) error: 503, init() without a ready angular env
4. I have tried to fix this issue by docker pull zixia/wechaty, however, it seems that doesn't work.
could you please help to review this issue, thanks.

**Comment by zixia** [comment]
You might run into issue #329 

There's a possible reason at here: 
https://github.com/Chatie/wechaty/issues/329#issuecomment-289647688

If you keep experiencing this issue, do a Docker restart, or even a Linux restart might help? I'm not sure.

Please let me know if you could find more information about this, good luck!

**Comment by zixia** [comment]
Duplicated with #329

**Comment by amyhuangxbd** [comment]
This issue didn't reproduce after I restart the centOS system.

**Comment by zixia** [comment]
Yes, this is a random issue and we still know nothing about the reason.

Please post to #329 if you noticed any new clues about this. Thanks.
