### ISSUE TITLE
Concat.avatar()  faild ,when hostname changed from https://wx.qq.com to https://wx2.qq.com

### ISSUE THREAD

**Issue by iRabbit** [Chatie/wechaty#418]
Sometimes  when I  login wechat ,the hostname changed and Concat.avatar() wouldn't work.
I found that the host in the broswer is "https://wx2.qq.com" ,and in method Concat.avatar()  "avatarUrl = https://wx.qq.com/xxxxxxx"  . maybe something wrong  here.

In the source code , cookie.hostname() default valued "http://wx.qq.com" ,and will not changed after first login wechat ,no matter  what the real hostname is.

**Comment by zixia** [comment]
Thanks for reporting this.

I think we should consider a new method like `PuppetWebBrowser.hostname()`, which can get current hostname that the web wechat is running on.

**Comment by zixia** [comment]
I have changed the `hostname()` function to get the current domain from the Browser since v0.8.110.

This issue should not exist anymore, but it needs to be confirmed.

@iRabbit @jinliming2 @kk3hi3123 Could you help me to test that?

**Comment by zixia** [comment]
Close this issue due to no response for more than two weeks.
