### ISSUE TITLE
windows run program send images throw out error

### ISSUE THREAD

**Issue by 51168** [Chatie/wechaty#427]
hi  guys @zixia ,I'll have trouble with you again. 
i run mac os success;but Move the code to windows is error.

**env:**
1.local area network
node v6.10.0
npm 3.10.10
wechaty v0.7.68

save image code:

function saveFile(message) {
  const filename = message.filename()
  console.log('IMAGE local filename: ' + filename)

  const fileStream = fs.createWriteStream(filename)

  console.log('start to readyStream()')
  message.readyStream()
          .then(stream => {
            stream.pipe(fileStream)
                  .on('close', () => {
                    console.log('finish readyStream()')
                  })
          })
          .catch(e => console.log('stream error:' + e))
}

![image](https://cloud.githubusercontent.com/assets/9131618/25268989/67971610-26ad-11e7-940b-c401ed437a3d.png)

i run explame/media-file-bot.ts ,When i made the picture, get the same error.
npm run ts-node example\media-file-bot.ts

![image](https://cloud.githubusercontent.com/assets/9131618/25269625/1740be52-26b0-11e7-97b8-5d977a0d3cdc.png)

Can you help me twice?

**Comment by zixia** [comment]
Hi @51168 ,

Your information is not enough for us to diagnostic.

Please provide more detailed code & logs with plain text(do not use picture/screenshot).

**Comment by 51168** [comment]
sorry, i later.

i only run demo And send the picture

`npm run ts-node example/media-file-bot.ts`

errors follows:

`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'ts-node',
1 verbose cli   'example\\media-file-bot.ts' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 verbose run-script [ 'prets-node', 'ts-node', 'postts-node' ]
5 info lifecycle wechaty@0.7.68~prets-node: wechaty@0.7.68
6 silly lifecycle wechaty@0.7.68~prets-node: no script for prets-node, continuing
7 info lifecycle wechaty@0.7.68~ts-node: wechaty@0.7.68
8 verbose lifecycle wechaty@0.7.68~ts-node: unsafe-perm in lifecycle true
9 verbose lifecycle wechaty@0.7.68~ts-node: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Administrator\Desktop\weixin\wechaty\node_modules\.bin;C:\Program Files (x86)\Common Files\NetSarang;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\ProgramData\ComposerSetup\bin;F:\phpStudy\php55n;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\Administrator\AppData\Roaming\Composer\vendor\bin;C:\Python27\Scripts;C:\Python27;C:\Users\Administrator\AppData\ChromeDriver;C:\Users\Administrator\AppData\Roaming\npm;C:\Program Files\Docker Toolbox
10 verbose lifecycle wechaty@0.7.68~ts-node: CWD: C:\Users\Administrator\Desktop\weixin\wechaty
11 silly lifecycle wechaty@0.7.68~ts-node: Args: [ '/d /s /c', 'ts-node "example\\media-file-bot.ts"' ]
12 silly lifecycle wechaty@0.7.68~ts-node: Returned: code: 1  signal: null
13 info lifecycle wechaty@0.7.68~ts-node: Failed to exec ts-node script
14 verbose stack Error: wechaty@0.7.68 ts-node: `ts-node "example\media-file-bot.ts"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid wechaty@0.7.68
16 verbose cwd C:\Users\Administrator\Desktop\weixin\wechaty
17 error Windows_NT 10.0.10240
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "ts-node" "example\\media-file-bot.ts"
19 error node v6.10.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error wechaty@0.7.68 ts-node: `ts-node "example\media-file-bot.ts"`
22 error Exit status 1
23 error Failed at the wechaty@0.7.68 ts-node script 'ts-node "example\media-file-bot.ts"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the wechaty package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ts-node "example\media-file-bot.ts"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs wechaty
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls wechaty
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by zixia** [comment]
Hi @51168 

Thanks for posting the output.

But I have no idea about the reason because I have not development on windows for serveral weeks.

My suggestion is:

1. Have a look on Appveyor CI, which is run on Windows and without any problem. See: <https://github.com/Chatie/wechaty/wiki/Test>
2. Talk with @xjchengo because he's using Windows and had fix a bug for Wechaty at #416

**Comment by 51168** [comment]
thanks, @zixia。tomorrow  i'll try it. not very familiar with nodejs, i will learn

**Comment by zixia** [comment]
@51168 Hope you doing well.

I'll close this issue because it's not active for a week. 

Please feel free to submit a new issue if you still have any problem.

Thanks!
