### ISSUE TITLE
build my docker image ,but run error 

### ISSUE THREAD

**Issue by ditunes** [Chatie/wechaty#432]
### Provide Your Network Information
1. Where is the location of your server? (i.e. City, or In/Out China)
china
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?
no just my macbook 
### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 

wechaty@0.7.71 check-node-version /wechaty
 check-node-version --node ">= 6.9"

node: 7.9.0
npm: 4.4.4
yarn: 0.22.0

  #### Wechaty Doctor

  1. Wechaty version: 0.7.71
  2. Linux x64 version 4.9.12-moby memory 711/1999 MB
  3. Docker: true
  4. Node version: v7.9.0
  5. Tcp IPC TEST: PASS
  6. Chromedriver: ChromeDriver 2.25 (5a911c1ac99b36efadff2041357740080cc27220)`
-------
this is my dockerfile
`FROM zixia/wechaty
WORKDIR /bot
COPY ./dist/ .
COPY package.json .
RUN npm install 

ENTRYPOINT [ ]
CMD [ "node","index.js" ]`

### Expected behavior
can execute normally

### Actual behavior
has errors as follows
01:47:06 INFO Wechaty v0.7.71 initializing...
01:47:13 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
01:47:13 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: valid() driver.getSession() timeout(halt?)
01:47:13 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
01:47:13 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 1
01:47:20 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
01:47:20 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: valid() driver.getSession() timeout(halt?)
01:47:20 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
01:47:20 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 2
01:47:27 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
01:47:27 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: valid() driver.getSession() timeout(halt?)
01:47:27 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
01:47:27 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 3
01:47:34 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
01:47:34 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: valid() driver.getSession() timeout(halt?)
01:47:34 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
01:47:34 WARN PuppetWebBrowserDriver initChromeDriver() not valid after retry: 4 times: Error: initChromeDriver() got invalid driver
    at BrowserDriver.<anonymous> (/wechaty/dist/src/puppet-web/browser-driver.js:117:35)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/dist/src/puppet-web/browser-driver.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
01:47:34 ERR PuppetWebBrowser init() exception: initChromeDriver() got invalid driver
01:48:06 WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.9.12-moby x86_64)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.9.12-moby x86_64)
(node:1) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
01:48:13 WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: unknown error: Chrome failed to start: exited abnormally

**Comment by zixia** [comment]
Duplicated with #147 

Please wait for us to release an `onbuild` version of docker image, because that would be easy to use.

**Comment by ditunes** [comment]
so  now i cannot build a docker image to run my bot ? or has other method?

**Comment by zixia** [comment]
yes you can.

I'll write about this when I have time.

**Comment by ditunes** [comment]
Could you give me some notice ,maybe i can try haha

**Comment by zixia** [comment]
@ditunes You can have a try by 

```diff
FROM zixia/wechaty
WORKDIR /bot
COPY ./dist/ .
COPY package.json .
RUN npm install

- ENTRYPOINT [ ]
- CMD [ "node","index.js" ]
+ CMD [ "npm", "start" ]
```

Remember to make sure you have a `start` script defined in your package.json file.

**Comment by zixia** [comment]
See: https://github.com/Chatie/wechaty/issues/147#issuecomment-296448684

**Comment by zixia** [comment]
Hi did the new `onbuild` image solve your issue?

I'll close this one, if you still have the problem related to the docker, please reply under #147 instead.
