### ISSUE TITLE
requesting a new QR code cost more than 2 minutes

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#434]
### Expected behavior
When wechat logs you out, and then asks you to login again by showing qrcode, it should within 2 minutes(watchdog timeout)

### Actual behavior
It will cost me 15min to show qrcode
`requesting a new QR code every 20 minutes` by @dcsan

**Comment by zixia** [comment]
Please look into the log when you experience this issue next time, and let me know if there's a line like this:

```shell
02:18:17 WARN PuppetWebWatchdog monirotScan() refresh browser for no food of type scan after 10 mins
02:18:17 VERB PuppetWebBrowser refresh()
```

Thanks.

**Comment by lijiarui** [comment]
yes, it got the line.

```
02:23:46 WARN PuppetWebWatchdog monirotScan() refresh browser for no food of type scan after 10 mins
```
each qrcode internal is 16 minutes.

**Comment by zixia** [comment]
I had changed this interval from 10 to 4 minutes because you said normaly it's 2 minutes, so we refresh after 4 minutes if there's no new QRCode coming.
> it should within 2 minutes

Please use the latest docker image to continue monitoring it, thanks.

**Comment by lijiarui** [comment]
> 2 minutes

I'm not sure why is should within 2 minutes...

I said 2 minutes, because I saw watchdog says 120s....

**Comment by lijiarui** [comment]
the same bot and same environment, log as follows:
```
03:20:47 WARN PuppetWebWatchdog monirotScan() refresh browser for no food of type scan after 10 mins
```

and qrcode internal is 15 minutes.

**Comment by dcsan** [comment]
one related feature request here is to DISABLE requesting a new QRCode. 

when some bots are running on a remote server, they will lose connection, and keep requesting new QRCodes for a long period, those personal Wechat accounts will get blocked.

**Comment by zixia** [comment]
@dcsan Thanks for pointing this out.

But what if someone uses his computer at the office to use web wechat, and then forget to turn the computer off, left it there, and have two weeks vacation?

Will his account be blocked? If so, I do not think that make sense.

**Comment by dcsan** [comment]
so the behavior here of calling for a new QRcode is identical to normal browser usage?

however, we have experienced this with accounts getting blocked.
perhaps it could be that multiple bots were running on the same VPS/IP# or there is some other behavior that makes chromedriver different (eg the *nix user agent?)

FWIW the bot accounts were also used on mobile phones, as normal/real wechat accounts.

**Comment by zixia** [comment]
Yes, the behavior of Wechaty _should_ be identical to a normal browser.

I think there must be some other behavior.(but not like the user agent & IP).

Maybe we should set up a place to collect the __bot blocked__ events from our developers, so we can discuss it deeper. ;-p

**Comment by JasLin** [comment]
@zixia  hi bro, just take a look at the source.  some information here maybe useful.

if it's ```isAssociationLogin```, wxwebapp will display a confirm button instead of qrcode, in this case , chatie will no trigger onScan event.

```html
      <div class="association"
          ng-class="{show: isAssociationLogin && !isBrokenNetwork}">
        <img class="img"
            mm-src="{{userAvatar}}"
            alt=""
            src="//res.wx.qq.com/a/wx_fed/webwx/res/static/img/2KriyDK.png" />
        <p ng-show="isWaitingAsConfirm"
            class="waiting_confirm">请在手机点击确认登录</p>
        <a href="javascript:;"
            ng-show="!isWaitingAsConfirm"
            ng-click="associationLogin()"
            class="button button_primary">登录</a>
        <a href="javascript:;"
            ng-click="qrcodeLogin()"
            class="button button_default">切换帐号</a>
      </div>
```
[source](https://github.com/Chatie/webwx-app-tracker/blob/fd3f24b16fad86e40c2ba6ea1ff7e1ce8b75fe1a/formatted/index.html#L112-L127)

click this button will trigger that  a confirm button display on mobile app, and click it to login.
```js
associationLogin: function(e) {
              var a = t.defer()
                , n = i.API_webwxpushloginurl + "?uin=" + encodeURIComponent(e);
              return $.ajax({
                  url: n
                  , dataType: "json"
                })
                .done(function(e) {
                  0 == e.ret ? a.resolve(e) : a.reject(e)
                })
                .fail(function() {
                  a.reject()
                }), a.promise
            }
```
[source](https://github.com/Chatie/webwx-app-tracker/blob/fd3f24b16fad86e40c2ba6ea1ff7e1ce8b75fe1a/formatted/webwxApp.js#L3815)


what is isAssociationLogin?
```js
...
e.isAssociationLogin = parseInt(a.getCookie("login_frequency") || 0) >= 2
...
```
it seems if we are login one wechat account  on one computer/browser too frequency, this account will be identify as a ```isAssociationLogin``` account?
[source](https://github.com/Chatie/webwx-app-tracker/blob/fd3f24b16fad86e40c2ba6ea1ff7e1ce8b75fe1a/formatted/webwxApp.js#L586)

**Comment by lijiarui** [comment]
cool！ I guess this is the reason why the internal is 15min-20min

**Comment by lijiarui** [comment]
@JasLin Let's continue to track this issue at #636

This issue will be closed. Thanks!
