### ISSUE TITLE
MediaMessage#filename() should not use timestamp as part of the filename

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#465]
@mukaiu 

### Issue:
I send image using the following code
```ts
room.say(new MediaMessage('pic/2017-05-02_19:06:34_#1_<李佳芮:机器人测试群>_4683734942127496021.jpg'))
```
It got the following error:
```shell
(node:59483) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open 'pic/2017-05-02_19:06:34_#1_<李佳芮:机器人测试群>_4683734942127496021.jpg'
(node:59483) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

While when I change the image name to `test1.jpg` as following, all works well.
```ts
room.say(new MediaMessage('pic/test1.jpg'))
```

### More Info:

**Scene:**
When anyone send a pic in a room, I download the pic and then send the pic.

**Download pic function:**
I use the following code to generat  file  `2017-05-02_19:06:34_#1_<李佳芮:机器人测试群>_4683734942127496021.jpg` in [media-file-bot.ts](https://github.com/Chatie/wechaty/blob/master/example/media-file-bot.ts) 

```ts
function saveMediaFile(message: Message) {
  const filename = message.filename()
  console.log('IMAGE local filename: ' + filename)

  const fileStream = createWriteStream(filename)

  console.log('start to readyStream()')
  message.readyStream()
          .then(stream => {
            stream.pipe(fileStream)
                  .on('close', () => {
                    console.log('finish readyStream()')
                  })
          })
          .catch(e => console.log('stream error:' + e))
}
```

**Comment by lijiarui** [comment]
It is because `:` instead of Chinese char....

linux change the `:` to `\` so it cannot get the right filename.

When I change the filename from `2017-05-02_19:06:34_#1_<李佳芮:机器人测试群>_4683734942127496021.jpg` to `2017-05-02_19_06_34_#1_<李佳芮_机器人测试群>_4683734942127496021.jpg` , it fix...

So I suggest to change add the following function in function filename:

```
filename = filename.replace(/:/g, '_')
```
@zixia  What do you think about it?

**Comment by zixia** [comment]
I think your suggestion is not the right direction to fix this.

We should always find the way to solve the problem, instead of sidestepping it.

**Comment by zixia** [comment]
However, I will git rid of the verbose `2017-05-02_19:06:34_#1_<李佳芮:机器人测试群>_` part in the filename, because it's just a test string when I write this piece of code.

We should only keep the original file name of the attachment file, if no original name, then we use the ID of the file.

**Comment by zixia** [comment]
After this commit, I believe we still can not send a filename with `:` character. So I'll leave this issue open.

**Comment by lijiarui** [comment]
yes, and filename should not contain Chinese char here, it still has some strange error...

When the code read the file name, it will catch an error, but when I using copy the file name and paste it in the code, it works well...

```ts
room.say(new MediaMessage('pic/2017-05-02_20_02_18_#4_<李佳芮_机器人测试群>_4343051853187432187.jpg'))
    room.say(new MediaMessage('pic/2017-05-02_20_02_17_#4_<李佳芮_机器人测试群>_4343051853187432187.jpg'))
```

**Comment by lijiarui** [comment]
Let me dig in it and find the final result... I'm sorry....

**Comment by lijiarui** [comment]
Finally.... I found the reason....

the following code using the same `m`, and I console.log(m.filename()) in each function, but their filename() are **different**! 

```ts
if (m.type() === MsgType.IMAGE) {
        await saveMediaFile(m)
        await imgBroadcast(m)
      }
```

```log
saveMediaFile_2017-05-02_20_18_18_#1_<李佳芮_机器人测试群>_2643239037259386854.jpg
imgBroadcat_2017-05-02_20_18_18_#1_<李佳芮_机器人测试群>_2643239037259386854.jpg
```

Because your filename function contains time, the two function execute time has 1 interval.... so one filename is `2017-05-02_20_18_18` and the other is `2017-05-02_20_18_18`

So if your filename remove time info, it should fix.

**Comment by zixia** [comment]
:+1: 

Then you can try the latest master code, which is not using the time as the filename anymore.

**Comment by zixia** [comment]
Please create an new issue if you still have problems.
