### ISSUE TITLE
message.mentioned() 返回为空数组

### ISSUE THREAD

**Issue by dadairui** [Chatie/wechaty#478]
```
.on('message', function(m) {
    const contactList = m.mentioned()
    console.log(contactList)
})
```

为什么这里打印出来的contactList 一直为空，但是打印出来的mention string是正确的

**Comment by zixia** [comment]
Duplicated with #477 

The reason of contactList empty is: the room is not `ready()` yet.

Sometimes even worse: the room maybe is in fake `ready()` state because the data is still syncing with the server.

Will continue track over there, this issue will be closed.

**Comment by huan** [comment]
This issue might be related to https://github.com/wechaty/wechaty-puppet-wechat/issues/141
