### ISSUE TITLE
may be not need .vscode folder, need .editorconfig

### ISSUE THREAD

**Issue by huhuanming** [Chatie/wechaty#489]
`.vscode/settings.json
`
```json
{
    "editor.tabSize": 2, 
    "typescript.tsdk": "./node_modules/typescript/lib"
}
```
the `editor.tabSize` can controlled by` .editorconfig`.
but now, the user setting and workspace setting polluted by it.

It seemed like a good idea that remove `.vscode` and add `.editorconfig` file

**Comment by zixia** [comment]
Yes, I agree with you that tabSize is not necessary at here, and should be removed.(I just did it)

However, vscode/settings.json have some feature that not supported by .editorconfig.

I.e: `files.exclude` to hide directory/files in the ide interface.

**Comment by huhuanming** [comment]
but the project does not use these features, such as `files.exclude`.
Modern editors support `.editorconfig`.

Wouldn't it make more sense?

**Comment by huhuanming** [comment]
```
Dust to dusts, dirt to dirts, ash to ashes
```
tabaSize to `.editorconfig`, `files.exclude` to `.tsconfig`

all not to `.vscode/settings.json`

**Comment by zixia** [comment]
No, I do not agree with you about this because of `file.exclude`@`.vscode/settings.json` is totally different as `exclude`@`tsconfig.json`. ;-)

See: [How do I hide certain files from the sidebar in Visual Studio Code?](stackoverflow.com/questions/30140112/how-do-i-hide-certain-files-from-the-sidebar-in-visual-studio-code)

**Comment by huhuanming** [comment]
sorry,  i make a mistake on it.

**Comment by zixia** [comment]
@huhuanming No problem buddy, and thank you for the warm-hearted suggestion.

Please feel free to let me know if you have any other good ideas. :)

**Comment by huhuanming** [comment]
sweet, thx.
