### ISSUE TITLE
Some types of media file is saved as a 0 byte file.

### ISSUE THREAD

**Issue by atfa** [Chatie/wechaty#504]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)
China
2. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?
My own Surface Pro 4 running windows 10
### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 

> wechaty@0.8.12 doctor C:\dev\wechaty
> npm run check-node-version && ts-node bin/doctor

> wechaty@0.8.12 check-node-version C:\dev\wechaty
> check-node-version --node ">= 6.9"

node: 6.10.2
npm: 4.6.1
yarn: 0.23.4

  #### Wechaty Doctor

  1. Wechaty version: 0.8.12
  2. Windows_NT x64 version 10.0.15063 memory 8851/16310 MB
  3. Docker: false
  4. Node version: v6.10.2
  5. Tcp IPC TEST: PASS
  6. Chromedriver: Error: spawnSync chromedriver ENOENT

### Expected behavior

I use wechat sending some files to the bot. I want my bot can save them on my hard disk.

### Actual behavior

IMAGES and VOICES can be saved as a correct file that can open with other applications. But VIDEOS , MicroVIDEOS and other format files such as *.doc or *.pdf will be saved as a 0 byte file. Only a filename. Nothing in it.
All the code is simple and same: saveMediaFile(m)

### Steps to reproduce the behavior (and fixes, if any)

1. Send a file to the bot. Maybe you should use wechat webapp of wechat Android APP.
2. Check the file saved on the hard disk.

### Paste the full output logs here with `WECHATY_LOG=silly` set

Sorry I do not know how to  `WECHATY_LOG=silly` . I just use node .\dist\mybot.js to run my bot.

**Comment by zixia** [comment]
1. It's strange that your chromedriver can not be found by doctor: (perhaps there's bug under win32)

> Chromedriver: Error: spawnSync chromedriver ENOENT

2. Get the debug output by run:

```shell
$ node_modules\.bin\cross-env WECHATY_LOG=silly node .\dist\mybot.js
```

**Comment by atfa** [comment]
1. I have installed a Chrome on my system. Node opens Chrome directly.

2. output:
09:24:27 SILL PuppetWebEvent onServerDing(heartbeat@browser)
09:24:27 SILL PuppetWebWatchdog onFeed: 60000, HEARTBEAT[heartbeat@browser]
09:24:27 SILL StateSwitch Puppet:target() - live
09:24:27 SILL StateSwitch Puppet:inprocess() false
09:24:27 SILL PuppetWebWatchdog clearWatchDogTimer() [45] seconds left
09:24:27 SILL PuppetWebWatchdog setWatchDogTimer(60000, HEARTBEAT:[heartbeat@browser])
09:24:27 SILL PuppetWebWatchdog monitorScan(HEARTBEAT)
09:24:27 SILL PuppetWebWatchdog autoSaveSession()
09:24:27 SILL PuppetWebWatchdog memoryCheck() free: 11689 MB, require: 4 MB
09:24:42 SILL PuppetWebEvent onServerDing(heartbeat@browser)
09:24:42 SILL PuppetWebWatchdog onFeed: 60000, HEARTBEAT[heartbeat@browser]
09:24:42 SILL StateSwitch Puppet:target() - live
09:24:42 SILL StateSwitch Puppet:inprocess() false
09:24:42 SILL PuppetWebWatchdog clearWatchDogTimer() [46] seconds left
09:24:42 SILL PuppetWebWatchdog setWatchDogTimer(60000, HEARTBEAT:[heartbeat@browser])
09:24:42 SILL PuppetWebWatchdog monitorScan(HEARTBEAT)
09:24:42 SILL PuppetWebWatchdog autoSaveSession()
09:24:42 SILL PuppetWebWatchdog memoryCheck() free: 11631 MB, require: 4 MB
09:24:57 SILL PuppetWebEvent onServerDing(heartbeat@browser)
09:24:57 SILL PuppetWebWatchdog onFeed: 60000, HEARTBEAT[heartbeat@browser]
09:24:57 SILL StateSwitch Puppet:target() - live
09:24:57 SILL StateSwitch Puppet:inprocess() false
09:24:57 SILL PuppetWebWatchdog clearWatchDogTimer() [46] seconds left
09:24:57 SILL PuppetWebWatchdog setWatchDogTimer(60000, HEARTBEAT:[heartbeat@browser])
09:24:57 SILL PuppetWebWatchdog monitorScan(HEARTBEAT)
09:24:57 SILL PuppetWebWatchdog autoSaveSession()
09:24:57 SILL PuppetWebWatchdog memoryCheck() free: 11546 MB, require: 4 MB
09:25:12 SILL PuppetWebEvent onServerDing(heartbeat@browser)
09:25:12 SILL PuppetWebWatchdog onFeed: 60000, HEARTBEAT[heartbeat@browser]
09:25:12 SILL StateSwitch Puppet:target() - live
09:25:12 SILL StateSwitch Puppet:inprocess() false
09:25:12 SILL PuppetWebWatchdog clearWatchDogTimer() [46] seconds left
09:25:12 SILL PuppetWebWatchdog setWatchDogTimer(60000, HEARTBEAT:[heartbeat@browser])
09:25:12 SILL PuppetWebWatchdog monitorScan(HEARTBEAT)
09:25:12 SILL PuppetWebWatchdog autoSaveSession()
09:25:12 SILL PuppetWebWatchdog memoryCheck() free: 11544 MB, require: 4 MB
09:25:18 SILL Message constructor() SN:2
09:25:18 SILL Message ready()
09:25:18 SILL Contact ready()
09:25:18 SILL Contact ready()
09:25:18 VERB PuppetWebEvent onServerMessage() EMOTICON/IMAGE/VIDEO/VOICE/MICROVIDEO message
09:25:18 SILL Message constructor() SN:3
09:25:18 SILL MediaMessage ready()
09:25:18 SILL Message ready()
09:25:18 SILL Contact ready()
09:25:18 SILL Contact ready()
09:25:18 VERB PuppetWebBridge getMsgVideo(3729739627497591386)
09:25:18 VERB PuppetWebBridge proxyWechaty(getMsgVideo, 3729739627497591386)
09:25:18 SILL PuppetWebBridge execute()
09:25:18 SILL PuppetWebBrowser Browser.execute("return typeof WechatyBro === "undefined"")
09:25:18 SILL StateSwitch Browser:target() - open
09:25:18 SILL StateSwitch Browser:current() - open
09:25:18 SILL PuppetWebBridge execute()
09:25:18 SILL PuppetWebBrowser Browser.execute(" const callback = arguments[arguments.length - 1] const isAsync = (typeof  ... ")
09:25:18 SILL StateSwitch Browser:target() - open
09:25:18 SILL StateSwitch Browser:current() - open
09:25:18 SILL Contact alias()
09:25:18 SILL Contact alias()
09:25:18 SILL Contact alias()
Message is VIDEO.
IMAGE local filename: files/3729739627497591386.mp4
09:25:18 SILL MediaMessage ready()
09:25:18 SILL Message ready()
09:25:18 SILL Contact ready()
09:25:18 SILL Contact ready()
09:25:18 VERB PuppetWebBridge getMsgVideo(3729739627497591386)
09:25:18 VERB PuppetWebBridge proxyWechaty(getMsgVideo, 3729739627497591386)
09:25:18 SILL PuppetWebBridge execute()
09:25:18 SILL PuppetWebBrowser Browser.execute("return typeof WechatyBro === "undefined"")
09:25:18 SILL StateSwitch Browser:target() - open
09:25:18 SILL StateSwitch Browser:current() - open
09:25:18 SILL PuppetWebBridge execute()
09:25:18 SILL PuppetWebBrowser Browser.execute(" const callback = arguments[arguments.length - 1] const isAsync = (typeof  ... ")
09:25:18 SILL StateSwitch Browser:target() - open
09:25:18 SILL StateSwitch Browser:current() - open
09:25:18 VERB PuppetWebBrowserCookie read()
09:25:18 SILL PuppetWebBrowserCookie read() webwx_auth_ticket,pgv_si,pgv_pvi,webwxuvid,last_wxuin,login_frequency,MM_WX_NOTIFY_STATE,MM_WX_SOUND_STATE,mm_lang,last_wxuin,login_frequency,wxloadtime,wxplugink
ey,wxuin,wxsid,webwx_data_ticket
09:25:27 SILL PuppetWebEvent onServerDing(heartbeat@browser)
09:25:27 SILL PuppetWebWatchdog onFeed: 60000, HEARTBEAT[heartbeat@browser]
09:25:27 SILL StateSwitch Puppet:target() - live
09:25:27 SILL StateSwitch Puppet:inprocess() false
09:25:27 SILL PuppetWebWatchdog clearWatchDogTimer() [46] seconds left
09:25:27 SILL PuppetWebWatchdog setWatchDogTimer(60000, HEARTBEAT:[heartbeat@browser])
09:25:27 SILL PuppetWebWatchdog monitorScan(HEARTBEAT)
09:25:27 SILL PuppetWebWatchdog autoSaveSession()
09:25:27 SILL PuppetWebWatchdog memoryCheck() free: 11540 MB, require: 4 MB
09:25:42 SILL PuppetWebEvent onServerDing(heartbeat@browser)
09:25:42 SILL PuppetWebWatchdog onFeed: 60000, HEARTBEAT[heartbeat@browser]
09:25:42 SILL StateSwitch Puppet:target() - live
09:25:42 SILL StateSwitch Puppet:inprocess() false
09:25:42 SILL PuppetWebWatchdog clearWatchDogTimer() [46] seconds left
09:25:42 SILL PuppetWebWatchdog setWatchDogTimer(60000, HEARTBEAT:[heartbeat@browser])
09:25:42 SILL PuppetWebWatchdog monitorScan(HEARTBEAT)
09:25:42 SILL PuppetWebWatchdog autoSaveSession()
09:25:42 SILL PuppetWebWatchdog memoryCheck() free: 11365 MB, require: 4 MB

**Comment by atfa** [comment]
Atfer I deployed wechaty on my centos, the problem is all the same : the saved mp4 file size is 0, while the mp3 file and jpg file are ok.

**Comment by ChenJavascript** [comment]
I have the same problem

**Comment by zixia** [comment]
@ChenJavascript Could you confirm there's always ok with your first login, and there's always fail after your second login?

**Comment by ChenJavascript** [comment]
@zixia I've tried many times.
I'm sure the second logon always fails,and save the 0kb after uploading the picture for second times.

**Comment by museroom** [comment]
I have same problem. Android videos/microcode all downloaded as 0 bytes. While iPhone iPod videos are ok.

**Comment by zixia** [comment]
Could you provide the details about the issue, for example: 
1. which kind of the MsgType is the video that can not be downloaded? and 
1. which kind of the MsgType is the video that will be download without the problem?

We need more information in details If we want this problem to be solved, thanks.

**Comment by museroom** [comment]
I think this problem is related to insane  censorship and bot-detection. 
I solved the problem by moving server outside asia.

**Comment by zixia** [comment]
Great to hear that!

Could you please close this issue now?
