### ISSUE TITLE
Cannot set alias of Contact Object getting from `message.from()` method when Contact is not a friend

### ISSUE THREAD

**Issue by MaxLi1994** [Chatie/wechaty#509]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China) **In China**
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using? **AliYun**

### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 

    Starting Wechaty v0.8.14 with Node.js v7.10.0 ...

    > wechaty@0.8.14 doctor /wechaty
    > npm run check-node-version && ts-node bin/doctor

    > wechaty@0.8.14 check-node-version /wechaty
    > check-node-version --node ">= 6.9"

    node: 7.10.0
    npm: 4.5.0
    yarn: 0.23.4

    #### Wechaty Doctor

    1. Wechaty version: 0.8.14
    2. Linux x64 version 4.4.52-boot2docker memory 106/995 MB
    3. Docker: true
    4. Node version: v7.10.0
    5. Tcp IPC TEST: PASS
    6. Chromedriver: ChromeDriver 2.25 (5a911c1ac99b36efadff2041357740080cc27220)

### Expected behavior
 
Expect Setting an alias for a non-friend Contact(we're in the same group but not friends to each other) in a room to be successful.
As far as I know, setting remark of a non-friend Contact in a chat group is supported in web wechat.

### Actual behavior

see logs below.

### Steps to reproduce the behavior (and fixes, if any)
    asssert(message.room() !== null);
    const sender = message.from();
    await sender.alias('new alias'); // error

### Paste the full output logs here with `WECHATY_LOG=silly` set

    08:17:17 SILL Contact alias()
    08:17:17 SILL Contact alias(sender-94417c10-37b4-11e7-a589-ebef4b9f78cf)
    08:17:17 VERB PuppetWebBridge proxyWechaty(contactRemarkAsync, @c83f2569fca67c304c5758d9a5631889, sender-94417c10-37b4-11e7-a589-ebef4b9f78cf)
    08:17:17 SILL PuppetWebBridge execute()
    08:17:17 SILL PuppetWebBrowser Browser.execute("return typeof WechatyBro === "undefined"")
    08:17:17 SILL StateSwitch Browser:target() is open
    08:17:17 SILL StateSwitch Browser:current() is open
    08:17:17 SILL PuppetWebBrowser Browser.executeAsync( const callback = arguments[arguments.length - 1]
        const isAsync = (typeof )
    08:17:17 SILL StateSwitch Browser:target() is open
    08:17:17 SILL StateSwitch Browser:current() is open
    08:17:17 WARN PuppetWebBrowser executeAsync() exception: javascript error: contactRemarkAsync() can not found UserName @c83f2569fca67c304c5758d9a5631889
    Jav
    08:17:17 WARN PuppetWebBridge executeAsync() exception: javascript error: contactRemarkAsync() can not found UserName @c83f2569fca67c304c5758d9a5631889
    JavaScript stack:
    Error: contactRemarkAsync() can not found UserName @c83f2569fca67c304c5758d9a5631889
        at contactRemarkAsync (<anonymous>:859:13)
        at eval (eval at executeAsyncScript (:329:5), <anonymous>:6:16)
        at eval (eval at executeAsyncScript (:329:5), <anonymous>:11:8)
        at executeAsyncScript (<anonymous>:329:26)
        at <anonymous>:345:29
        at callFunction (<anonymous>:237:33)
        at <anonymous>:247:23
        at <anonymous>:248:3
    (Session info: chrome=56.0.2924.76)
    (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.4.52-boot2docker x86_64)
    08:17:17 VERB PuppetWebBridge proxyWechaty(contactRemarkAsync, @c83f2569fca67c304c5758d9a5631889, sender-94417c10-37b4-11e7-a589-ebef4b9f78cf) 
    08:17:17 WARN PuppetWebBridge proxyWechaty() exception: javascript error: contactRemarkAsync() can not found UserName @c83f2569fca67c304c5758d9a5631889
    JavaScript stack:
    Error: contactRemarkAsync() can not found UserName @c83f2569fca67c304c5758d9a5631889
        at contactRemarkAsync (<anonymous>:859:13)
        at eval (eval at executeAsyncScript (:329:5), <anonymous>:6:16)
        at eval (eval at executeAsyncScript (:329:5), <anonymous>:11:8)
        at executeAsyncScript (<anonymous>:329:26)
        at <anonymous>:345:29
        at callFunction (<anonymous>:237:33)
        at <anonymous>:247:23
        at <anonymous>:248:3
    (Session info: chrome=56.0.2924.76)
    (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.4.52-boot2docker x86_64)
    08:17:17 ERR PuppetWebBridge contactRemarkAsync() exception: javascript error: contactRemarkAsync() can not found UserName @c83f2569fca67c304c5758d9a5631889
    JavaScript stack:
    Error: contactRemarkAsync() can not found UserName @c83f2569fca67c304c5758d9a5631889
        at contactRemarkAsync (<anonymous>:859:13)
        at eval (eval at executeAsyncScript (:329:5), <anonymous>:6:16)
        at eval (eval at executeAsyncScript (:329:5), <anonymous>:11:8)
        at executeAsyncScript (<anonymous>:329:26)
        at <anonymous>:345:29
        at callFunction (<anonymous>:237:33)
        at <anonymous>:247:23
        at <anonymous>:248:3
    (Session info: chrome=56.0.2924.76)
    (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.4.52-boot2docker x86_64)
    08:17:17 WARN PuppetWeb contactRemark(@c83f2569fca67c304c5758d9a5631889, sender-94417c10-37b4-11e7-a589-ebef4b9f78cf) rejected: javascript error: contactRemarkAsync() can not found UserName @c83f2569fca67c304c5758d9a5631889
    JavaScript stack:
    Error: contactRemarkAsync() can not found UserName @c83f2569fca67c304c5758d9a5631889
        at contactRemarkAsync (<anonymous>:859:13)
        at eval (eval at executeAsyncScript (:329:5), <anonymous>:6:16)
        at eval (eval at executeAsyncScript (:329:5), <anonymous>:11:8)
        at executeAsyncScript (<anonymous>:329:26)
        at <anonymous>:345:29
        at callFunction (<anonymous>:237:33)
        at <anonymous>:247:23
        at <anonymous>:248:3
    (Session info: chrome=56.0.2924.76)
    (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.4.52-boot2docker x86_64)
    08:17:17 ERR Contact alias(sender-94417c10-37b4-11e7-a589-ebef4b9f78cf) rejected: javascript error: contactRemarkAsync() can not found UserName @c83f2569fca67c304c5758d9a5631889
    JavaScript stack:
    Error: contactRemarkAsync() can not found UserName @c83f2569fca67c304c5758d9a5631889
        at contactRemarkAsync (<anonymous>:859:13)
        at eval (eval at executeAsyncScript (:329:5), <anonymous>:6:16)
        at eval (eval at executeAsyncScript (:329:5), <anonymous>:11:8)
        at executeAsyncScript (<anonymous>:329:26)
        at <anonymous>:345:29
        at callFunction (<anonymous>:237:33)
        at <anonymous>:247:23
        at <anonymous>:248:3
    (Session info: chrome=56.0.2924.76)
    (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.4.52-boot2docker x86_64)

**Comment by zixia** [comment]
Thanks for your helpful issue description, the problem is very clear and meaningful.

Wechaty should be able to support any operation that web wechat can do. If web wechat could make a remark for a contact that not a friend, then we should be able to fix this issue.

My question is: Could you double confirm that the remark you made could restore after session change?(i.e. logout & login again in web wechat)

> setting remark of a non-friend Contact in a chat group is supported in web wechat

**Comment by MaxLi1994** [comment]
😢  Unfortunately, the remark I put on non-friend Contact did not remain after session change.

Guess this is as far as we can go for now in trying to permanently identify everyone in a room.

**Comment by zixia** [comment]
@MaxLi1994 sad to hear that...

Then this issue is clear now: the operation could not be supported at this point. Pity!
