### ISSUE TITLE
When a room member change it's nickname in a room, bot cannot detect it.

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#528]
When a contact change it's nickname in a room, using room.member() cannot get the contact successfully.

I guess this is because the following code in `room.ts` doesn't refresh contact
```ts
  private async readyAllMembers(memberList: RoomRawMember[]): Promise<void> {
    for (const member of memberList) {
      const contact = Contact.load(member.UserName)
      await contact.ready()
    }
    return
  }
```

**Comment by zixia** [comment]
Yes, you are right.

**Comment by lijiarui** [comment]
Maybe we should plan to do `refresh` in period inside the Wechaty Framework. Because all of room info should update.

It can add an enhancement.

**Comment by zixia** [comment]
I will not disagree with you because I'd also like to consider adding a `refresh` in a period.

However, it will need not only a proposal in detail to discuss, but also more design patterns should be considered. I'd like to leave those works as an exercise to the community.

**Comment by zixia** [comment]
Currently, we have to use `room.sync()` as a workaround. 

If anyone has better ideas, please let me know by leave comments under this issue, and I'll reopen it for discussion.
