### ISSUE TITLE
[enhancement] Cant send a wechat page link to the room.

### ISSUE THREAD

**Issue by kungfu-software** [Chatie/wechaty#537]
Please help to resolve the issue. 
I am actually relay in two chatrooms. The share link wont work

 - Room1: Somebody shared a wechat page link
![screen shot 2017-05-23 at 5 55 51 pm](https://cloud.githubusercontent.com/assets/700550/26343909/217da962-3fe1-11e7-8384-53d6d7b4ae26.png)

 - Room2: The bot should send the same info into chat room 2
![screen shot 2017-05-23 at 5 53 01 pm](https://cloud.githubusercontent.com/assets/700550/26343792/b1f67d4e-3fe0-11e7-8592-d846fe045273.png)

**Comment by zixia** [comment]
I don't think this operation is supported by Web Wechat.

Could you please confirm that Web Wechat could do this?

If it can, then we could plan to implement this to Wechaty;
if it can not, then Wechaty also can not do this, unless we have new Puppet like AndroidPuppet.

**Comment by kungfu-software** [comment]
Maybe the web wechat dont support this directly. But when I posted on the phone, the web wechat can view the link content.

**Comment by zixia** [comment]
Future discussion about this can move to #718 

I'll close this issue for now.
