### ISSUE TITLE
Friend Request rate limit exceeded

### ISSUE THREAD

**Issue by kungfu-software** [Chatie/wechaty#540]
### Expected behavior
Automatically send out FriendRequest and waiting others to accept.

### Actual behavior
Always return false. And others dont receive the friend request

### Code Snippet
```
function sendFriendRequest(room, msg) {

    if (!room) {
        console.log('Bot', 'there is no room topic Test111(yet)');
        return;
    }

    let contacts = room? room.memberList({}) : [];
    console.log(contacts.length);

    if (msg && contacts && "/Friends" === msg.content()) {
        for (let i = 0; i < contacts.length; i ++) {
            let contact = contacts[i];
            let request = new FriendRequest();
            request.send(contact, "哈咯， 我是晴晴, 请加我好友 拜托哟!!!")
                .then( result => {
                    console.log("Request Send", result);
                })
                .catch(e => {
                     console.log('Bot', 'Friend Request rejected: %s', e.stack);
                }) 
            //console.log("FriendRequest sent to:", contact.name());
        }
    }
```

### Logs
![screen shot 2017-05-23 at 7 49 37 pm](https://cloud.githubusercontent.com/assets/700550/26348732/ff0260e8-3ff0-11e7-9203-80f6b4b509be.png)

**Comment by kungfu-software** [comment]
It's NOT on a FRIEND EVENT. I just want to find all the people in the room and send them Friend Request.

**Comment by zixia** [comment]
Thanks for reporting this.

I'm not sure about your problem but return false means Web Wechat had rejected your request.

I suggest you have a read about this wiki article, and limit your request rate first: 
<https://github.com/Chatie/wechaty/wiki/Throttled-Rate-for-WeChat-Web-API>

**Comment by kungfu-software** [comment]
Strange. I can't even manually add friends from web wechat now.
<img width="864" alt="screen shot 2017-05-23 at 10 12 08 pm" src="https://cloud.githubusercontent.com/assets/700550/26353710/0293e362-4005-11e7-93c1-7ad06c9c9472.png">

### In the chrome dev console

```
{"BaseRequest":{"Uin":1823145502,"Sid":"/lz3PL1inK/INaHv","Skey":"@crypt_c6728aa0_df4e4e9495de19c05cd9d49d0126aa28","DeviceID":"e921142703205690"},"Opcode":2,"VerifyUserListSize":1,"VerifyUserList":[{"Value":"@6fd45455805c09be05b5363f70f40568feae7479b99c21eb9cdb2e933c62d970","VerifyUserTicket":""}],"VerifyContent":"我是晴晴","SceneListCount":1,"SceneList":[33],"skey":"@crypt_c6728aa0_df4e4e9495de19c05cd9d49d0126aa28"}
Name
```

**Comment by lijiarui** [comment]
I guess you get true result for the some of friendrequest but failed of the remaining one. 

Webwechat can only accept about 80 requests one day. But if you didn't send with an interval, it will fail soon.

**Comment by kungfu-software** [comment]
Thanks for the reply @lijiarui . How can i set an interval?

**Comment by kungfu-software** [comment]
I manually set the interval like these. But still failed after about 20 users added.
```
function sendFriendRequest(room, msg) {

    if (!room) {
        console.log('Bot', 'there is no room topic Test111(yet)');
        return;
    }

    let contacts = room? room.memberList({}) : [];
    console.log('Contacts Size:', contacts.length);

    let content = msg.content();
    if (msg && contacts && /\/Friends\[\d{1,3}-\d{1,3}\]/.test(content)) {

        var i1 = content.indexOf('[') +1;
        var i2 = content.indexOf(']');
        var subContent = content.substring(i1, i2);
        var splits = subContent.split('-');
    
        for (let i = splits[0]; i < splits[1]; i ++) {
            let contact = contacts[i];
            let request = new FriendRequest();            
            request.send(contact, "哈咯， 我是晴晴, 请加我好友 拜托哟!!!")
                .then( result => {
                    console.log("Friend Request Send ", contact.name(), result);
                })
                .catch(e => {
                     console.log('Bot', 'Friend Request rejected: %s', e.stack);
                })
            sleepFor(5000);
        }
    }

    /*
    Room.find({ topic: /^FRIENDS/i })
        .then(room => {
            
        })
        .catch(e => {
            console.log('Bot', 'Room.find rejected: %s', e.stack);
        })
    */

}

function sleepFor( sleepDuration ){
    var now = new Date().getTime();
    while(new Date().getTime() < now + sleepDuration){ /* do nothing */ } 
}
```

**Comment by kungfu-software** [comment]
I figured out how to make delay. Seems a lot better now at this stage. 👍 
Thanks for the help @zixia  @lijiarui

**Comment by zixia** [comment]
Great to hear that.

The API rate limitation is a big pitfall that many developers will get into.

If you had figure out the solution, would you like to share your idea to the community?

If you will, I'd  like to invite you to write a blog post to talk how to deal with this problem.

Looking forward to your reply, thanks!

**Comment by kungfu-software** [comment]
Basically use the following code snippet
```javascript
function delay(ms: number) {
    return new Promise<void>(function(resolve) {
        setTimeout(resolve, ms);
    });
}

async function asyncAwait() {

    for (let i = 0; i < 10; i++) { 
        console.log("Knock", i);
        await delay(5000);
    }
}

asyncAwait();
```

**Comment by zixia** [comment]
Actually, we have already an `await Wechaty.sleep(5000)`  for sleep 5 seconds, you could rewrite your code to:

```ts
async function asyncAwait() {

    for (let i = 0; i < 10; i++) { 
        console.log("Knock", i);
        await Wechaty.sleep(5000);
    }
}

asyncAwait();

```

Then would you like to write a blog post to introduce how to use `Wechaty.sleep()` to make delay when calling Wechaty methods? 

A short post to introduce the problem you met and the solution you made is enough. :)

**Comment by kungfu-software** [comment]
@zixia Thanks for the post. Learnt sth today again. 
Yeah, more than happy to do it if it will help others.

**Comment by zixia** [comment]
@kungfu-software Great to hear that you'd like to draft one to help others!

The preferred language is in English, but you could write in any language as you like.

I have just invited you at our chatie blog repository, looking forward to your article, thanks!
