### ISSUE TITLE
如何直接获取contact类的实例,主动给联系人发消息?

### ISSUE THREAD

**Issue by OUZICHENG** [Chatie/wechaty#544]
绝对新手,真心学习,求大神解救.
最近才接触docker,有点混乱.都说docker和虚拟机很像,如果按虚拟机的思维,我在虚拟机上开了服务,我的代码要在虚拟机上跑,我应该把代码放到虚拟机虚拟出来的文件系统里面.所以有docker,我的源代码要在 docker上跑似乎也应该放到 docker内.我网上查到有两种方法可以解决这个问题,一个是wechaty现在用的,将本地的一个目录映射到docker 内,源代码就直接写在docker外面就好.另一种方法是使用工具像登录虚拟机一样登录到docker容器内,把代码放进去,或者干脆在生产环境中原代码和原基本镜象一起打成一个新的镜象,并把这个镜象跑起来.我是这样理解的,不知道是否正确.

基于上面的一点点了解,那么问题来了:
1,按wechaty一在推荐的解决方案,业务代码与wechaty功能部分分开,业务源代码放在容器外的文件卷中,映射到 docker内.这样处理后业务代码与放置于镜象内的wechaty代码的目录层级关系是什么样的.且说开去,以后别的项目中可能还会有一样的问题,所在想了解清楚.

我本地docker运行了这个例子(https://blog.chatie.io/developer/2017/03/20/added-hot-reload-for-bots.html)的代码,一切正常.
但是我有两个疑惑:a,在此例子的原代码中并不有node-modules目录,就是或是其他和node相关的文件,几乎就是纯js.问题是他可以在index.js中直接使用这样的代码获取了三个模块

> `const fs = require('fs');
const path = require('path');
const Wechaty = require('wechaty').default;`
两个系统模块和一个wechaty模块,这是不是说业务代码可以访问原 docker镜象中的系统信息和代码,而且似乎当前目录(宿主机业务源代码所在目录)与容器中的文件在同一个目录(逻辑上).
但是我使用下面语句却获取不了contact模块,提示找不到模块,为什么?

> `const Contact = require('./contact').default;`

所参照例子中作者明明用相似方法拿到了wechaty实例哟.

#################################################
上面说容器外映射到容器的代码可以直接调用里面的资源,但是另外一个测试又好你说根本用不到里面的代码.是这么回事,我git了整个项目原代码到本地.终端进入到examle目录后,用上面同样的运行docker的命令执行contact-bot.ts. 一开始没成功,后面我反回项目根目录运行 npm install后再重复上面的运行步骤,成功了.之后我将同一个contact.ts文件复制到了一个新的目录,同样的运行,发现就没有反应了,不会出来扫码提示,直接告诉退出了.
这是不是说明,容器外业务代码的ts到js还是要依赖本地的支持的,只有转成了可以直接运行的js,才能被容器内调用,而容器内原来搭建好的转换功能并不能被外面的业务代码使用.是这样的吗?

#######################################################

纠结了好几天.想想要不就还是用虚拟机思维吧,我进去,直接把代码放进去,看看行不行,但是这个没试成功.不是运行不成功,是压根不知道怎么将文件复制到容器内.因为wechaty的镜像要运行起来,似乎总要给他个本地的js或ts,这个js或ts运行正常行就直接进了业务中,使用attach登录docker看到的也是一样的界面,看不到文件目录也不说不上复制,只要终止运行,自动又退出来了.自己太白,没办法,最后只好来求救了!!!

说了这么多,我其实想做的就是可以在没有人找我的情况下,自动给某个或某些人发信息.不是被动回复,主动出击.这似乎要先能过contact获得联系人,再用say方法发出.
对了,在contact-bot.ts中有示例是从

> `import

 {
  Config,
  Contact,
  Wechaty,
  log,
} from '../'`
拿到的,但是隔着docker当真不知道从哪里引入啊

考虑过就用npm包吧,可以看到目录,可是不甘心啊,就是想问个明白

上面这些东西可能很白,但是请大神们不要太黑,小心脏受不鸟.天亮了,我先睡会儿

**Comment by zixia** [comment]
```js
const Contact = require('./contact').default;
```

This is not recommended.

Using `import { Contact } from 'wechaty'` instead.

**Comment by OUZICHENG** [comment]
@zixia got it, thanks a lot.
