### ISSUE TITLE
How to keep the bot online?

### ISSUE THREAD

**Issue by OUZICHENG** [Chatie/wechaty#548]
I found that when my bot account exited from my mobile phone wechat, it exited from web wechat immidiately.  when I send some message to the bot, it did nothing.

Is this happend on you too  or just for me?

How to  keep it  work while the account doesn't login on my phone

**Comment by OUZICHENG** [comment]
[https://blog.chatie.io/developer/2016/12/04/gitchat-lijiarui-interview.html](url)
> 问：机器人断线概率高么？

答：从我自己使用的情况来看，Wechaty这个框架很稳定，但是网页微信定期会把你踢下去，所以需要重新登录。Wechaty有一个功能，就是通过wechaty.instance({ profile: ‘test’ }) 会把你的session信息存到一个test.wechaty.json的文件中，如果掉线了，会自动重新登录，test可以随便换名字哈。

**Comment by OUZICHENG** [comment]
修改了
`const bot = Wechaty.instance()`
为:
`const bot = Wechaty.instance({
  profile: 'my-bot'
})`
手机微信退出,机器人依然立即退出,目录中有生成my-bot.wechaty.json文件,但是未见机器人重新登录.手机登录其他账号给机器人账号发信息应该没有反应.

**Comment by zixia** [comment]
This is not related to Wechaty, it's a limitation of Wechat.

However, we could use some trick to avoid this.

See: https://github.com/Urinx/WeixinBot/issues/46#issuecomment-217595998

**Comment by OUZICHENG** [comment]
@zixia 
好吧,看来我又天真了,你们牛,原来还是有其他人用中文提问的,以为这里人都是英语专业的说.感谢耐心回复,辛苦了,有空把qq也一起搞了吧,这样两个就可以直接通信了,哈哈,再次感谢

**Comment by zixia** [comment]
To support QQ is a cool idea! 

Hope there will be someone make a pull request to implement it someday.

**Comment by zhuaoyuan** [comment]
> 答：从我自己使用的情况来看，Wechaty这个框架很稳定，但是网页微信定期会把你踢下去，所以需要重新登录。Wechaty有一个功能，就是通过wechaty.instance({ profile: ‘test’ }) 会把你的session信息存到一个test.wechaty.json的文件中，如果掉线了，会自动重新登录，test可以随便换名字哈。
In what situation will test.wechaty.json work?
I have tried wechaty.instance({ profile: ‘test’ }) in my script(with wechaty 0.13.12), however my bot still logs out and cannot automatically login every several days.
The log after logging out is below:
> 10:08:46 WARN PuppetWeb initScanWatchdog() on(reset) lastFood: https://login.weixin.qq.com/qrcode/YYHbZ_eWXQ==, timeLeft: 120000
