### ISSUE TITLE
如何转发转发转发多媒体信息,谢谢

### ISSUE THREAD

**Issue by OUZICHENG** [Chatie/wechaty#549]
我又来了啊,只不过这回不是半夜月黑风高的时候.
我已经可以接收,发送信息了,手机装了个多开软件,两个微信已经能玩起来.一任性就把小冰和微软自己的公众号给连在了一起,他们聊得挺嗨.但是问题又来了:

如果他们一方发送图片(除系统默认表情外的图片或第三方表情),语音或是图文素材的时候,另一方就会开始抱怨说看不懂了(眼睛都看花了).原因是经过bot转接的信息都给转成了字符串,完全失去了原来的意思.

尝试过的解决办法:
参考[这篇文章](https://blog.chatie.io/2017/04/13/support-message-type-of-image-and-video.html),知道wechaty可以发送图片和视频,但是似乎一定要指定视频所在的本地路径.

这时我想如果bot能在接收信息时对信息类型进行判断,如果是多媒体信息则记录其多媒体文件地址,备用,这问题似乎就能解决. 但是查看Message类的相关api后无从下手
[message.content](https://github.com/Chatie/wechaty/wiki/API#messagecontentcontent-string-string) :返回类型为字符,也就是之前为什么发出图片语音都转成字符的原因.如何从这一堆字符里找到有用的信息,找到信息中的多媒体文件呢?
[Message.filename()](https://github.com/Chatie/wechaty/wiki/API#messagefilenamestring):似乎是一个不错的选择,从说明上来看,就是返回多媒体文件的文件名,正是所需要的. 但是试了下,发图片的时候报错,说不是媒体文件.难道我用法不对,给个例子可好?或者说图片不算媒体文件,什么类型才算呢,是我想多了吗?

关于信息转接的用途,为什么想做这个事,肯定不只是想逗小冰玩
1. 群中出现敏感信息时自动转发给管理员进行处理
2.想要统一发布的多媒体信息,直接从管理员的微信发给机器人账号,让它自动去向其联系人发送.

天天来烦一下,不要打我啊

**Comment by zixia** [comment]
Two answers:

1. Do it today:
    1. Download media file to the local file first. example: https://github.com/Chatie/wechaty/blob/master/example/media-file-bot.ts
    1. Send media file from the local file.
1. Do it in the future: 
    * Duplicated with #200

**Comment by OUZICHENG** [comment]
good job. 你都在研究怎么改进框架,我是到手的框架都不会用,哎. 你们英语随口就来,我只有看的分, 差距怎么就这么大呢? 先玩下目前方案,期待将来的方案,等我上手了给你搞定qq(不要太当真,呵呵)

**Comment by zixia** [comment]
Glad to hear that! 

Looking forward to your PuppetQQ! :+1:
