### ISSUE TITLE
[求]可用人工智能会话api接入和部署方案

### ISSUE THREAD

**Issue by JesonOU** [Chatie/wechaty#564]
接触wechaty后,开始作死想给bot接人工智能api,可能不怎么实用,但是看着很厉害的样子,反正是学习,所以就作一下啊.折腾许久,不是一两小时,是一两个星期,始终没有合适的方案,所以想请诸位大神给点建议.

**希望达到的要求:**
1,支持中文自然语言分析,这个最基本的,不然我怎么跟它聊呢?
2,易用,有现成的多轮会话设置界面,不要让我从头做起,做不来,55555
3,高可用,服务稳定.不要显得反映迟钝,或识别不准
4,支持比较大量的调用,不一定要支持产品级别,但是不能一个循环下来就一个月不能再用吧.

好像就这么点要求吧,过分吗?

目前试过的方案:
1,api.ai,支持中文,易用性足够,反正我好像会用吧,识别也还算准吧.主要的问题就是远在他国,有时候不挂vpn都打不开.服务器上好像不能装vpn吧.这个速度问题怎么解决?我还有没有实际部署过,如果能解决速度问题,我还是比较喜欢这个的.哪位大神实践过,介绍下经验.把服务器放国外,用起来会不会一样很慢,服务器与api.ai访问快了,可是服务器与国内微信服务器呢?
2,yige.ai,这是个国内服务,支持中文也易用,但是发现识别不是很准确.比如说设置了一个查库存的场景,例句有"xxxx家的库存还有多少"但是测试的时候发现只要输入"的"甚至于"我的","你的","好的"等有的的短语竟然都命中,无语.另外是词库(entities)没有自动添加选项,命名中相同位置出现的词语如果在词库中没有出现,意图命中,动作参数却返回空.实际场景中你有一千个产品似乎都要把他们的编号录入词库.人功智能系统与数据中心不应该结合太紧吧,这也是为什么更喜欢api.ai的原因.除此之外,他们还自己提供了绑定微信公众号的服务,很不幸的是存在回复延迟或不回复的问题.有时候问两次回复一次,有时问三次都不回,尚未测试自己搭服务,调用api,自己实现回复微信公众平台有没有这样的问题,识别不准就让人心寒了
3,阿里有公测中的智能对话系统.但是不支持多轮会话,纯粹的问题系统,一问一答的形式,也没有动作等概念,无法从问题中提取信息做后台处理.就是一个问题的多种问法,对应一个问题的多种固定回复,系统识别自动调用.不满足要求
4,百度提供自然语言识别sdk,但是没有设置平台,没有对话管理平台,而且免费调用次数有限制
5,腾讯有bot.qq.com.看着好像很牛b,但是纯粹是个有病的平台.多次提交申请都没有后续,也不说要不要钱,也不说什么要求才能开通,反正就是没人理你.点完创建自己的机器人,提示会有人联系你,后面鬼都没一个

有没有大神有好的解决方案,给讲讲呗,给你小红花

**Comment by lijiarui** [comment]
I use api.ai as my NLU tool, and use it on digital ocean, then it can resolve VPN problem because I use digital ocean's Singapore VPS.

I use both api.ai and luis in my bot.

China service has 芝麻机器人 and yige.ai

**Comment by zixia** [comment]
@OUZICHENG This topic is very valuable to be discussed because this is a very typical scenario.

I encourage you to try the different solutions and find out which one is the best for you.

**Comment by OUZICHENG** [comment]
@zixia 哦哦,行吧,有机会都部署上试试吧.docker不熟悉,正在恶补呢.始终感觉,docker只是本地搭建了一个独立的运行环境,而且这个环境很容易迁移到其他支持docker的物理机上,所以开发时,测试时,生产环境都用的一个docker image,主要是迁移快.但是对开发,我说的是写代码似乎没什么用.你不可能把ide装进docker内,还是在本地写,你在本地写源代码的时候引用别人的库还是得npm或是yarn到本地,不然ide就会提示你 个找不到那个找不到.只有在写好程序源代码之后,要运行了才有docker的事.这些都是题外话.接触wechaty,发现还有很多东西不会啊,坑

**Comment by OUZICHENG** [comment]
@lijiarui 谢谢提供借鉴,有机会我都会尝试一下.有成品吗?推荐来看看效果,谢谢

**Comment by lijiarui** [comment]
by the way, api.ai need VPN, but [luis.ai](https://www.luis.ai/) made by Microsoft doesn't need VPN, about 2-3 seconds will get a respond.

**Comment by lijiarui** [comment]
This [repo](https://github.com/lijiarui/lx-api-ai) is my demo use wechaty and api.ai & luis.ai for test.

you can run [api-ai-wechaty.ts](https://github.com/lijiarui/lx-api-ai/blob/master/api-ai-wechaty.ts) to have a test about api.ai

you can run [luis-wechaty..ts](https://github.com/lijiarui/lx-api-ai/blob/master/luis-wechaty.ts) to have a test about luis.ai

This just a test, please ignore the dirty code

**Comment by OUZICHENG** [comment]
@lijiarui thanks. I am interested in why you two guys speak English is so well

**Comment by OUZICHENG** [comment]
@lijiarui @zixia 刚刚试了下luis.ai.识别还是比较准确的,个人体验.但是它好像不支持多轮会话是吗?好像不能设置上下文,仅仅能做单句的语意分析,可以获取用户提供的信息,没有action概念(不过这个可以用intent名字代替,参数齐不齐可以自己判断然后给出提示,不是很大问题.另外好像有调用次数限制,一个月1000次,如果要多就要购买.两位都有研究过这个ai,我上面说的这些没有错吧,我英文不好,不要骗我哟,你看我大半夜在学习的份上

**Comment by lijiarui** [comment]
YouGood summary！ And I use superscript with luis&api.ai.  

http://superscriptjs.com/

**Comment by kungfu-software** [comment]
This is a good article talking about different bots and services. It's quite amazing.
You can have a good read, if you have time. 
https://stanfy.com/blog/advanced-natural-language-processing-tools-for-bot-makers/ 

Happy coding.

**Comment by zixia** [comment]
@kungfu-software Amazing article, thanks for sharing!

**Comment by zixia** [comment]
Hi @JesonOU , 

Your question is great and I would like to invite you to share what you learned to the community after you got some insight from it.

However, I'll close this issue from now, because it's not related to the Wechaty Issue.

Please feel free to submit a new issue if you have other problems. Thanks.
