### ISSUE TITLE
在 Windows Server 上初始化的时候，chromedriver 报错。

### ISSUE THREAD

**Issue by kawnnor** [Chatie/wechaty#574]
Windows Server 版本：
Microsoft Windows Server 2008 R2 (64bit)

Chrome 版本：
58.0.3029.81 (32bit)

Microsoft Windows [版本 6.1.7600]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>node -v
v6.10.3

C:\Users\Administrator>npm -v
3.10.10

D:\wxbot\node_modules\.bin>chromedriver -v
ChromeDriver 2.29.461591 (62ebf098771772160f391d75e589dc567915b233)

D:\wxbot>node robot.js
18:37:49 INFO Wechaty v0.8.91 initializing...
18:37:57 WARN PuppetWebBrowserDriver validDriverSession() driver.getSession() ti
meout(halt?)
18:37:57 WARN PuppetWebBrowserDriver validDriverSession() driver.getSession() ex
ception: validDriverSession() driver.getSession() timeout(halt?)
18:37:57 WARN PuppetWebBrowserDriver getChromeDriver() got invalid driver at ttl
 2
18:38:04 WARN PuppetWebBrowserDriver validDriverSession() driver.getSession() ti
meout(halt?)
18:38:04 WARN PuppetWebBrowserDriver validDriverSession() driver.getSession() ex
ception: validDriverSession() driver.getSession() timeout(halt?)
18:38:04 WARN PuppetWebBrowserDriver getChromeDriver() got invalid driver at ttl
 1
18:38:11 WARN PuppetWebBrowserDriver validDriverSession() driver.getSession() ti
meout(halt?)
18:38:11 WARN PuppetWebBrowserDriver validDriverSession() driver.getSession() ex
ception: validDriverSession() driver.getSession() timeout(halt?)
18:38:11 WARN PuppetWebBrowserDriver getChromeDriver() got invalid driver at ttl
 0
18:38:11 WARN PuppetWebBrowserDriver getChromeDriver() invalid after ttl expired
: Error: got invalid driver at ttl 0
    at BrowserDriver.<anonymous> (D:\wxbot\node_modules\wechaty\dist\src\puppet-
web\browser-driver.js:133:35)
    at next (native)
    at fulfilled (D:\wxbot\node_modules\wechaty\dist\src\puppet-web\browser-driv
er.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
18:38:11 ERR PuppetWebBrowser init() exception: got invalid driver at ttl 0
18:38:11 WARN PuppetWebBrowser quit() exception: Cannot read property 'close' of
 undefined
18:38:11 WARN PuppetWebBrowser driver.quit() exception: Cannot read property 'cl
ose' of undefined
18:38:11 ERR PuppetWeb initBrowser() exception: got invalid driver at ttl 0
18:38:11 ERR PuppetWeb init() exception: Error: got invalid driver at ttl 0
    at BrowserDriver.<anonymous> (D:\wxbot\node_modules\wechaty\dist\src\puppet-
web\browser-driver.js:133:35)
    at next (native)
    at fulfilled (D:\wxbot\node_modules\wechaty\dist\src\puppet-web\browser-driv
er.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
18:38:11 INFO Robot error: Error: got invalid driver at ttl 0
18:38:11 ERR Wechaty init() exception: Cannot read property 'clear' of undefined

18:38:11 ERR Bot init() fail: TypeError: Cannot read property 'clear' of undefin
ed
18:38:11 ERR Wechaty quit() must run on a inited instance.

**Comment by zixia** [comment]
Could you confirm that you have already a Chrome browser installed?

**Comment by kawnnor** [comment]
重启服务器，问题解决了。
