### ISSUE TITLE
room-join event cannot get inviteeList when name of invitee contains some emoji

### ISSUE THREAD

**Issue by kk3hi3123** [Chatie/wechaty#588]
### Provide Your Network Information

Where is the location of your server? (i.e. City, or In/Out China)
Hong Kong

### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 

npm ERR! missing script: doctor

node -v: v8.0.0
npm -v: 5.0.0

### Expected behavior

When users join the room, send a welcome message and friend requests to them.

### Actual behavior

InviteeList cannot get the contact object that name contains some emoji.

I have tested for some cases. Some emoji like ring bell has no problem. 
obj: 
   { ......
     name: '丁叮🛎',
     ...... }

But some other emoji like pumpkin cannot run correctly. 
obj: 
   { ......
     name: '丁叮`<img class="emoji emoji1f383" text="_web" src="/zh_CN/htmledition/v2/images/spacer.gif" />`',
     ...... }
(This object is got in 'message' event by message.from(). By the way, on 'message' gets no problem with pumpkin emoji)

### Steps to reproduce the behavior (and fixes, if any)

```
bot.on('room-join', (room, inviteeList, inviter) => {
        const nameList = inviteeList.map(c => c.name()).join(',');
        room.say(`歡迎新成員 ${nameList} 加入`);
    })
```

In this case, '歡迎新成員  加入' will be displayed in the room.

### Paste the full output logs here with `WECHATY_LOG=silly` set

[log.txt](https://github.com/Chatie/wechaty/files/1084340/log.txt)

**Comment by kk3hi3123** [comment]
I changed line 337 (or nearby?) in room.js from:
`const filterValue = queryArg[filterKey];`
into
 `const filterValue = util_lib_1.default.stripEmoji(util_lib_1.default.plainText(queryArg[filterKey]));`

It seems ok. I have only tested 3-4 times. Hope it helps.

**Comment by zixia** [comment]
Yes, it helps.

However, what's the version of Wechaty were you using?

It seems we did it at https://github.com/Chatie/wechaty/blob/master/src/room.ts#L481 
```ts
    const filterValue: string  = UtilLib.stripEmoji(queryArg[filterKey])
```

And ISSUE #64 is related to emoji need to be striped problem.

**Comment by kk3hi3123** [comment]
Oh, my Wechaty version is 0.8.91.

**Comment by zixia** [comment]
So did update to the latest version fix your issue?

**Comment by kk3hi3123** [comment]
No error and only warning is showed in version 0.8.110
But the contact still cannot be got

**Comment by zixia** [comment]
I just add your solution to the code base, please check the latest version(0.8.114 or above). Also refer to #64

**Comment by kk3hi3123** [comment]
The error still comes out seldom. Here is the warning message in another case:

`12:16:44 WARN PuppetWebFirer fireRoomJoin() reject() inviteeContactList: , inviterContact: kk3hi3123<img class="emoji emoji1f383" text="_web" src="/zh_CN/htmledition/v2/images/spacer.gif" />
`
In this case, the name of invitee has no emoji but the contact object still cannot be got. I have tried to call room.memberList() but the invitee is not included in the list. And contact.avatar() returns "Error: Can not get avatar: not ready".

**Comment by lijiarui** [comment]
@kk3hi3123   Yes, I got a lot of this error too, because I use group-qrcode-image to invite people into the room, if people join in the room too fast(like 10 persons join in the room in one second), and it will get the error.

**Comment by lijiarui** [comment]
And sometimes even got the following error:
```
12:11:11 ERR PuppetWebFirer firmRoomJoin() inivter not found for 32e0cbe1-950e-4c2c-9fd5-90e927d6825b , `room-join` & `join` event will not fired
```

I suggest if cannot get inviter, it will fired room-join event too, then we can know exactly how many people join the room.

**Comment by zixia** [comment]
Moved to <https://github.com/Chatie/wechaty-puppet-puppeteer/issues/27>
