### ISSUE TITLE
[enhancement] Add timezone in to Dockerfile

### ISSUE THREAD

**Issue by kis87988** [Chatie/wechaty#594]
Right now, we can not declare a environment (ENV) varialbe to set timezone
My idea is:
> 1. apk add tzdata
> 2. set ENV localTime America/Los_Angeles
> 3. RUN cp /usr/share/zoneinfo/${localTime} /etc/localtime
but I could not figure it out how to make it run in the dockerfile

The alternating method is:
create container first by docker pull/docker run and then docker enter to the container.
do the following: 
> 1. apk add -U tzdata
> 2. cp /usr/share/zoneinfo/America/Los_Angeles /etc/localtime

Hope someone can make it into dockerfile.

**Comment by zixia** [comment]
Thanks for purposing!

I believe setting timezone is a necessary feature that Wechaty Docker Image should support.

**Comment by zixia** [comment]
Support to set `TZ` for timezone at Wechaty version 0.13.13 or above at: https://github.com/Chatie/wechaty/commit/61c277c4b3400c155544fec59f8e2659238352f4

Usage:

```shell
docker run -e TZ='Asia/Shanghai' zixia/wechaty
```
