### ISSUE TITLE
Can't get wechaty up and running using phantomjs

### ISSUE THREAD

**Issue by cherry-geqi** [Chatie/wechaty#60]
I'm using the latest branch. While executing

``` bash
WECHATY_HEAD=phantomjs ts-node example/ding-dong-bot.ts
```

it complains:

```
INFO Wechaty v#git[bdac338 BREAKING CHANGE: `room-join`/`room-leave`/`join`/`leave` events now only emit `contactList: Contact[]` as params. no `contact: Contact` anymore.] initializing...
WARN PuppetWebBrowser execute() exception: {"errorMessage":"Unexpected token ','","request":{"headers":{"Accept":"application/json; charset=ut
...
WARN PuppetWebBrowser driver() exception: no driver
```

Did I miss something?

**Comment by zixia** [comment]
Hi @cherry-geqi ,

due to #28 , I'm not sure whether phantomjs could work with wechaty v0.4.x & 0.5.x(master).

but your error message seems there's another bug with phantomjs. I'll check it later.

If you want to run wechaty now, I recommend you to use `chrome` head, because it's well tested and work without any problem.

good luck.

**Comment by zixia** [comment]
@cherry-geqi 

Thank you for the PR of https://github.com/wechaty/wechaty/pull/97

Could you confirm the phantomjs HEAD will work for Wechaty after your PR?

**Comment by cherry-geqi** [comment]
Yes, it works.

**Comment by zixia** [comment]
awesome. I'll turn on the phantom head unit tests then.

Cheers!

**Comment by zixia** [comment]
Hi @cherry-geqi ,

I had just run the demo bot: `WECHATY_LOG=silly WECHATY_HEAD=phantomjs npm run demo`, it can show the QR Code right. 

But after I scanned, it keeps showing the error: `VERB PuppetWebEvent onServerLogin: browser not full loaded(15), retry later`. 

Could you try to run the above command for me to confirm whether it's ok at your side? 

Appreciate.

**Comment by zixia** [comment]
Hi, @cherry-geqi , 

Could you please have a check for me for the demo bot? I need your help.

BTW, as you are reading the WechatyBro source code, you might be interested in this repository: webwxApp source code update tracker: https://github.com/wechaty/webwx-app-tracker/commits/master/formatted/webwxApp.js , just FYI.

**Comment by cherry-geqi** [comment]
OK, I'll check this late today.

**Comment by cherry-geqi** [comment]
Sometimes phantomjs sends `webwxnewloginpage` request but gets no response. When this happens, wechaty keeps logging `VERB PuppetWebEvent onServerLogin: browser not full loaded(15), retry later`. Right now I have no idea why the server sometimes responses and sometimes don't. I have even added some custom headers and changed userAgent to Chrome to emulate the behavior of Chrome but no luck.

Here are the snapshots:
![36f146ad-472e-4a46-a3e9-167397ce63f0](https://cloud.githubusercontent.com/assets/13705685/20705682/e3cd5a1a-b65e-11e6-85ec-9b030abe85d5.png)
![8497a1ef-4a12-482b-9000-be0f3c5b88ea](https://cloud.githubusercontent.com/assets/13705685/20705698/eec1a598-b65e-11e6-9e3c-efe5772a8101.png)

**Comment by zixia** [comment]
@cherry-geqi thanks for the information about phantomjs. It seems we need to dig deeper for it.

According to your post, did you mean when you are using `WECHATY_HEAD=phantomjs`, sometimes it works and sometimes not? If so, what's the success rate of your test? for example, will get X success after retry 10 times?

**Comment by cherry-geqi** [comment]
Yes, about half-half, don't see clear regularities.

**Comment by zixia** [comment]
So how did you use Wechaty now? It seems you were using phantomjs before/now, but if it had this kind of problem, how can you deal with that?

Or you are using chrome/Docker now?

**Comment by zixia** [comment]
Hello, @cherry-geqi!

Long time no sees. I'd like to invite you to join the Chatie/Contributor Team because you are one of the early committers of Wechaty. :)

Did you receive my team invitation? I can resend an invitation to you if needed. 

Thanks!

**Comment by zixia** [comment]
It seems phantomjs worked again by referring to https://github.com/Chatie/wechaty/issues/633

However it seems has some bugs like WebSocket connection is not stable, need to investigate more time to fix.

**Comment by zixia** [comment]
Close this issue because there are 2 users use it and it seems works like a charm.
