### ISSUE TITLE
Modify Function `Message.say` return type, from `Promise<any>` to `Promise<boolean>`

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#611]
Now,  function `Message.say()` return type as follows:
```ts
public say(text: string, replyTo?: Contact | Contact[]): Promise<any>
```

I suggest it return `Promise<boolean>` to detect whether it send message successfully

The same as `Contact.say()` and `Room.say()`

**Comment by zixia** [comment]
Thanks, great suggestion!

And PR is welcome. :)

**Comment by zixia** [comment]
According to https://github.com/Chatie/wechaty/issues/683#issuecomment-317378166, we should not return `null`.

Instead, we should throw an Exception.

**Comment by zixia** [comment]
Merge to #683
