### ISSUE TITLE
Modify Function `Room.create` return type, from `Promise<Room>` to `Promise<Room|null>` 

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#616]
Now,  function `Room.create()` return type as follows:
```ts
public static create(contactList: Contact[], topic?: string): Promise<Room> {
```

I suggest it return `Promise<boolean>` to detect whether it can create room successfully

Related logs as follows:

#### If it can create room successfully, return as follows:
```
Bot createDingRoom() new ding room created: %s Room {
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  id: '@@356afb5f9c9491eb34158dd1f11b99e136d104c9055106545869cbba1b0fec1c' }
```

#### If it cannot create room successfully, throw the following exception:
```
02:22:13 ERR PuppetWebBridge roomCreate(@ac4db07084d16fe10555569c660e5b8526d162bdc0acca2e93dd72d322f22b4a,@35f68307d4ec6b6e0eabead00e446127) exception: undefined
02:22:13 WARN PuppetWeb roomCreate(@ac4db07084d16fe10555569c660e5b8526d162bdc0acca2e93dd72d322f22b4a,@35f68307d4ec6b6e0eabead00e446127, 网球黑龙江1群) rejected: undefined
02:22:13 ERR Room create() exception: [object Object]
```

**Comment by zixia** [comment]
Could you explain the pros and cons between the two design?

A good purpose should go with good reasons.

**Comment by lijiarui** [comment]
After I thought more, maybe it should return `Promise<Room | null>` will be better.

 If it cannot create a room, we want to get the fail status and don't see more error.

Like `Contact.find()` we will return `Promise<Contact | null>` instead of throw Error if it cannot find a contact.

**Comment by zixia** [comment]
Yes, that's the right answer after you think more.

Please think more before post question/suggestions, at least explain your ideas with pros and cons in detail.

**Comment by lijiarui** [comment]
But now it returns <Room> and throw error, maybe is should return <Room | null> instead of throw error.

**Comment by zixia** [comment]
I agree your purpose.

Please change the title of this issue to better reflect your purpose, and I'll label it as a _enhancement_

**Comment by zixia** [comment]
1. If we can not find a contact by name, it's not an error because the reason will be there's no contact with that name. 
1. However, if we can not create a room, there must be something wrong.

In CASE 1 we should return null, in CASE 2 we should throw an exception.

So my question is: when will `null` be returned by `Room.create()` is necessary, and why?

**Comment by zixia** [comment]
Close this issue due to inactivity for almost two weeks.

**Comment by zixia** [comment]
We should not return `null`.

We are planning to throw an Exception instead.

See also: https://github.com/Chatie/wechaty/issues/683#issuecomment-317378166
