### ISSUE TITLE
Phone Emoji display

### ISSUE THREAD

**Issue by samuelg78** [Chatie/wechaty#632]
In case someone need to display Phone emoji, you can refer the following:

//https://apps.timwhitlock.info/emoji/tables/unicode
const emojiMoneyBag = "💰"
const emojiClapHand = "👏"
const emojiPartyPopping = "🎉"
const emojiBankNote = "💵"
const emojiChineseWu = "🈚"
const emojiChineseYou = "🈶"
const emojiChineseZhong = "🀄"
const emojiTick = "✔"
const emojiTick2 = "✅"
const emojiCross = "✖"
const emojiCross2 = "❌"
const emojiPlus = "➕"
const emojiMinus = "➖"
const emojiNumber0 = "0⃣"
const emojiNumber1 = "1⃣"
const emojiNumber2 = "2⃣"
const emojiNumber3 = "3⃣"
const emojiNumber4 = "4⃣"
const emojiNumber5 = "5⃣"
const emojiNumber6 = "6⃣"
const emojiNumber7 = "7⃣"
const emojiNumber8 = "8⃣"
const emojiNumber9 = "9⃣"

console.log(emojiMoneyBag)

**Comment by suntong** [comment]
This should be in wiki, instead of issue, shouldn't it?

**Comment by zixia** [comment]
I'll close this issue for now, and add that information to the Wiki will be welcome.
