### ISSUE TITLE
watchDogReset() watchdog reset after 60 seconds (phantomjs head)

### ISSUE THREAD

**Issue by kk3hi3123** [Chatie/wechaty#633]
### Expected behavior

Watchdog never dies. Or everything resets after watchdog is reset.

### Actual behavior

```
(node:4813) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: watchDogReset() watchdog reset after 60 seconds, last feed:[HEARTBEAT:[heartbeat@browser]]
```

And the bot has no response after that. (I have tested it more than 60 seconds)
I have found that the function watchDogReset in watchdog.js is not run completely.

```
function watchDogReset(timeout, lastFeed) {
    return __awaiter(this, void 0, void 0, function* () {
        config_1.log.verbose('PuppetWebWatchdog', 'watchDogReset(%d, %s)', timeout, lastFeed);
        const e = new Error(Date.now() + 'watchDogReset() watchdog reset after '
            + Math.floor(timeout / 1000)
            + ' seconds, last feed:'
            + '[' + lastFeed + ']');
        this.emit('error', e);
        // The function stops here. The code below does not run.
        event_1.default.onBrowserDead.call(this, e);
        return;
    });
}
```

### Steps to reproduce the behavior (and fixes, if any)

The bot runs in Ubuntu server using PhantomJS. The bot stops with the error message above within 12 hours. 

### Log

[log.txt](https://github.com/Chatie/wechaty/files/1134238/log.txt)

**Comment by zixia** [comment]
> The bot runs in Ubuntu server using PhantomJS

I have two questions:

1. What's the version of your Wechaty, please follow the issue template if possible.
1. How did you start your bot by using PhantomJS HEAD, please post your command line with all the parameters?

Thanks.

**Comment by kk3hi3123** [comment]
1. My Wechaty version is in 0.8.116.
2. I start it by typing `WECHATY_HEAD=phantomjs node mybot.js`

**Comment by zixia** [comment]
Thanks.

Could you post your full log output with `WECHATY_LOG=silly WECHATY_HEAD=phantomjs` environment variables set?

**Comment by kk3hi3123** [comment]
Ok. But it may spend some time as the issue does not always come out.

**Comment by kk3hi3123** [comment]
Log file is updated

**Comment by zixia** [comment]
Hello @kk3hi3123 , I will close this issue because finally I decided not support phantomjs anymore due to the limited resources.

And we will use chrome-headless in the future, which will work perfectly after 17 Oct this year, after the Chrome version 62 becomes the stable version.
