### ISSUE TITLE
获取不到avatar

### ISSUE THREAD

**Issue by LuKing4DB** [Chatie/wechaty#645]
测试contact-bot.ts，获取头像失败，也许是因为微信接口发生了改变。
测试了python的一个库itchat，https://github.com/littlecodersh/ItChat
也是一样的问题

**Comment by zixia** [comment]
Thanks for reporting.

Are there any others who have the same problem?

**Comment by lingluo** [comment]
我也遇到同样的问题，请问有解决方式不，请求获取到的联系人或者自己的avatar信息后，得到200的响应结果，但是response没有任何数据

**Comment by zixia** [comment]
Could you provide a minimum runnable code snip to reproduce the problem?

I have to close this issue if you can not reproduce it.

**Comment by zixia** [comment]
Close this issue due to inactivity for a month.
