### ISSUE TITLE
Room.find() 发送消息提示 say is not a function

### ISSUE THREAD

**Issue by cmzz** [Chatie/wechaty#664]
![image](https://user-images.githubusercontent.com/6111715/28261155-aa7b81b2-6b10-11e7-82a7-b1431559fe0b.png)

如图，有一个 test 的群。

          const r = Room.find({topic: 'test'})
          r.say('hello')

提示 r.say is not a function

**Comment by zixia** [comment]
`const r = await Room.find({topic: 'test'})`

You need to add **await** before the function which will return a Promise.
