### ISSUE TITLE
Just remove the chromedriver dependency

### ISSUE THREAD

**Issue by jianzhou520** [Chatie/wechaty#674]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)
In China

1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?
none

My personal advice is we should remove the dependency of chromedriver then give all control back to developer

### Full Output Logs

```shell
$ WECHATY_LOG=silly npm run ts-node mybot.ts

# or 

$ WECHATY_LOG=silly node dist/mybot.js
```

<details>
<summary>
Show Logs
</summary>
### Paste the full output logs here with `WECHATY_LOG=silly` set 

```shell
# PASTE FULL LOG OUTPUT AT HERE:



```
</details>

**Comment by zixia** [comment]
Yes, I agree with you.

Actually, I did this once before. Please see: #164 

It seems will cause problems if we did not install it by default. So finally I decided to restore it to suppress that kind of issues.

If you have any good idea about how to remove the dependencies without cause other issues, please feel free to let me know, I would like to do that because there also have other WebDrivers like `phantomjs` and `firefox` etc.

**Comment by jianzhou520** [comment]
I didn't see the source code very clearly, did you use chromedriver to implement the cookie system in node?

**Comment by zixia** [comment]
Yes.

You can know more via my talk at here: 
http://blog.chatie.io/guide/2017/01/06/wechaty-101-presentation.html

Related part is at 7'37''

**Comment by jianzhou520** [comment]
Maybe do this ourselves is a better choice? There are so many issues about chromedriver in windows system

**Comment by zixia** [comment]
I know there are issues, either install or not install.

So please let me know if you have any better solution, which should consider both sides of the issues above.

I'll be very like to hear from you, thanks.

**Comment by jianzhou520** [comment]
I mean we can maintain cookie by handle. There is a same project [wechat4u](https://github.com/nodeWechat/wechat4u), this is the request wrapper contains the cookie operation [request.js](https://github.com/nodeWechat/wechat4u/blob/master/src/util/request.js)

**Comment by zixia** [comment]
Sorry, we can't just use request.js as wechat4u did.

If you had watched my talk, or read the source, you will understand we do heavily depend on the WebDriver to get all the jobs done.

**Comment by zixia** [comment]
closing this because I'm planning to switch to use puppeteer by default in the future.
