### ISSUE TITLE
Group game

### ISSUE THREAD

**Issue by udee297** [Chatie/wechaty#675]
Hi,
Is there any example or tutorial to create group game? Like that werewolves on blog

Regards

**Comment by zixia** [comment]
Did you have a look inside the example directory? 

https://github.com/Chatie/wechaty/wiki/Example

The **room-bot.ts - Manage Chat Room** example should contain the code you needed.

**Comment by zixia** [comment]
Hope you have read the examples and make your code work.

I'll close this issue for now. Please feel free to submit a new issue if you have other problems.
