### ISSUE TITLE
Should throw Exception when there have API Error.

### ISSUE THREAD

**Issue by amyhuangxbd** [Chatie/wechaty#683]
I try to modify contact remark in contact-bot.ts
The main code is: 

``` ts
for (let i = 0; i < contactList.length; i++) {
      const contact = contactList[i]
      if (contact.personal()) {
          log.info('Bot', `personal ${i}: ${contact.get('name')} : ${contact.id}`)
          const remarkUser = '测试' + contact.get('name')
          const ret = await contact.alias(remarkUser)
          if (ret) {
            console.log('ok')
          } else {
            console.error('failed')
          }
          await contact.refresh()
          log.info('Bot', 'get alias: %s', contact.alias())

      }
    }
```

### Expected behavior
Remark should be modified,
And I got the log that tells me the remark is modified, however, in fact, the remark isn't modified.

Below is part of logs: 
``` shell
ok
07:23:31 INFO Bot get alias: INFO Bot get alias: %s 测试转世一瞬
07:23:31 INFO Bot personal 188: 花月正春风 : @4223c4c6f8f25f186f6501dc353e88d0ce5971e7faeef50e77933a44002d8da0 INFO Bot personal 188: 花月正春风 : @4223c4c6f8f25f186f6501dc353e88d0ce5971e7faeef50e77933a44002d8da0
ok
07:23:31 INFO Bot get alias: INFO Bot get alias: %s 测试花月正春风
07:23:31 INFO Bot personal 190: 会飞的灰灰^o^ : @a32609b330af4c163c67859147f833d5 INFO Bot personal 190: 会飞的灰灰^o^ : @a32609b330af4c163c67859147f833d5
ok
07:23:32 INFO Bot get alias: INFO Bot get alias: %s 测试会飞的灰灰^o^
07:23:32 INFO Bot personal 195: Chandelier : @0ae7ef3b90b50aae9338cf65e61b1879fe959035da8e348664ced6201d3cf977 INFO Bot personal 195: Chandelier : @0ae7ef3b90b50aae9338cf65e61b1879fe959035da8e348664ced6201d3cf977
ok
07:23:32 INFO Bot get alias: INFO Bot get alias: %s 测试Chandelier
07:23:32 INFO Bot personal 201: Jarrah - 100offer : @348213df31a64f2f2c9ab614851d2c759605f8868a1927f727799514e7c6a58a INFO Bot personal 201: Jarrah - 100offer : @348213df31a64f2f2c9ab614851d2c759605f8868a1927f727799514e7c6a58a

```

**Comment by lijiarui** [comment]
You should wait for a while.
Becasue it change alias on web wechat, and it needs some time to synchronize to mobile wechat.

**Comment by lijiarui** [comment]
Btw, please change ` to ``` for your log info as I modified for your first comment.

**Comment by zixia** [comment]
It's related to #596 #412 

After those issues, I start to think that we should throw an `Exception` if the operation failed, instead of return a `false` silently.

The related method should include(but not limited):
1. `alias`
1. `say`
1. `accept`
1. `add`
1. `del`
1. etc...

**Comment by amyhuangxbd** [comment]
@lijiarui Thanks for your reply and support!
In fact, I have tried many times to change the remark. And only a few times was successful,
In most cases, it is failing. contact.alias(String) seems unstable.

**Comment by iyjian** [comment]
@amyhuangxbd  YES it is unstable, do u have any workaround?

**Comment by amyhuangxbd** [comment]
I can remark friend's alias in web version successfully, but the alias unable to synchronize to the phone.
I haven't found the reason why the web and the phone can't sync.

**Comment by zixia** [comment]
@amyhuangxbd You did not "remark friend's alias in web version successfully", it's only changed inside your browser, the server never accepted that.

If you refresh the browser or re-login, you will find out that the new "alias/remark" is lost.

**Comment by zixia** [comment]
I had changed some of the API to throw Exception when failed, and will changes others in the future.

Please let me know if you found any API need to refactor in the latest version of the master branch, PR will be awesome and welcome!

See: https://github.com/Chatie/wechaty/issues/1167
