### ISSUE TITLE
How to link it with personal account. 

### ISSUE THREAD

**Issue by AliAyub007** [Chatie/wechaty#693]
I am having a little problem here that how can I link my account and dow do we configure our account with this. How will my account work as a chatbot on weChat or in short where will I send messages to test it?  can anyone explain please.  It will be very thankful. 

Sorry for not following guidelines of issue but couldn't do so.

**Comment by zixia** [comment]
Did you see the Getting Start Tutorial?
https://github.com/Chatie/wechaty/wiki/GettingStarted

It's in Chinese but you could follow it without any problem because it's a live coding tutorial.

Also I'll suggest you have a look on Examples first at here: https://github.com/Chatie/wechaty/wiki/Example

**Comment by AliAyub007** [comment]
when I tried getting started with npm module I got these error in console. 

22:54:47 ERR PuppetWebEvent onServerDisconnect() setTimeout() bridge.init() exception: [Error: execute proxyWechaty(init) error: 503, init() without a ready angular env]

(node:53719) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: watchDogReset() watchdog reset after 60 seconds, last feed:[HEARTBEAT:[heartbeat@browser]]

here is my code:

const { Wechaty } = require('wechaty') // import { Wechaty } from 'wechaty'

const bot = Wechaty.instance() // Singleton
bot.init();

bot.on('scan', (url, code) => console.log(`Scan QR Code to login: ${code}\n${url}`))
bot.on('login',       user => console.log(`User ${user} logined`))
bot.on('message',  message => console.log(`Message: ${message}`))

**Comment by zixia** [comment]
Hello, thank you for using Wechaty. 

Issues are about to fire bugs & request features only, so it's not a Support Forum.

To get help, ask questions and discuss with other developers, please join our _Wechaty Developers' Home_ community in Wechat.

### Join Wechaty Developers' Community

Wechaty is used in many ChatBot projects by hundreds of developers. If you want to talk with other developers, just scan the following QR Code in WeChat with secret code _wechaty_, you can join our **Wechaty Developers' Home** at once.

![Wechaty Developers' Home](https://raw.githubusercontent.com/chatie/wechaty/master/image/BotQrcode.png)

Scan now, because other Wechaty developers want to talk with you too! (secret code: _wechaty_)

**Comment by Realzzz1874** [comment]
@huan hi, bro! I got the same problem when I first use wechaty, is there any ideas?

error message: 
```javascript
ERR PuppetWeChatBridge onLoad() exception: Error: execute proxyWechaty(init) error: 503, init() without a ready angular env
node:internal/process/promises:246
```

my code:

```javascript
// index.js
const qrTerm = require('qrcode-terminal');
const Wechaty = require('wechaty');

const { ScanStatus, WechatyBuilder, log } = Wechaty;

function onScan (qrcode, status) {
  if (status === ScanStatus.Waiting || status === ScanStatus.Timeout) {
    qrTerm.generate(qrcode, { small: true });  // show qrcode on console

    const qrcodeImageUrl = [
      'https://wechaty.js.org/qrcode/',
      encodeURIComponent(qrcode),
    ].join('');

    log.info('StarterBot', 'onScan: %s(%s) - %s', ScanStatus[status], status, qrcodeImageUrl);
  } else {
    log.info('StarterBot', 'onScan: %s(%s)', ScanStatus[status], status);
  }
}

// get a Wechaty instance
const bot = WechatyBuilder.build({
  name: 'wechat-bot',
  puppet: 'wechaty-puppet-wechat',
})

// emit when the bot needs to show you a QR Code for scanning
bot.on('scan', onScan);

// start the bot
bot.start()
  .then(() => log.info('StarterBot', 'Starter Bot Started.'))
  .catch(e => log.error('StarterBot', e))
```

**Comment by Yongest** [comment]
请问现在可以了没

**Comment by Yongest** [comment]
> @huan hi, bro! I got the same problem when I first use wechaty, is there any ideas?
> 
> error message:
> 
> ```js
> ERR PuppetWeChatBridge onLoad() exception: Error: execute proxyWechaty(init) error: 503, init() without a ready angular env
> node:internal/process/promises:246
> ```
> 
> my code:
> 
> ```js
> // index.js
> const qrTerm = require('qrcode-terminal');
> const Wechaty = require('wechaty');
> 
> const { ScanStatus, WechatyBuilder, log } = Wechaty;
> 
> function onScan (qrcode, status) {
>   if (status === ScanStatus.Waiting || status === ScanStatus.Timeout) {
>     qrTerm.generate(qrcode, { small: true });  // show qrcode on console
> 
>     const qrcodeImageUrl = [
>       'https://wechaty.js.org/qrcode/',
>       encodeURIComponent(qrcode),
>     ].join('');
> 
>     log.info('StarterBot', 'onScan: %s(%s) - %s', ScanStatus[status], status, qrcodeImageUrl);
>   } else {
>     log.info('StarterBot', 'onScan: %s(%s)', ScanStatus[status], status);
>   }
> }
> 
> // get a Wechaty instance
> const bot = WechatyBuilder.build({
>   name: 'wechat-bot',
>   puppet: 'wechaty-puppet-wechat',
> })
> 
> // emit when the bot needs to show you a QR Code for scanning
> bot.on('scan', onScan);
> 
> // start the bot
> bot.start()
>   .then(() => log.info('StarterBot', 'Starter Bot Started.'))
>   .catch(e => log.error('StarterBot', e))
> ```

请问可以了没

**Comment by Realzzz1874** [comment]
可以了，已经解决了

**Comment by shootyou** [comment]
> 可以了，已经解决了

请教下如何解决的？
