### ISSUE TITLE
Room.memberAll(FilterString) if FilterString are all with emojis

### ISSUE THREAD

**Issue by superchaoran** [Chatie/wechaty#704]
Description:
When FilterString contains all emojis, api code in memberAll will try to remove all emojis, result in a filterValue of null.
https://github.com/Chatie/wechaty/blob/f906d7a5fa6269e21c25ada7ececee78caf28641/src/room.ts#L518

**Comment by zixia** [comment]
Thanks for reporting. 

it seems should be solved. Did it throw exception?

**Comment by zixia** [comment]
Should we keep the emoji XML instead of trying to parse or filter it out?

**Comment by zixia** [comment]
Close this issue due to no response for a year.
