### ISSUE TITLE
MediaMessage.filename() cannot get correct img name.

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#722]
### Expected behavior

Get picture filename

### Actual behavior

Cannot get picture filename, but can get pdf filename.

### Steps to reproduce the behavior (and fixes, if any)

code as follows:
```ts
.on('message', async function (m) {
    if (m.rawObj) {
      console.log('======get filename()=======')
      const mediaMsg = new MediaMessage(m.rawObj)
      console.log(mediaMsg.filename())
    }
})
```

#### When I send a pdf file, it works as follows:
```
======get filename()=======
how to build a chatbot.pdf
```

#### When I send a picture, called `WechatIMG1.jpg`, I expect it return `WechatIMG1.jpg`, but it gets the following result:
```
======get filename()=======
813716082458353226.jpg
```

**Comment by binsee** [comment]
Video / voice / image / emoticon type msg, ( gif/jpg/png/jpeg/mp3/mp4 ).
The file name will be renamed by the server, so the file name is not required when uploading.

**Comment by binsee** [comment]
Other type file, (MsgType = APP =49 , AppMsgType = ATTACH =6), need file name, file name is the same when Upload and download

**Comment by lijiarui** [comment]
ok, I see, thanks!
