### ISSUE TITLE
Add Transpond Message

### ISSUE THREAD

**Issue by binsee** [Chatie/wechaty#726]
PR: #727

Read the page code, see the official forwarding message implementation code.
And this code is very simple, you can easily in a formal way to achieve forwarding messages, such as the direct forwarding of the received file.

```javascript
angular.module("Controllers").controller("transpondDialogController", ["$rootScope", "$scope", "$timeout", "$state", "$log", "$document", "chatFactory", "contactFactory", "appFactory", "chatroomFactory", "confFactory", "mmpop", "ngDialog", "utilFactory", "stateManageService", "accountFactory",
  function(e, t, a, n, i, o, chatFactory, c, s, l, confFactory, f, u, m, g, accountFactory) {
    function h(msg, userName) {
      if (e.MsgType != confFactory.MSGTYPE_SYS) {
        var newMsg = angular.copy(msg);
        newMsg.ToUserName = userName;
        newMsg.FromUserName = accountFactory.getUserName();
        newMsg.isTranspond = !0;
        newMsg.MsgIdBeforeTranspond = msg.MsgIdBeforeTranspond || msg.MsgId;
        newMsg._h = void 0;
        newMsg._offsetTop = void 0;
        newMsg.MMSourceMsgId = msg.MsgId;
        newMsg.Scene = 2;
        newMsg = chatFactory.createMessage(newMsg);
        newMsg.sendByLocal = !1;
        newMsg.Content = m.htmlDecode(newMsg.Content.replace(/^@\w+:<br\/>/, ""));
        newMsg.MMActualSender = accountFactory.getUserName();
        newMsg.MMSendContent && (newMsg.MMSendContent = newMsg.MMSendContent.replace(/^@\w+:\s/, ""));
        newMsg.MMDigest && (newMsg.MMDigest = newMsg.MMDigest.replace(/^@\w+:/, ""));
        newMsg.MMActualContent && (newMsg.MMActualContent = m.clearHtmlStr(newMsg.MMActualContent.replace(/^@\w+:<br\/>/, "")));

        chatFactory.appendMessage(newMsg);
        chatFactory.sendMessage(newMsg)
      }
    }

// ...........
```

Use:

```javascript
id='' // roomId or userId
// Room.toString()
// Contact.id
// Message.from()
bot.on('message',async m => {
     m.transpond(id)
}) 
```

**Comment by binsee** [comment]
Upload the branch later

**Comment by binsee** [comment]
This support involves [Reconstruction MediaMessage #724](https://github.com/Chatie/wechaty/issues/724), because need to consider where to build the original data structure.

The current build data is to call the `chatFactory.createMessage()` method via `webchaty-bro`.
Either the text of the message, or the Rich Media `MediaMessage`. However, there is a problem with the call in `MediaMessage`.

Forwarding features that need to skip the call, but contrary to the current data isolation scheme.

**Comment by zixia** [comment]
Great achievement!

Please see #200, I suggest to use `forward()` as the method name because it's very straight forward.

**Comment by binsee** [comment]
@zixia The code used `forward`, See #727

**Comment by binsee** [comment]
discuss:
WeChat server for more than 25Mb of the document, asked to re-upload, can not be directly forwarded.
Should I detect file size in forward (), throw exception if it exceeds 25Mb?

**Comment by zixia** [comment]
Thanks.

About the size limit: my suggestion is to re-upload automatically with a verbose log message.

**Comment by binsee** [comment]
I think that the document beyond the limits should be implemented on its own.

But because there is no test upload 25Mb get MediaId whether multiple multiplexing in the message, it can not be conclusive.

I will supplement the information after the test.

**Comment by binsee** [comment]
Known issues:
Forward the message within the group, forward the message will be "@ id:" prefix

**Comment by binsee** [comment]
Add the Forward Message Source Settings option, see https://github.com/Chatie/wechaty/pull/727/commits/09511eb7bc6fcb87d36ecbe49ef0cb51203e02dc


```javascript
m.forward(Room.load(id), { user: '$USER', room: 'Room[$ROOM]', custom: 'forward from $ROOM$USER' })

// source message: 'test msg'
// from room: 'testRoom'
// from user: 'Bot'
// forward message: `forward from Room[testRoom]Bot:\ntest msg`
```

**Comment by zixia** [comment]
I do not understand about the design of `m.forward(Room.load(id), { room: '群[$ROOM]', custom: '转发消息来自 $ROOM$USER' })`, it looks very complicated and hard to understand at the first sight.

Does this design for forwarding a TEXT message?

I do not think forward a text message is necessary, because we can be easy to just `say()` it without any problem.

The power of `forward` is dealing with the attachments, which should belong to the `MediaMessage`. 

Please correct me if I missed any point.

**Comment by binsee** [comment]
This design is not intuitive.
If you want to remove this design, I would like forward can only be used to forward Media message.

**Comment by zixia** [comment]
Yes, my suggestion is to:

1. move `forward` to `MediaMessage` only, because that would be really helpful for dealing with the attachment files.
1. if we want to forward a `Message`, which means it is a text message, we can easily archive the same result by constructing a new string to the message, like the following code snip:     
```ts
const forwardMsg = `转发消息来自${room}${user}\n$content`
await forwardRoom.say(forwardMsg)
```    
Which is more straight forward, and also keep the API to be simple and be easy understand.    

3. we can identify the `Message` and `MediaMessage` by using `instanceof` in `message` event listener. 
Full code will like this:
```ts
on('message', async m => {
  const from = m.from()
  const room = m.room()
  const content = m.content()
  const fwdMsg = `转发消息来自${room}${user}\n$content`
  const fwdRoom = await Room.find('测试群')
  await fwdRoom.say(fwdMessage)
  if (m instanceof MediaMessage) {
    await m.forward(fwdRoom)
  }
})

**Comment by binsee** [comment]
moved forward() from class Message to MediaMessage.
https://github.com/Chatie/wechaty/pull/727/commits/ea3e63829672993c26b81c21db34ba7e23fb2ec4

**Comment by zixia** [comment]
Awesome!

**Comment by binsee** [comment]
forward video msg of room, self() error.

fiex. see https://github.com/Chatie/wechaty/pull/727/commits/5f8503dbbba43f2fb4474ad58af8fe29a1e3560c
