### ISSUE TITLE
[doc] To Embed Document in Wechaty Code for Generating Automaticly

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#73]
The Public API of Wechaty is almost not changed much during the past five months, but the module is increasing, and the internal API is changed a lot.

We need to document them better, not only the public but also the internal modules and methods. 

So a document generator with embed document in code needs to be considering from now.

I'd like to prefer [Dgeni](https://github.com/angular/dgeni), which is the Documentation Generator of AngularJS/Angular Material/Protractor/Ionic.

~~Here're some useful links:~~
* ~~<https://github.com/angular/angular.js/wiki/Writing-AngularJS-Documentation>~~
* ~~<http://allenhwkim.tumblr.com/post/92161523693/sigh-angularjs-documentation>~~
---
### Update on Feb 2017:

Finally we decided to use the classic [jsdoc](http://usejsdoc.org/) to embed document in TypeScript, then generate document to [docs/](https://github.com/wechaty/wechaty/tree/master/docs) by [jsdoc2md](https://github.com/jsdoc2md/jsdoc-to-markdown).

* [An introduction to JSDoc](http://www.2ality.com/2011/08/jsdoc-intro.html)
* [Creates markdown API documentation from jsdoc-commented javascript](https://github.com/jsdoc2md/jsdoc-to-markdown)
* [Typescript: JSDoc support in JavaScript](https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript)

**Comment by sleedata** [comment]
@zixia, I'll look into this.

**Comment by kis87988** [comment]
I will try to contribute about this issue

**Comment by zixia** [comment]
@kis87988 Hope you could help the community to get a better version of Documentations!

**Comment by zixia** [comment]
Close this issue because the PR will be merged soon.
