### ISSUE TITLE
Code formatting conventions

### ISSUE THREAD

**Issue by binsee** [Chatie/wechaty#745]
I use vscode as the IDE, using some plugin for formatting the code style. But the code to edit the project had to disable the style plug-in, because the format after the automatic format and the original code style is very different.
The current style of some chaos, some alignment did not find the available plug-ins to maintain the style of unity.

current style:
```javascript
const obj: MsgObj = {
  id:           rawObj.MsgId,
  type:         rawObj.MsgType,
  from:         rawObj.MMActualSender, // MMPeerUserName
  to:           rawObj.ToUserName,
  content:      rawObj.MMActualContent, // Content has @id prefix added by wx
  status:       rawObj.Status,
  digest:       rawObj.MMDigest,
  date:         rawObj.MMDisplayTime,  // Javascript timestamp of milliseconds
  url:          rawObj.Url || rawObj.MMAppMsgDownloadUrl || rawObj.MMLocationUrl,
}

//////////////////////
log.verbose('Room', 'say(%s, %s)',
                    content,
                    Array.isArray(replyTo)
                    ? replyTo.map(c => c.name()).join(', ')
                    : replyTo ? replyTo.name() : '',
)

//////////////
    return Promise.resolve([
      new Message   (<MsgRawObj>{MsgId: '-2'}),
      new Message (<MsgRawObj>{MsgId: '-3'}),
    ])
```

I formatted the style:
```javascript
const obj: MsgObj = {
  id: rawObj.MsgId,
  type: rawObj.MsgType,
  from: rawObj.MMActualSender, // MMPeerUserName
  to: rawObj.ToUserName,
  content: rawObj.MMActualContent, // Content has @id prefix added by wx
  status: rawObj.Status,
  digest: rawObj.MMDigest,
  date: rawObj.MMDisplayTime,  // Javascript timestamp of milliseconds
  url: rawObj.Url || rawObj.MMAppMsgDownloadUrl || rawObj.MMLocationUrl,
}

//////////////
log.verbose('Room', 'say(%s, %s)',
  content,
  Array.isArray(replyTo)
    ? replyTo.map(c => c.name()).join(', ')
    : replyTo ? replyTo.name() : '',
)

////////////
    return Promise.resolve([
      new Message(<MsgRawObj>{ MsgId: '-2' }),
      new Message(<MsgRawObj>{ MsgId: '-3' }),
    ])
```

Should add cross-IDE style conventions? Such as using eslint. [eslint@vscode](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
Or please tell me the current style plugin used to keep the style united.

**Comment by binsee** [comment]
I noticed that the project's eslint style configuration is saved in package.json, but even with this configuration, I use eslint to format the code and still produce a lot of style changes.
So now I can not use the full file format, can only choose their own editing code area, and format them. This is very cumbersome, especially when editing the code very much.

**Comment by zixia** [comment]
Yes , please do not do any full file format by plugin, because the current style is not generated by any plugin, but by myself. 

I'm always using vscode , its the best ide I think.

And I never use auto formating plugin because I like the current style.

Btw: do not use eslint , use tslint instead because we are typescript code.

**Comment by binsee** [comment]
Okay. But I think the multiplayer project does not use automatic code style formatting, inevitably there will be inconsistent code style.

**Comment by zixia** [comment]
I agree. And I would love to have an automatic code style formatting tool for our project if we could find a suitable tool.

Please let me know if you have any good suggestions, thanks!

**Comment by binsee** [comment]
I think about the code formatting, the main problem we face is the alignment of the parameter style.
I found a plugin on vscode that can handle parameter alignment, but it needs to be manipulated manually, it is appropriate to handle the alignment on the style of the development process, but it is a trouble not to use it directly for formatting.
In addition, it does not support some features. Such as typescript's `import` statement and some code will be formatted incorrectly.


VSCode plugin: [Better Align](https://marketplace.visualstudio.com/items?itemName=wwm.better-align)

------------

![image](https://user-images.githubusercontent.com/5285894/29894211-1e8ffe70-8e07-11e7-9fd7-353250455813.png)

**Comment by zixia** [comment]
VSCode plugin Better Align is awesome, I'll try to play with it.

About the tslint, could we possibly put the rules into our tslint.json?

**Comment by zixia** [comment]
```json
 "alignment": {
        "operatorPadding": "right"
      , "indentBase":      "firstline"
      , "surroundSpace":   {
        "colon":      [-1, 1],   // The first number specify how much space to add to the left, can be negative. The second number is how much space to the right, can be negative.
        "assignment": [1, 1],    // The same as above.
        "arrow":      [1, 1],    // The same as above.
        "comment":    2          // Special how much space to add between the trailing comment and the code.
                               // If this value is negative, it means don't align the trailing comment.
    }
```

I believe this is the style that I did in Wechaty.

**Comment by wj-Mcat** [comment]
> ```json
>  "alignment": {
>         "operatorPadding": "right"
>       , "indentBase":      "firstline"
>       , "surroundSpace":   {
>         "colon":      [-1, 1],   // The first number specify how much space to add to the left, can be negative. The second number is how much space to the right, can be negative.
>         "assignment": [1, 1],    // The same as above.
>         "arrow":      [1, 1],    // The same as above.
>         "comment":    2          // Special how much space to add between the trailing comment and the code.
>                                // If this value is negative, it means don't align the trailing comment.
>     }
> ```
> 
> I believe this is the style that I did in Wechaty.

According to the `.vscode/setting.json` file in wechaty, wechaty-* projects, the "colon" parameter should be : `[1, 1]`. the whole alignment config shoule be:

```typescript
  "alignment": {
    "operatorPadding": "right",
    "indentBase":      "firstline",
    "surroundSpace":   {
      "colon":      [1, 1],   // The first number specify how much space to add to the left, can be negative. The second number is how much space to the right, can be negative.
      "assignment": [1, 1],    // The same as above.
      "arrow":      [1, 1],    // The same as above.
      "comment":    2,         // Special how much space to add between the trailing comment and the code.
                               // If this value is negative, it means don't align the trailing comment.
    }
  },
```

If it is, we can make it a rule for wechaty tslint settings configuration. @huan How do you think abuot ?

**Comment by huan** [comment]
Agree to use it as a rule for wechaty.

BTW: we are using eslint now because tslint was deprecated.
