### ISSUE TITLE
how to get all rooms with Room.findAll

### ISSUE THREAD

**Issue by yzy5768** [Chatie/wechaty#748]
now, Room.findAll return about 30 items, is there a way to get all rooms ? thx!

**Comment by zixia** [comment]
have you tried #668?

**Comment by yzy5768** [comment]
yes,  I'v tried, here's my code
`
var dumpRoomCount = 0;
function dumpRooms() {
	return __awaiter(this, void 0, void 0, function* () {
	    const roomList = yield Room.findAll();
	    for (let i = 0; i < roomList.length; i++) {
	        const room = roomList[i];
	        console.log('Bot', `room ${i}: ${room.topic()}`);
	    }
	    if(++dumpRoomCount < 4)
	    	setTimeout(dumpRooms, 3 * 1000);
	})
}`
I tried two wechat accounts,  the code retrieve only 30 recent rooms for each one.

**Comment by zixia** [comment]
I'm trying to fix this issue, please test the master branch code with version v0.8.157 or above, which should resolve this problem.

**Comment by yzy5768** [comment]
ok, thx.

**Comment by zixia** [comment]
Did the latest version solve your problem?

**Comment by yzy5768** [comment]
The latest 0.8.170 version still has that probolem, but if i use normal chrome as my puppet and clear all cached data like cookie etc, then will get much more groups but not all of them. I tried login in web wechat on chrome after clear cookies, the web wechat it's self only get the same groups as wechaty. I guess  some groups and recent contacts may be locally cahced,  and the wechat api olny got the recent groups and contacts.

**Comment by zixia** [comment]
Did you tried to use a settimeout for your contact.findall?

Like after 10s, or even 60s, depends on your network.

**Comment by yzy5768** [comment]
ye, I tried,  is there some method to clear cookies while use wechaty?

**Comment by zixia** [comment]
So what did you exactly tried, and what's the result?

**Comment by yzy5768** [comment]
I tried both chrome browser and wechaty, they all got part of groups, if I clear cookies ,they got more but still all of the groups.

**Comment by zixia** [comment]
If you only get part of groups in your Browser Web Wechat App, then you have to wait until the data is fully loaded from the Tencent Server. 

Then this issue seems not related with Wechaty because what Wechaty did is just to load data from the browser.

Please close this issue if this answer resolves your question.
