### ISSUE TITLE
add static method `Message.findAll()`

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#765]
as shown in the code ：

https://github.com/lijiarui/wechaty/blob/master/docs/index.md#messagefindall

**Comment by zixia** [comment]
I have to questions for you:

1. what do you think this function do?
1. why it's useful?

I ask because I'm still thinking about them.

**Comment by zixia** [comment]
Close this issue for no future input for a week.

Will reopen it when we have clear ideas on this topic.
