### ISSUE TITLE
ERR Wechaty init() already inited. return and do nothing

### ISSUE THREAD

**Issue by moxiaobei2** [Chatie/wechaty#778]
### I create node server with websocket,when I connected,I will  Wechaty.instance() then scan function to set image url to client to show view. but when i logined,it can do actions to all client.just like when I finished scan ,one client index.html hide image,just nodw another clien index.html also hide  image. terminal show ERR Wechaty init() already inited.return and do doing.
##how can i do not disturb each other.just single line

**Comment by zixia** [comment]
This error message means that you called `Wechaty.instance().init()` more than once.

Please check your code.

**Comment by zixia** [comment]
Close this issue due to inactivity for long time.
