### ISSUE TITLE
请问能否添加下载附件的功能？

### ISSUE THREAD

**Issue by djjeng77** [Chatie/wechaty#791]
#看了您的文档上并没有下载对方发送的图片，语音，视频的功能。
虽然能拿到url地址，但是因为cookie不同，无法使用node下载。
请问能否添加下载图片语音等功能呢？
示例代码speech-to-text-bot.ts里面有下载，但是下载下来之后是一个0kb大小的mp3文件。

**Comment by lijiarui** [comment]
see [media-file-bot.ts](https://github.com/Chatie/wechaty/blob/master/example/media-file-bot.ts)

You can download image, voice, and video.

**Comment by nichoasurey** [comment]
You can use docker.

**Comment by zixia** [comment]
We had already support to download any attachments. Please read the document carefully, and try the media-file-bot in the example directory.

**Comment by lizhongyi** [comment]
获取到的文件图片是 122333..jpg 然后size是0 安卓手机，mac 终端测试 不能下载图片
