### ISSUE TITLE
Incorrect number of contacts in Contact.findAll 

### ISSUE THREAD

**Issue by hk768** [Chatie/wechaty#797]
My wechat account has more than two thousand contacts, I got incorrect number of contacts when using `Contact.findAll`. Below is the related code snippet:
```js
.on('login', user => { 
    Contact.findAll().then((list) => {
        console.log(`count: ${list.length}`);
    })
})
```
the console outputted `76` while actually it should be two thousand more.

**Comment by zixia** [comment]
It's not an issue of Wechaty because the WebWechat only loads some of your contacts after you log in.

To confirm this, you can open a web browser to login web wechat, and check the total number of your contacts.

**Comment by hk768** [comment]
@zixia I moved the code containing `Contact.findAll` to `.init().then` callback and it seems to work now.

**Comment by zixia** [comment]
Great to hear that.

But please be careful that I believe it will not be guaranteed to always get your expected result by using `init().then`.

**Comment by hk768** [comment]
@zixia No, It doesn't.
