### ISSUE TITLE
请问怎么才能获取微信web协议中对聊天对象的唯一标识，并且通过这个唯一标识去保存与聊天对象的聊天记录，以方便日后查看

### ISSUE THREAD

**Issue by PikachuWu** [Chatie/wechaty#801]
请问怎么才能获取微信web协议中对聊天对象的唯一标识，并且通过这个唯一标识去保存与聊天对象的聊天记录，以方便日后查看

**Comment by lijiarui** [comment]
>> You can get the unique ID for a contact/room by contact.id and room.id. However, this id will not keep consistent across Web Sessions. You can use contact.alias('uniqueId') to set an alias for the contact, and find contact by alias using Contact.find({alias: 'uniqueId'}).

From [FAQ](https://github.com/Chatie/wechaty/wiki/FAQ#1-how-to-get-the-permanent-id-for-a-contact)

**Comment by PikachuWu** [comment]
微信属于多端的，所以设置备注有很多风险会导致保存的聊天数据丢失，个人觉得不是特别好，有没有其他比较优雅的方式呢？

**Comment by lijiarui** [comment]
Wechat alias can across multiple ends.

Try change alias on PC client wechat, and you will find you mobile client change alias automatically.

**Comment by PikachuWu** [comment]
是的，即是说，这个别名的唯一标识有多种方式可以被更改，所以数据丢失风险太大，意义不大

**Comment by zixia** [comment]
Currently, this is the only way we can identify the wechat user from the web protocol: use a contact alias.
