### ISSUE TITLE
新注册微信号无法登录网页版

### ISSUE THREAD

**Issue by chunyong1991** [Chatie/wechaty#804]
![4b343acd-cb64-4fe9-a3d9-4b4f714a2195](https://user-images.githubusercontent.com/12395543/30469830-e6828280-9a24-11e7-9b9a-d45dcda0949f.jpeg)

机器人没法用了吗?

**Comment by lijiarui** [comment]
just FYI

![image](https://user-images.githubusercontent.com/6419514/30471702-4cdbfdf2-9a2c-11e7-86f9-23d768792e55.png)

![image](https://user-images.githubusercontent.com/6419514/30471705-51503682-9a2c-11e7-8e0f-98b2a1741b69.png)

**Comment by chunyong1991** [comment]
@lijiarui  Is this official response from WeChat?

**Comment by lijiarui** [comment]
This picture from [WeixinBot](github.com/Urinx/WeixinBot) community.

**Comment by zixia** [comment]
I'll close this issue because it is not an issue related with Wechaty, but a policy from Tencent.

**Comment by zixia** [comment]
See: #990
