### ISSUE TITLE
can wechaty send share card msg ?

### ISSUE THREAD

**Issue by loohoo** [Chatie/wechaty#824]
例子中没有找到 发送各种类型消息的代码？ 不知道如何自定义发送消息。光纯文本没法满足需求。

**Comment by binsee** [comment]
wechaty目前只有基于web wx协议实现，受到微信官方的限制，只能发文字、图片、文件这三种形式的信息。
其中文件可以发送100Mb以内的文件，图片和音乐类型文件会被转化形式。

**Comment by zixia** [comment]
Thanks @binsee for explaining this.
