### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#846]
I got this exception when I receive/send image files just now.

```shell
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._callback (/home/zixia/chatie/wechaty/src/puppet-web/puppet-web.ts:565:28)
    at Request.self.callback (/home/zixia/chatie/wechaty/node_modules/request/request.js:186:22)
```

https://github.com/Chatie/wechaty/blob/f0c81fc074303406096f4f93bd5eead3839e9cbc/src/puppet-web/puppet-web.ts#L560-L570

I believe it is a random error because I had sent/received many image files before saw this error message.

CC @binsee

**Comment by binsee** [comment]
Can you look at the body content?

**Comment by zixia** [comment]
Will post the body content to here if I could reproduce it again.

**Comment by zixia** [comment]
Close this issue for house keeping...
