### ISSUE TITLE
Static user identifier

### ISSUE THREAD

**Issue by seifhatem** [Chatie/wechaty#861]
Hello,
Is there a way to get an identifer for the user who sent the message that is always the same?

uin & wxuin are undeifned ir null
username & MMFullUserName are the user id which is changed after restarting the server

Thanks

**Comment by lijiarui** [comment]
You can get the unique ID for a contact/room by contact.id and room.id. However, this id will not keep consistent across Web Sessions. You can use `contact.alias('uniqueId')` to set an alias for the contact, and find contact by alias using `Contact.find({alias: 'uniqueId'})`.

see more [FAQ](https://github.com/Chatie/wechaty/wiki/FAQ#1-how-to-get-the-permanent-id-for-a-contact)

**Comment by seifhatem** [comment]
Thanks for your help
