### ISSUE TITLE
[Docker] Unable to login 

### ISSUE THREAD

**Issue by kimmanlui** [Chatie/wechaty#871]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China) HONG KONG
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using? DOCKER 

run -ti --rm --volume="$(pwd)":/bot zixia/wechaty mybot.ts
It is expected to login after scanning QR code. But, nothing happened. On the android, wechat showed I already logged into webwechat but nothing showed on the console. 
Thanks,

**Comment by zixia** [comment]
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

**Comment by kimmanlui** [comment]
Sorry here is the message. I just follow your example.

Your Example: docker run -ti --rm --volume="$(pwd)":/bot zixia/wechaty mybot.ts  

admins-MacBook-Pro:wechaty admin$ docker run -ti --rm --volume="$(pwd)":/bot zixia/wechaty mybot.ts 

 __        __        _           _          
 \ \      / /__  ___| |__   __ _| |_ _   _  
  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | | 
   \ V  V /  __/ (__| | | | (_| | |_| |_| | 
    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, | 
                                     |___/  
____________________________________________________
            https://www.chatie.io
  ____                            _   _             
 / ___|___  _ __  _ __   ___  ___| |_(_)_ __   __ _ 
| |   / _ \| '_ \| '_ \ / _ \/ __| __| | '_ \ / _` |
| |__| (_) | | | | | | |  __/ (__| |_| | | | | (_| |
 \____\___/|_| |_|_| |_|\___|\___|\__|_|_| |_|\__, |
                                              |___/ 
  ____ _           _   ____        _       
 / ___| |__   __ _| |_| __ )  ___ | |_ ___ 
| |   | '_ \ / _` | __|  _ \ / _ \| __/ __|
| |___| | | | (_| | |_| |_) | (_) | |_\__ \
 \____|_| |_|\__,_|\__|____/ \___/ \__|___/
                                           

Starting Wechaty v0.10.9 with Node.js v7.10.1 ...
Working directory: /bot
Executing ts-node mybot.ts
05:31:30 INFO Wechaty v0.10.13 initializing...
05:31:30 ERR PuppetWebBridge init() exception: AssertionError: Chromium revision is not downloaded. Run "npm install"
05:31:30 ERR PuppetWeb initBridge() exception: Chromium revision is not downloaded. Run "npm install"
05:31:30 ERR PuppetWeb init() exception: AssertionError: Chromium revision is not downloaded. Run "npm install"
05:31:30 ERR Wechaty init() exception: Chromium revision is not downloaded. Run "npm install"
(node:32) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): AssertionError: Chromium revision is not downloaded. Run "npm install"
(node:32) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

 __        __        _           _          
 \ \      / /__  ___| |__   __ _| |_ _   _  
  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | | 
   \ V  V /  __/ (__| | | | (_| | |_| |_| | 
    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, | 
                                     |___/  
____________________________________________________
            https://www.chatie.io
  _____      _ _      ___   
 | ____|_  _(_) |_   / _ \  
 |  _| \ \/ / | __| | | | | 
 | |___ >  <| | |_  | |_| | 
 |_____/_/\_\_|\__|  \___/

**Comment by zixia** [comment]
You need to run `npm install` first. (Before docker run)

**Comment by liutian1937** [comment]
the same problem

**Comment by zixia** [comment]
@liutian1937 What version did you use? Please try v0.12, it should work without any problem.

See: https://github.com/Chatie/wechaty/issues/937#issuecomment-340411445

**Comment by zixia** [comment]
I'll close this issue due to inactivity.

Please make sure you are using the latest stable version of Wechaty when you ran into issue.

Currently v0.12 should work without any problem.

**Comment by zhuaoyuan** [comment]
the same problem with redhat4.8.5&docker1.12.6&wechaty0.13.12
$sudo docker run -ti --rm --volume="$(pwd)":/bot zixia/wechaty mybot.js
 
__        __        _           _         
\ \      / /__  ___| |__   __ _| |_ _   _ 
  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | |
   \ V  V /  __/ (__| | | | (_| | |_| |_| |
    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, |
                                     |___/ 
____________________________________________________
https://www.chatie.io
  ____                            _   _            
/ ___|___  _ __  _ __   ___  ___| |_(_)_ __   __ _
| |   / _ \| '_ \| '_ \ / _ \/ __| __| | '_ \ / _` |
| |__| (_) | | | | | | |  __/ (__| |_| | | | | (_| |
\____\___/|_| |_|_| |_|\___|\___|\__|_|_| |_|\__, |
                                              |___/
  ____ _           _   ____        _      
/ ___| |__   __ _| |_| __ )  ___ | |_ ___
| |   | '_ \ / _` | __|  _ \ / _ \| __/ __|
| |___| | | | (_| | |_| |_) | (_) | |_\__ \
\____|_| |_|\__,_|\__|____/ \___/ \__|___/
                                          
 
Starting Wechaty v0.13.12 with Node.js v8.9.0 ...
Working directory: /bot
Executing babel-node --presets env mybot.js
12:08:54 WARN Wechaty init() DEPRECATED and will be removed after Jun
2018. Use start() instead. 12:08:54 INFO Wechaty v0.13.12 starting...
12:08:54 ERR PuppetWebBridge init() exception: AssertionError
[ERR_ASSERTION]: Chromium revision is not downloaded. Run "npm install"
12:08:54 ERR PuppetWeb initBridge() exception: Chromium revision is not
downloaded. Run "npm install" 12:08:54 WARN PuppetWebBridge quit()
page.close() exception: TypeError: Cannot read property 'close' of
undefined 12:08:54 WARN PuppetWebBridge quit() browser.close()
exception: TypeError: Cannot read property 'close' of undefined
12:08:54 ERR PuppetWeb init() exception: AssertionError
[ERR_ASSERTION]: Chromium revision is not downloaded. Run "npm install"
12:08:54 ERR Wechaty start() exception: Chromium revision is not
downloaded. Run "npm install" (node:32)
UnhandledPromiseRejectionWarning: Unhandled promise rejection
(rejection id: 1): AssertionError [ERR_ASSERTION]: Chromium revision is
not downloaded. Run "npm install" (node:32) [DEP0018]
DeprecationWarning: Unhandled promise rejections are deprecated. In the
future, promise rejections that are not handled will terminate the
Node.js process with a non-zero exit code.
 
__        __        _           _         
\ \      / /__  ___| |__   __ _| |_ _   _ 
  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | |
   \ V  V /  __/ (__| | | | (_| | |_| |_| |
    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, |
                                     |___/ 
____________________________________________________
https://www.chatie.io
  _____      _ _      ___  
| ____|_  _(_) |_   / _ \ 
|  _| \ \/ / | __| | | | |
| |___ >  <| | |_  | |_| |
|_____/_/\_\_|\__|  \___/

**Comment by zixia** [comment]
@zhuaoyuan Could you please run the following command and submit the output log?

```shell
docker run zixia/wechaty:0.12.0 doctor
docker run zixia/wechaty:0.12.0 test
```

**Comment by zhuaoyuan** [comment]
@zixia
Have sent logs to zixia@zixia.net

**Comment by zixia** [comment]
@zhuaoyuan Please post the logs by replying this issue, because we can easily track all the related information. 

Thanks!

**Comment by zhuaoyuan** [comment]
@zixia Here it is.
[wechaty-log.txt](https://github.com/Chatie/wechaty/files/1445621/wechaty-log.txt)
