### ISSUE TITLE
Can't Login after Scan

### ISSUE THREAD

**Issue by Randyedu** [Chatie/wechaty#880]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)  South of China
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using? Aliyun

### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 

Starting Wechaty v0.10.17 with Node.js v7.10.1 ...

> wechaty@0.10.17 doctor /wechaty
> npm run check-node-version && ts-node bin/doctor

> wechaty@0.10.17 check-node-version /wechaty
> check-node-version --node ">= 7"

node: 7.10.1
npm: 4.2.0
yarn: 1.2.1

  #### Wechaty Doctor

  1. Wechaty version: #git[b1c04f5]
  2. Linux x64 version 4.4.0-62-generic memory 69/992 MB
  3. Docker: true
  4. Node version: v7.10.1
  5. Tcp IPC TEST: PASS
  ****6. Chromedriver: Error: spawnSync chromedriver ENOENT****

### Expected behavior

Login to Wechaty after scan.  i would login using lower version of wechaty

### Actual behavior
/* if (/Wechaty/i.test(room.get('name'))) { */

Loading...

19:10:22 INFO Wechaty v0.10.17 initializing...
19:10:22 INFO PuppetWebBridge init() initBrowser() down
19:10:22 INFO PuppetWebBridge initPage() before page.goto(domain)
19:10:23 INFO PuppetWebBridge initPage() after page.goto(domain)
19:10:23 INFO PuppetWebBridge init() initPage() down
https://login.weixin.qq.com/qrcode/4fJFdSSyaQ==
[0] Scan QR Code in above url to login:
https://login.weixin.qq.com/qrcode/4fJFdSSyaQ==
[201] Scan QR Code in above url to login:

### Steps to reproduce the behavior (and fixes, if any)
1.   docker run -ti --rm --volume="$(pwd)":/bot zixia/wechaty tuling123-bot.ts
2. scan the QRcode and confirm via mobile wechat
3. the Issue found

### Full Output Logs

```shell
$ WECHATY_LOG=silly npm run ts-node mybot.ts

# or 

$ WECHATY_LOG=silly node dist/mybot.js
```

<details>
<summary>
Show Logs
</summary>
### Paste the full output logs here with `WECHATY_LOG=silly` set 

```shell
# PASTE FULL LOG OUTPUT AT HERE:



```
</details>

**Comment by Jfeng3** [comment]
@zixia 
Same case. 
1. It seems the wechaty-bro.js never emits 'login' event
2. How can I debug wechaty-bro.js? How can I open the page opended by puppeteer ?

**Comment by zixia** [comment]
@Jfeng3 what's the version of your Wechaty?

You could try to use `WECHATY_HEAD=1 npm start` to show the browser window, and then you will be able to see what's happened in the Web Browser.

**Comment by Jfeng3** [comment]
thanks! @zixia

**Comment by zixia** [comment]
@Jfeng3 You are welcome.

**Comment by Jfeng3** [comment]
login confirmation之前 windowWechatyBro object exists 
login confirmation 之后 ，网页版login 成功 ，redirect, 但是window.WechatyBro 没有了
@zixia

**Comment by Jfeng3** [comment]
my problem is fixed .thanks for the help!

**Comment by zixia** [comment]
Could please tell me how could you fix the problem?

-- 
李卓桓
發自我的小霸王學習機

**Comment by Jfeng3** [comment]
@zixia 
Sorry I have not idea. 
I just went back to use wechaty-getting-started repo's code 
The thing I found is that before wechat confirmation, window.wechatyBro object exists 
Right after wechat confirmation, the webpage redirect then window.wechatyBro object disappear.
But it should have window.wechatyBro object there to function normally

**Comment by zixia** [comment]
Merge to #899
