### ISSUE TITLE
The scan code shows 201，Then there's no more

### ISSUE THREAD

**Issue by isuoge** [Chatie/wechaty#882]
### Provide Your Network Information

本地测试    node v6.10.0       wechaty v0.10.19    

 npm 运行

### Actual behavior
运行demo后扫码之后就201不动了。有时候是408，扫完之后就没反应了，微信客户端显示web端已登录。

#### demo.js
const { Wechaty } = require('wechaty')

Wechaty.instance() // Singleton
.on('scan', (url, code) => {
  if (!/201|200/.test(String(code))){
   let loginUrl = url.replace(/\/qrcode\//, '/l/')
   require('qrcode-terminal').generate(loginUrl)
}
console.log(`${url}\n[${code}] Scan QR Code in above url to login: `)
})
.on('login',       user => console.log(`User ${user} logined`))
.on('message',  message => console.log(`Message: ${message}`))
.init()

####info

https://login.weixin.qq.com/qrcode/4aJ78Mkc5g==
[408] Scan QR Code in above url to login:
https://login.weixin.qq.com/qrcode/4aJ78Mkc5g==
[201] Scan QR Code in above url to login:

**Comment by zixia** [comment]
Sorry, but your code snip is not RUNNABLE.

Please re-post your log messages with `WECHATY_LOG=silly` environment variable set.

**Comment by zixia** [comment]
Merge to #899
