### ISSUE TITLE
CANT RUN THE WECHATY-GETTING-STARTED, PUPPETWEBROWSER valid() getSession()

### ISSUE THREAD

**Issue by lonson** [Chatie/wechaty#891]
### Provide Your Network Information

1. Where is the location of your server? (Out China)
out china
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?
digitalocean

MY ISSUE IS FOLLOWING
13:23:31 INFO Wechaty v0.7.95 initializing...
13:23:31 WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: Server terminated early with status 127
13:23:31 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: Server terminated early with status 127
13:23:31 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
13:23:31 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 1
(node:3946) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Server terminated early with status 127
(node:3946) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
13:23:31 WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: Server terminated early with status 127
13:23:31 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: Server terminated early with status 127
13:23:31 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
13:23:31 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 2
(node:3946) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Server terminated early with status 127
13:23:31 WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: Server terminated early with status 127
13:23:31 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: Server terminated early with status 127
13:23:31 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
13:23:31 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 3
(node:3946) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Server terminated early with status 127

### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 
  GNU nano 2.3.1                文件： /root/.npm/_logs/2017-10-17T05_26_41_133Z-debug.log                                    

0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v8.7.0/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v8.7.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'doctor' ]
2 info using npm@5.4.2
3 info using node@v8.7.0
4 verbose stack Error: missing script: doctor
4 verbose stack     at run (/root/.nvm/versions/node/v8.7.0/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /root/.nvm/versions/node/v8.7.0/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /root/.nvm/versions/node/v8.7.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /root/.nvm/versions/node/v8.7.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:402:5
4 verbose stack     at checkBinReferences_ (/root/.nvm/versions/node/v8.7.0/lib/node_modules/npm/node_modules/read-package-js$
4 verbose stack     at final (/root/.nvm/versions/node/v8.7.0/lib/node_modules/npm/node_modules/read-package-json/read-json.j$
4 verbose stack     at then (/root/.nvm/versions/node/v8.7.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js$
4 verbose stack     at /root/.nvm/versions/node/v8.7.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:348:12
4 verbose stack     at /root/.nvm/versions/node/v8.7.0/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:514:3)
5 verbose cwd /home/wwwroot/wechaty-getting-started
6 verbose Linux 3.10.0-693.2.2.el7.x86_64
7 verbose argv "/root/.nvm/versions/node/v8.7.0/bin/node" "/root/.nvm/versions/node/v8.7.0/bin/npm" "run" "doctor"
8 verbose node v8.7.0
9 verbose npm  v5.4.2
10 error missing script: doctor
11 verbose exit [ 1, true ]

### Full Output Logs

```shell
$ WECHATY_LOG=silly npm run ts-node mybot.ts

# or 

$ WECHATY_LOG=silly node dist/mybot.js
```

<details>
<summary>
Show Logs
</summary>
### Paste the full output logs here with `WECHATY_LOG=silly` set 

```shell
# PASTE FULL LOG OUTPUT AT HERE:



```
</details>

**Comment by zixia** [comment]
Please try to use the latest version v0.10 or above.

**Comment by lonson** [comment]
which one use the latest version?

**Comment by zixia** [comment]
@lijiarui Could you please update your starter project to use v0.10?
