### ISSUE TITLE
Disable HotImport in PRODUCTION Environment

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#907]
the `hotImport` from module `hot-import` will enable us to automatically reload listeners of Wechaty.

Should be automatically disabled if `process.env.NODE_ENV === 'production'`.

See:

https://github.com/Chatie/wechaty/blob/dd2238de97cf349d8349aca10d1975600fd819e6/src/wechaty.ts#L365-L372

**Comment by xinbenlv** [comment]
Should the WeChaty provide this feature out of box or should it be configurable and overridable by the user?

**Comment by zixia** [comment]
My opinion is to provide this feature out of the box.

And if `process.env.NODE_ENV === 'production'`, then we should disable all the watchers inside hotImport because it should be not necessary and will cost some CPU circles.

The solution is to call `hotImport()` with the second parameter `watch = false`, like: `hotImport(absoluteFilename, false)`.

**Comment by zixia** [comment]
Fixed by the latest commit.
