### ISSUE TITLE
[FR] Create an example for using hot-import for listener and other modules

### ISSUE THREAD

**Issue by xinbenlv** [Chatie/wechaty#923]
Since [this commit](https://github.com/Chatie/wechaty/commit/c47715b4470e7ade9a2590fd3e66985dd7977622) we can use hot-import, but here has not been an example provided. Let's add an example to demonstrate how to do it.

**Comment by xinbenlv** [comment]
Assigning to myself

**Comment by lijiarui** [comment]
@xinbenlv see this [hot-import](https://github.com/zixia/hot-import)
Chatie hot-import come from here, and also need an example and simple doc as [issue](https://github.com/zixia/hot-import/issues/4) said. Are you interested in this?

**Comment by xinbenlv** [comment]
I'd like to assign to myself but seems dont have edit permission, weird

**Comment by lijiarui** [comment]
add assign 😄
