### ISSUE TITLE
[CI] Homebrew must be run under Ruby 2.3! You're running 2.0.0. (RuntimeError)

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#936]
TravisCI MacOS Error:

```
/usr/local/Homebrew/Library/Homebrew/brew.rb:12:in `<main>': Homebrew must be run under Ruby 2.3! You're running 2.0.0. (RuntimeError)
```

https://travis-ci.org/Chatie/wechaty/jobs/294655691#L3326

**Comment by zixia** [comment]
Run `brew uninstall --force brew-cask` will prevent this error.

Forgot the reason for why...

**Comment by TheMangoTrain** [comment]
Thanks, worked for me. Had same error as OP.

**Comment by danersan** [comment]
crap, that's worked for me, thanks buddy
