### ISSUE TITLE
Dockerfile.onbuild build error.Directory permissions wrong

### ISSUE THREAD

**Issue by mukaiu** [Chatie/wechaty#961]
https://github.com/Chatie/wechaty/blob/81ff9621025a8176e779d345025a4631cd9f2710/Dockerfile.onbuild#L12

Directory permissions wrong

rm: cannot remove '/tmp/npm-7-34a7984e': Operation not permitted
![image](https://user-images.githubusercontent.com/7746790/32635564-cd36d0b8-c5eb-11e7-8eed-229833a586a5.png)

![image](https://user-images.githubusercontent.com/7746790/32635549-b915a14a-c5eb-11e7-840c-ccbc03c362eb.png)

**Comment by zixia** [comment]
Good catch!
