### ISSUE TITLE
How to auto add friend from rooms

### ISSUE THREAD

**Issue by forconz** [Chatie/wechaty#969]
As we know , we can add friends from room when we use WeChat for Web.

ItChat https://github.com/littlecodersh/ItChat/tree/robot

@itchat.msg_register('Friends')
def add_friend(msg):
    itchat.add_friend(**msg['Text'])
    itchat.get_contract()
    itchat.send_msg(msg['RecommendInfo']['UserName'], 'Nice to meet you!')

And I find some userful links:
微信网页版功能添加：群人员添加好友
https://bbs.125.la/forum.php?mod=viewthread&tid=13963316&extra=page=8
在线微信一键加群内好友怎么用
https://jingyan.baidu.com/article/cd4c2979082e2a756f6e6053.html

**How can I use wechaty to auto add friend from a room?**

**Comment by zixia** [comment]
Please see:
1. https://github.com/Chatie/wechaty/issues/6#issuecomment-252425225
1. https://github.com/Chatie/wechaty/issues/33

**Comment by dongeast** [comment]
This is not my result. 
I want to send friend request to other. 
I find a function of FriendRequest class 
`abstract send(contact: Contact, hello: string): Promise<boolean>;`
but I did not get the example in friend-bot.js

> 1. Send Friend Request
I only find **2. Accept Friend Request** and **3. Recongenize Verify Message**.

I know how to add friend(Contact) to a group(Room) 
`yield room.add(contact);`

and I know how to auto  Friend Request / Contact Add & Del #6
`request.accept(); // auto accepted`

I will try the code(implementation of friend-request.js):
`    /**
     * Send a new friend request
     * @param {Contact} contact
     * @param {string} [hello='Hi']
     * @returns {Promise<boolean>} Return a Promise, true for accept successful, false for failure.
     * @example
     * const from = message.from()
     * const request = new FriendRequest()
     * request.send(from, 'hello~')
     */
    send(contact, hello = 'Hi') {
        return __awaiter(this, void 0, void 0, function* () {
            config_1.log.verbose('PuppetWebFriendRequest', 'send(%s)', contact);
            if (!contact) {
                throw new Error('contact not found');
            }
            this.contact = contact;
            this.type = 'send';
            if (hello) {
                this.hello = hello;
            }
            return config_1.config.puppetInstance()
                .friendRequestSend(contact, hello);
        });
    }
`

if you have time, please provider a example in friend-bot.js:

> send friend request to other

**Comment by zixia** [comment]
Yes, I agree that we should have an example for `FriendRequest` because that would be easy to get started.

Hope someone could make a PR to add this example code.

**Comment by dongeast** [comment]
.on('message', m => {
    if (m.self()) {
        return;
    }

    const c = m.from();
    // Check if contact is stranger
    if(c.stranger()) // True for not friend of the bot, False for friend of the bot, null for unknown.
    {
        const fr = new FriendRequest();
        fr.send(from, 'hello~')
    }

is this example code ok?

**Comment by zixia** [comment]
I think it should workable for your case.

**Comment by dongeast** [comment]
const _from = m.from();
    debug('message.from(contact):');
    debug(_from);
    console.log(`message.from id=${_from.id} name=${_from.name()} alias=${_from.alias()} province=${_from.province()} city=${_from.city()} avatarUrl=${_from.avatarUrl()}`)
    // Check if message.from(contact) is stranger
    if(_from.stranger()) // True for not friend of the bot, False for friend of the bot, null for unknown.
    {
        console.log(`message.from(name=${_from.name()}  alias=${_from.alias()}) is not friend of the bot`);
        const _FriendRequest = new FriendRequest();
        _FriendRequest.send(_from, 'hello~');
    }
    else
    {
        console.log(`message.from(name=${_from.name()}  alias=${_from.alias()}) is friend or unknown of the bot`);
    }

**Comment by zixia** [comment]
Hope this issue had been resolved.
