### ISSUE TITLE
How dismiss a room in web wechat ?

### ISSUE THREAD

**Issue by JETWLL** [Chatie/wechaty#977]
#### Environment
web wechat 

#### Detail
There is a room which created by me and I want to dismiss it. But, I can't find a method to resolve this problem.
Thank you !

**Comment by zixia** [comment]
We can not do it in Web Wechat because Tencent does not have this API for the Web version.

This feature might be able to implement by other versions of Puppet.

See: #1167

**Comment by zixia** [comment]
Close this issue because the question had already been answered.
