### ISSUE TITLE
[RUMOR] wechat will close webapi for wechat

### ISSUE THREAD

**Issue by htoooth** [Chatie/wechaty#990]
https://share.iclient.ifeng.com/shareNews?fromType=vampire&forward=1&aid=38628857#backhead#backhead

Is it realy ?

**Comment by zixia** [comment]
No, it's not really, it's a RUMOR.

See: https://github.com/Chatie/wechaty/issues/673#issuecomment-347400196

**Comment by letitfly** [comment]
I got this message from a relatively new account when trying to login into wx.qq.com:

<error><ret>1203</ret><message>为了你的帐号安全，此微信号已不允许登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com</message></error>

That message seems to indicate that this account is permanently blocked from web wechat. But I can login into desktop (mac) wechat client with that account. 

What api is desktop client using? not webapi? Can we try to emulate desktop api?

**Comment by letitfly** [comment]
Anyone knows where to buy a wechat account that can be used in wechaty? That maybe the only option left to create new bot.

**Comment by vipplayerdev** [comment]
Infact,I dont know how and where to buy it.

**Comment by zixia** [comment]
For those developers who want to use Wechaty but be limited by the Web API: 

Please have a look at our in-alpha testing Wechaty v0.15, with new Puppet: PuppetPadchat. PuppetPadchat will let you login your bot without any problem.

See: #1296

**Comment by brabayounew** [comment]
now almost account will be noticed : 1203为了你的帐号安全，此微信号已不允许登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com Mac微信下载地址：https://mac.weixin.qq.com

web API can't be used any more
