### ISSUE TITLE
我实在解决不了这个问题了~菜鸟一枚

### ISSUE THREAD

**Issue by orrvan** [Chatie/wechaty#998]
昨天还可以直接运行~
然后我用的CMD：
docker run -ti --rm --volume="%cd%":/bot zixia/wechaty run demo
docker run -ti --rm --volume="%cd%":/bot zixia/wechaty tuling123-bot.ts
均正常，
今天更新系统之后，
docker run -ti --rm --volume="%cd%":/bot zixia/wechaty run demo
这个还是可以正常运行
然而**docker run -ti --rm --volume="%cd%":/bot zixia/wechaty tuling123-bot.ts**
会报错：
Starting Wechaty v0.13.34 with Node.js v8.9.1 ...
ERROR: can not found bot file: tuling123-bot.ts

**Comment by orrvan** [comment]
好像是docker分享的问题，已解决~

**Comment by zixia** [comment]
It's my first time seeing the syntax for Win32: `--volume="%cd%":/bot` 

Interesting, and good luck to you!
